# -*- coding: utf-8 -*-
"""falling_home.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dxiA0wnOfBUX_d_xJPaGo3gl1j10K8k8
"""

# ============================================================
# CELL 1 — Constants & Reentry Physics Foundation
# Day 9 — Falling Home
# Code Beyond the Earth | April 9, 2026
# ============================================================
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from matplotlib.patches import FancyBboxPatch, FancyArrowPatch
from matplotlib.gridspec import GridSpec
from datetime import datetime, timezone

# ── Physical constants ────────────────────────────────────────
G_ACCEL    = 9.81          # m/s² surface gravity
R_EARTH    = 6_371_000     # m
RHO_0      = 1.225         # kg/m³ sea level density
H_SCALE    = 8_500         # m atmospheric scale height
SIGMA_SB   = 5.67e-8       # Stefan-Boltzmann W/m²K⁴

# ── Orion capsule parameters ──────────────────────────────────
ORION_MASS      = 9_300    # kg (crew module)
ORION_DIAM      = 5.03     # m base diameter
ORION_AREA      = np.pi * (ORION_DIAM/2)**2   # m²
ORION_CD        = 1.38     # drag coefficient (blunt body)
ORION_BETA      = ORION_MASS / (ORION_CD * ORION_AREA)
                            # ballistic coefficient kg/m²

# ── Reentry initial conditions ────────────────────────────────
V_ENTRY_MS   = 11_176      # m/s  (25,000 mph)
V_ENTRY_MPH  = 25_000
H_ENTRY      = 120_000     # m    entry interface
GAMMA_LOFTED = -5.5        # deg  lofted entry angle
GAMMA_STEEP  = -7.5        # deg  steeper Artemis II fix
GAMMA_BALLISTIC = -10.0    # deg  ballistic (no skip)

# ── Artemis I vs II fix ───────────────────────────────────────
# Artemis I: shallow angle → long heating duration
#            → more ablation, large chunks peeling off
# Artemis II fix: steeper angle → higher peak heat
#                 → shorter duration → less total ablation
ARTEMIS_I_ANGLE  = -5.2   # deg (shallower)
ARTEMIS_II_ANGLE = -6.8   # deg (steeper fix)

# ── Heat shield: Avcoat properties ───────────────────────────
AVCOAT_DENSITY     = 512    # kg/m³
AVCOAT_THICKNESS   = 0.058  # m  (5.8 cm)
AVCOAT_K           = 0.21   # W/mK thermal conductivity
AVCOAT_CP          = 1_260  # J/kgK specific heat
AVCOAT_T_ABLATE    = 3_316  # K  ablation temperature
AVCOAT_H_ABLATE    = 4.5e6  # J/kg heat of ablation

# ── Reentry timeline (NASA Henfling briefing) ─────────────────
# Times in minutes from entry interface
TIMELINE = [
    ( 0.0,  120_000,  V_ENTRY_MS,      0, 0.0,
      'Entry interface (EI)\n120 km'),
    ( 1.0,   90_000,  10_800,        400, 0.5,
      'Heating begins'),
    ( 2.5,   65_000,   9_200,      2_760, 3.9,
      'Peak heating 2,760°C\nPeak g-force 3.9g'),
    ( 4.0,   55_000,   7_100,      2_200, 3.2,
      'Skip manoeuvre\n(lofted entry)'),
    ( 6.0,   45_000,   5_500,      1_200, 1.8,
      'Post-skip recovery'),
    ( 8.0,   35_000,   3_200,        300, 0.8,
      'Plasma blackout ends\n~35 km'),
    ( 9.5,    6_700,     900,         80, 0.3,
      'Forward bay cover\njettisoned'),
    (10.0,    6_100,     800,         60, 0.2,
      'Drogue chutes\ndeploy  22,000 ft'),
    (11.0,    1_800,     350,         40, 0.1,
      'Main chutes deploy\n6,000 ft'),
    (13.0,        0,       8,         25, 0.0,
      'Splashdown\nPacific Ocean'),
]

t_min  = np.array([e[0] for e in TIMELINE])
h_m    = np.array([e[1] for e in TIMELINE])
v_ms   = np.array([e[2] for e in TIMELINE])
temp_c = np.array([e[3] for e in TIMELINE])
g_load = np.array([e[4] for e in TIMELINE])
labels = [e[5] for e in TIMELINE]
colors_ev = [
    '#EF4444','#F59E0B','#EF4444',
    '#3B82F6','#3B82F6','#475569',
    '#10B981','#10B981','#10B981',
    '#3B82F6'
]

# ── Atmospheric density model ─────────────────────────────────
def rho_atm(h):
    """Exponential atmosphere density kg/m³."""
    return RHO_0 * np.exp(-h / H_SCALE)

# ── Stagnation point heat flux (Sutton-Graves) ────────────────
def q_stag(v_ms, h_m, R_nose=2.0):
    """
    Stagnation heat flux W/m²
    Sutton-Graves approximation
    R_nose: nose radius [m]
    """
    rho  = rho_atm(h_m)
    k_sg = 1.742e-4   # Sutton-Graves constant
    return k_sg * np.sqrt(rho / R_nose) * v_ms**3

# ── Drag deceleration ─────────────────────────────────────────
def drag_decel(v_ms, h_m):
    """Drag deceleration m/s²."""
    rho = rho_atm(h_m)
    return 0.5 * rho * v_ms**2 * \
           ORION_CD * ORION_AREA / ORION_MASS

# ── Print summary ─────────────────────────────────────────────
print("=" * 62)
print("   DAY 9 — FALLING HOME")
print("   Reentry physics + skip trajectory")
print("=" * 62)
print()
print("  Orion capsule parameters:")
print(f"    Mass            : {ORION_MASS:,} kg")
print(f"    Base diameter   : {ORION_DIAM} m")
print(f"    Reference area  : {ORION_AREA:.2f} m²")
print(f"    Drag coeff (Cd) : {ORION_CD}")
print(f"    Ballistic coeff : {ORION_BETA:.1f} kg/m²")
print()
print("  Entry conditions:")
print(f"    Velocity        : {V_ENTRY_MS:,} m/s  "
      f"({V_ENTRY_MPH:,} mph)")
print(f"    Altitude        : {H_ENTRY/1000:.0f} km")
print(f"    Artemis I angle : {ARTEMIS_I_ANGLE}°")
print(f"    Artemis II angle: {ARTEMIS_II_ANGLE}°")
print(f"    Fix             : steeper → less ablation")
print()
print("  Heat shield (Avcoat):")
print(f"    Thickness       : {AVCOAT_THICKNESS*100:.1f} cm")
print(f"    Ablation temp   : {AVCOAT_T_ABLATE:,} K "
      f"({AVCOAT_T_ABLATE-273:.0f}°C)")
print(f"    Heat of ablation: {AVCOAT_H_ABLATE/1e6:.1f} MJ/kg")
print(f"    Same material as Apollo — Avcoat")
print()
print("  Reentry timeline:")
for t, h, v, tc, g, lbl in TIMELINE:
    short = lbl.split('\n')[0]
    print(f"    T+{t:4.1f} min  "
          f"h={h/1000:6.1f} km  "
          f"v={v:,} m/s  "
          f"T={tc:,}°C  "
          f"{g}g  {short}")
print()
print("  Peak stagnation heat flux:")
q_peak = q_stag(V_ENTRY_MS * 0.9, 70_000)
print(f"    q_stag ≈ {q_peak/1e6:.1f} MW/m²")
print(f"    (at ~70km, 90% entry velocity)")
print("=" * 62)

# ============================================================
# CELL 2 — Thermal Model
# Heat flux, Avcoat ablation, Artemis I vs II comparison
# ============================================================
fig = plt.figure(figsize=(16, 10))
fig.patch.set_facecolor('#0D1117')
gs  = GridSpec(2, 3, figure=fig,
               hspace=0.45, wspace=0.38)

ax_flux  = fig.add_subplot(gs[0, :2])
ax_temp  = fig.add_subplot(gs[1, :2])
ax_avcoat= fig.add_subplot(gs[:, 2])

# ── fine time / altitude arrays ───────────────────────────────
t_fine = np.linspace(0, 13, 1000)
h_fine = np.interp(t_fine, t_min, h_m)
v_fine = np.interp(t_fine, t_min, v_ms)

# ── heat flux for both trajectories ──────────────────────────
# velocity profile scales slightly with entry angle
# steeper = faster through thin air, same peak heat
# but shorter duration

def v_profile(t, gamma_deg):
    """
    Approximate velocity profile for a given
    entry angle. Steeper = faster deceleration
    in upper atmosphere.
    """
    # deceleration scale factor
    scale = abs(gamma_deg) / abs(ARTEMIS_II_ANGLE)
    # compress/stretch timeline
    t_eff = t * scale
    return np.interp(t_eff, t_min, v_ms)

def h_profile(t, gamma_deg):
    scale = abs(gamma_deg) / abs(ARTEMIS_II_ANGLE)
    t_eff = t * scale
    return np.interp(t_eff, t_min, h_m)

# Artemis I: shallower → longer heating
# Artemis II: steeper  → shorter heating
q_a1  = np.array([
    q_stag(
        v_profile(t, ARTEMIS_I_ANGLE),
        h_profile(t, ARTEMIS_I_ANGLE))
    for t in t_fine])

q_a2  = np.array([
    q_stag(
        v_profile(t, ARTEMIS_II_ANGLE),
        h_profile(t, ARTEMIS_II_ANGLE))
    for t in t_fine])

temp_fine = np.interp(t_fine, t_min, temp_c)

# ── TOP: heat flux comparison ─────────────────────────────────
ax_flux.set_facecolor('#0D1117')
ax_flux.set_title(
    'Stagnation heat flux — '
    'Artemis I trajectory vs Artemis II fix',
    color='white', fontsize=11, pad=10)
ax_flux.set_ylabel('Heat flux (MW/m²)',
                   color='#94A3B8', fontsize=9)
ax_flux.tick_params(
    colors='#94A3B8', labelsize=8)
for sp in ['bottom', 'left']:
    ax_flux.spines[sp].set_color('#334155')
for sp in ['top', 'right']:
    ax_flux.spines[sp].set_visible(False)
ax_flux.grid(color='#1E293B',
             lw=0.6, zorder=0)

q_a1_mw = q_a1 / 1e6
q_a2_mw = q_a2 / 1e6

ax_flux.plot(t_fine, q_a1_mw,
             color='#EF4444', lw=2.0,
             ls='--', zorder=4,
             label=f'Artemis I angle '
                   f'({ARTEMIS_I_ANGLE}°) — '
                   f'shallower, longer')
ax_flux.plot(t_fine, q_a2_mw,
             color='#10B981', lw=2.5,
             zorder=5,
             label=f'Artemis II angle '
                   f'({ARTEMIS_II_ANGLE}°) — '
                   f'steeper, shorter')

ax_flux.fill_between(
    t_fine, q_a1_mw, q_a2_mw,
    where=(q_a1_mw > q_a2_mw),
    color='#EF4444', alpha=0.10,
    label='Extra ablation (Artemis I)')
ax_flux.fill_between(
    t_fine, q_a1_mw, q_a2_mw,
    where=(q_a2_mw >= q_a1_mw),
    color='#10B981', alpha=0.08)

# plasma blackout zone
ax_flux.axvspan(2.5, 8.0,
                color='#EF4444',
                alpha=0.05)
ax_flux.text(5.25, q_a2_mw.max() * 0.85,
             'PLASMA BLACKOUT',
             color='#EF4444',
             fontsize=8, ha='center',
             fontweight='bold')

# integrated heat load comparison
q1_total = np.trapz(q_a1_mw, t_fine * 60)
q2_total = np.trapz(q_a2_mw, t_fine * 60)
ax_flux.text(
    9.5, q_a2_mw.max() * 0.6,
    f'Total heat load:\n'
    f'Artemis I:  {q1_total:.0f} MJ/m²·s\n'
    f'Artemis II: {q2_total:.0f} MJ/m²·s\n'
    f'Reduction:  '
    f'{(1-q2_total/q1_total)*100:.0f}%',
    color='white', fontsize=8,
    linespacing=1.6,
    bbox=dict(
        boxstyle='round,pad=0.4',
        facecolor='#0F172A',
        edgecolor='#334155',
        alpha=0.9))

ax_flux.set_xlim(0, 13)
ax_flux.set_xticklabels([])
ax_flux.legend(
    facecolor='#1E293B',
    edgecolor='#334155',
    labelcolor='white', fontsize=8,
    loc='upper right')

# ── BOTTOM: surface temperature ───────────────────────────────
ax_temp.set_facecolor('#0D1117')
ax_temp.set_title(
    'Heat shield surface temperature '
    '— Avcoat ablation behaviour',
    color='white', fontsize=10, pad=8)
ax_temp.set_xlabel(
    'Minutes from entry interface',
    color='#94A3B8', fontsize=9)
ax_temp.set_ylabel('Temperature (°C)',
                   color='#94A3B8', fontsize=9)
ax_temp.tick_params(
    colors='#94A3B8', labelsize=8)
for sp in ['bottom', 'left']:
    ax_temp.spines[sp].set_color('#334155')
for sp in ['top', 'right']:
    ax_temp.spines[sp].set_visible(False)
ax_temp.grid(color='#1E293B',
             lw=0.6, zorder=0)

ax_temp.plot(t_fine, temp_fine,
             color='#F59E0B', lw=2.5,
             zorder=5)
ax_temp.fill_between(
    t_fine, temp_fine, 0,
    color='#F59E0B', alpha=0.08)

# material reference lines
mat_refs = [
    (AVCOAT_T_ABLATE - 273,
     '#EF4444',
     f'Avcoat ablation '
     f'({AVCOAT_T_ABLATE-273:.0f}°C)'),
    (1_535, '#F59E0B', 'Iron melts (1,535°C)'),
    (660,   '#3B82F6', 'Aluminium melts (660°C)'),
    (100,   '#475569', 'Water boils (100°C)'),
]
for val, col, label in mat_refs:
    if val <= temp_fine.max() * 1.1:
        ax_temp.axhline(
            val, color=col, lw=0.9,
            ls=':', alpha=0.7)
        ax_temp.text(
            0.3, val + 40, label,
            color=col, fontsize=7.5)

# peak annotation
pk_idx = np.argmax(temp_fine)
ax_temp.plot(
    t_fine[pk_idx], temp_fine[pk_idx],
    'o', color='#EF4444', ms=10,
    zorder=7,
    markeredgecolor='#0D1117',
    markeredgewidth=1.0)
ax_temp.annotate(
    f'Peak: 2,760°C\n'
    f'≈ ½ Sun surface\n'
    f'Avcoat chars and\n'
    f'ablates — not melts',
    xy=(t_fine[pk_idx],
        temp_fine[pk_idx]),
    xytext=(5.5, 2_400),
    color='#EF4444', fontsize=8,
    linespacing=1.5,
    arrowprops=dict(
        arrowstyle='->',
        color='#EF4444', lw=1.0))

ax_temp.axvspan(2.5, 8.0,
                color='#EF4444',
                alpha=0.05)
ax_temp.set_xlim(0, 13)
ax_temp.set_ylim(-100, 3_200)

# ── RIGHT: Avcoat explainer ───────────────────────────────────
ax_avcoat.set_facecolor('#0D1117')
ax_avcoat.axis('off')
ax_avcoat.set_title(
    'Avcoat heat shield',
    color='white', fontsize=10, pad=8)

avcoat_facts = [
    ('Material',
     'Silica fibers + epoxy\n'
     '+ resins in honeycomb',
     '#F59E0B'),
    ('Same as Apollo',
     'Used on all Apollo\n'
     'lunar missions 1968–72',
     '#94A3B8'),
    ('How it works',
     'Chars and ablates —\n'
     'carries heat away\n'
     'as material flakes off',
     '#10B981'),
    ('Thickness',
     '5.8 cm on Orion\n'
     'varies by heat zone',
     '#3B82F6'),
    ('Artemis I problem',
     'Large chunks peeled\n'
     'off unexpectedly\n'
     'during Artemis I',
     '#EF4444'),
    ('Artemis II fix',
     'Steeper entry angle\n'
     'Higher peak heat but\n'
     'shorter duration\n'
     '→ less total ablation',
     '#10B981'),
    ('Backup system',
     'Inner structure rated\n'
     'to survive if shield\n'
     'partially fails',
     '#475569'),
]

y_start = 0.92
row_h   = 0.125
for j, (title, desc, col) in \
        enumerate(avcoat_facts):
    y = y_start - j * row_h
    ax_avcoat.plot(
        0.05, y, 'o', color=col,
        ms=7, zorder=3,
        transform=ax_avcoat.transAxes)
    ax_avcoat.text(
        0.13, y + 0.012, title,
        transform=ax_avcoat.transAxes,
        color=col, fontsize=8,
        fontweight='bold', va='center')
    ax_avcoat.text(
        0.13, y - 0.030, desc,
        transform=ax_avcoat.transAxes,
        color='#475569', fontsize=7.5,
        va='center', linespacing=1.3)
    if j < len(avcoat_facts) - 1:
        ax_avcoat.plot(
            [0.05, 0.95],
            [y - row_h * 0.72,
             y - row_h * 0.72],
            transform=ax_avcoat.transAxes,
            color='#1E293B', lw=0.6)

plt.suptitle(
    'Orion Heat Shield — '
    'Thermal Analysis & Artemis I vs II Fix\n'
    'Stagnation heating model  ·  '
    'Sutton-Graves approximation  ·  '
    'Avcoat ablative material',
    color='white', fontsize=11,
    fontweight='bold', y=1.01)

plt.tight_layout()
plt.savefig(
    'artemis_thermal_model.png',
    dpi=120, facecolor='#0D1117',
    bbox_inches='tight')
plt.show()
print("Saved: artemis_thermal_model.png")

# ============================================================
# CELL 3 — Skip Trajectory Visualisation
# Ballistic vs lofted entry — altitude vs range
# ============================================================
fig, axes = plt.subplots(
    1, 2, figsize=(16, 8),
    gridspec_kw={'width_ratios': [1.6, 1]}
)
fig.patch.set_facecolor('#0D1117')

ax_traj = axes[0]
ax_comp = axes[1]

# ── numerical trajectory integration ─────────────────────────
def integrate_trajectory(
        gamma_deg, v0=V_ENTRY_MS,
        h0=H_ENTRY, dt=0.1,
        skip=True):
    """
    2D trajectory integration.
    gamma_deg : entry angle (negative = down)
    skip      : apply skip manoeuvre
    Returns (t, h, v, range_km, g_load, q)
    """
    gamma = np.radians(gamma_deg)
    v     = v0
    h     = float(h0)
    x     = 0.0      # downrange [m]
    t     = 0.0

    t_arr, h_arr  = [t], [h]
    v_arr, x_arr  = [v], [x]
    g_arr, q_arr  = [0.0], [0.0]

    skipped = False

    while h > 0 and t < 900:
        rho  = rho_atm(h)
        q_d  = 0.5 * rho * v**2
        drag = q_d * ORION_CD * \
               ORION_AREA / ORION_MASS
        grav = G_ACCEL * \
               (R_EARTH / (R_EARTH + h))**2

        # lift (blunt body has small L/D)
        ld   = 0.18   # lift-to-drag ratio
        lift = drag * ld

        # equations of motion
        # along-path deceleration
        dv   = -(drag + grav *
                 np.sin(-gamma))
        # path angle rate
        if v > 10:
            dgamma = (lift / v -
                      grav * np.cos(-gamma) / v +
                      v / (R_EARTH + h)) * \
                     (1 / v)
        else:
            dgamma = 0

        # skip manoeuvre —
        # at ~55 km pitch up momentarily
        if skip and h < 60_000 and \
           h > 45_000 and not skipped:
            gamma = gamma - \
                    np.radians(3.0)
            skipped = True

        gamma += dgamma * dt
        v     = max(v + dv * dt, 5)
        h     = h + v * np.sin(gamma) * dt
        x    += v * np.cos(-gamma) * dt
        t    += dt

        g_l  = drag / G_ACCEL
        q_s  = q_stag(v, max(h, 1000))

        t_arr.append(t)
        h_arr.append(max(h, 0))
        v_arr.append(v)
        x_arr.append(x)
        g_arr.append(g_l)
        q_arr.append(q_s)

        if h <= 0:
            break

    return (np.array(t_arr) / 60,
            np.array(h_arr) / 1000,
            np.array(v_arr),
            np.array(x_arr) / 1000,
            np.array(g_arr),
            np.array(q_arr) / 1e6)

# compute three trajectories
t_loft, h_loft, v_loft, \
    x_loft, g_loft, q_loft = \
    integrate_trajectory(
        ARTEMIS_II_ANGLE, skip=True)

t_ball, h_ball, v_ball, \
    x_ball, g_ball, q_ball = \
    integrate_trajectory(
        GAMMA_BALLISTIC, skip=False)

t_a1, h_a1, v_a1, \
    x_a1, g_a1, q_a1_int = \
    integrate_trajectory(
        ARTEMIS_I_ANGLE, skip=True)

# ── LEFT: altitude vs range ───────────────────────────────────
ax_traj.set_facecolor('#060F1A')
ax_traj.set_title(
    'Entry trajectory comparison — '
    'lofted vs ballistic',
    color='white', fontsize=12, pad=10)
ax_traj.set_xlabel(
    'Downrange distance (km)',
    color='#94A3B8', fontsize=9)
ax_traj.set_ylabel(
    'Altitude (km)',
    color='#94A3B8', fontsize=9)
ax_traj.tick_params(
    colors='#94A3B8', labelsize=8)
for sp in ['bottom', 'left']:
    ax_traj.spines[sp].set_color('#334155')
for sp in ['top', 'right']:
    ax_traj.spines[sp].set_visible(False)
ax_traj.grid(color='#1E293B',
             lw=0.6, zorder=0)

# atmosphere layers
layers = [
    (0,   12,  '#0D1B2E', 'Troposphere'),
    (12,  50,  '#0A1525', 'Stratosphere'),
    (50,  85,  '#07101C', 'Mesosphere'),
    (85,  120, '#050D17', 'Thermosphere'),
]
for y0, y1, col, name in layers:
    ax_traj.axhspan(y0, y1,
                    color=col, alpha=0.9,
                    zorder=1)
    ax_traj.text(
        5, (y0+y1)/2, name,
        color='#1E3A5C', fontsize=7,
        va='center', style='italic')

# trajectories
ax_traj.plot(
    x_loft, h_loft,
    color='#10B981', lw=3.0,
    zorder=5,
    label=f'Artemis II lofted '
          f'({ARTEMIS_II_ANGLE}°)')
ax_traj.plot(
    x_a1, h_a1,
    color='#F59E0B', lw=2.0,
    ls='--', zorder=4,
    label=f'Artemis I shallower '
          f'({ARTEMIS_I_ANGLE}°)',
    alpha=0.8)
ax_traj.plot(
    x_ball, h_ball,
    color='#EF4444', lw=1.8,
    ls=':', zorder=3,
    label=f'Ballistic '
          f'({GAMMA_BALLISTIC}°) — '
          f'no skip',
    alpha=0.7)

# skip manoeuvre annotation
skip_idx = np.argmin(
    np.abs(h_loft - 52))
if skip_idx < len(x_loft):
    ax_traj.annotate(
        'Skip manoeuvre\n'
        'Orion pitches up\n'
        'briefly — extends\n'
        'path, reduces peak g',
        xy=(x_loft[skip_idx],
            h_loft[skip_idx]),
        xytext=(x_loft[skip_idx] - 180,
                h_loft[skip_idx] + 25),
        color='#10B981', fontsize=8,
        linespacing=1.5,
        arrowprops=dict(
            arrowstyle='->',
            color='#10B981', lw=1.0))

# plasma blackout zone
pk_q_idx = np.argmax(q_loft)
pk_x     = x_loft[pk_q_idx]
bk_start = max(0, pk_q_idx - 150)
bk_end   = min(len(x_loft)-1,
               pk_q_idx + 400)
ax_traj.fill_between(
    x_loft[bk_start:bk_end],
    0,
    h_loft[bk_start:bk_end],
    color='#EF4444', alpha=0.08,
    zorder=2, label='Plasma blackout zone')

# event markers on lofted trajectory
key_h = [120, 70, 50, 6.7, 1.8, 0]
key_labels = [
    'EI', 'Peak\nheat',
    'Skip', 'Drogue\nchutes',
    'Main\nchutes', 'Splash']
key_cols = [
    '#EF4444','#F59E0B','#3B82F6',
    '#10B981','#10B981','#3B82F6']

for kh, kl, kc in zip(
        key_h, key_labels, key_cols):
    idx = np.argmin(
        np.abs(h_loft - kh))
    if idx < len(x_loft):
        ax_traj.plot(
            x_loft[idx],
            h_loft[idx],
            'o', color=kc, ms=9,
            zorder=7,
            markeredgecolor='#0D1117',
            markeredgewidth=0.8)

# Earth surface
ax_traj.axhline(
    0, color='#1B4FD8',
    lw=2.5, alpha=0.8, zorder=6)
ax_traj.fill_between(
    [0, x_loft[-1] + 50],
    -8, 0,
    color='#1B4FD8', alpha=0.25,
    zorder=5)
ax_traj.text(
    x_loft[-1] * 0.5, -5,
    'Pacific Ocean',
    color='#3B82F6', fontsize=8,
    ha='center')

ax_traj.set_xlim(
    -20, max(x_ball.max(),
             x_loft.max()) + 50)
ax_traj.set_ylim(-8, 130)
ax_traj.legend(
    facecolor='#1E293B',
    edgecolor='#334155',
    labelcolor='white', fontsize=8,
    loc='upper right')

# ── RIGHT: comparison panel ───────────────────────────────────
ax_comp.set_facecolor('#0D1117')
ax_comp.axis('off')
ax_comp.set_title(
    'Entry comparison\nkey metrics',
    color='white', fontsize=10, pad=8)

# g-load profile subplot
ax_g = fig.add_axes([
    0.675, 0.55, 0.29, 0.32
])
ax_g.set_facecolor('#0D1117')
ax_g.tick_params(
    colors='#475569', labelsize=7)
for sp in ['bottom', 'left']:
    ax_g.spines[sp].set_color('#334155')
for sp in ['top', 'right']:
    ax_g.spines[sp].set_visible(False)
ax_g.grid(color='#1E293B',
          lw=0.5, zorder=0)
ax_g.set_title(
    'G-force during reentry',
    color='white', fontsize=8, pad=4)

ax_g.plot(t_loft,
          np.clip(g_loft, 0, 8),
          color='#10B981', lw=2.0,
          label='Lofted (AII)')
ax_g.plot(t_ball,
          np.clip(g_ball, 0, 8),
          color='#EF4444', lw=1.5,
          ls='--', label='Ballistic')
ax_g.axhline(3.9, color='#EC4899',
             lw=1.0, ls=':',
             alpha=0.8)
ax_g.text(0.3, 4.0,
          'Peak: 3.9g (nominal)',
          color='#EC4899', fontsize=6.5)
ax_g.set_xlabel(
    'Minutes from EI',
    color='#475569', fontsize=6.5)
ax_g.set_ylabel(
    'G-force', color='#475569',
    fontsize=6.5)
ax_g.legend(
    facecolor='#1E293B',
    edgecolor='#334155',
    labelcolor='white',
    fontsize=6, loc='upper right')
ax_g.set_xlim(0, 13)
ax_g.set_ylim(0, 8.5)

# comparison table
comp_rows = [
    ('Entry angle',
     f'{ARTEMIS_I_ANGLE}°',
     f'{ARTEMIS_II_ANGLE}°'),
    ('Peak heat',
     'Lower',
     'Higher'),
    ('Heat duration',
     'Longer',
     'Shorter ✓'),
    ('Total ablation',
     'More (chunks)',
     'Less ✓'),
    ('Peak g-force',
     '~4.5g',
     '3.9g ✓'),
    ('Skip manoeuvre',
     'Yes',
     'Yes'),
    ('L/D ratio',
     '0.18', '0.18'),
    ('Splashdown',
     'Pacific',
     'Pacific'),
]

y_top = 0.50
rh    = 0.055
ax_comp.text(
    0.05, y_top + 0.03,
    'Parameter',
    transform=ax_comp.transAxes,
    color='#64748B', fontsize=7.5,
    fontweight='bold')
ax_comp.text(
    0.48, y_top + 0.03,
    'Artemis I',
    transform=ax_comp.transAxes,
    color='#F59E0B', fontsize=7.5,
    fontweight='bold', ha='center')
ax_comp.text(
    0.78, y_top + 0.03,
    'Artemis II',
    transform=ax_comp.transAxes,
    color='#10B981', fontsize=7.5,
    fontweight='bold', ha='center')
ax_comp.plot(
    [0.03, 0.97],
    [y_top, y_top],
    transform=ax_comp.transAxes,
    color='#334155', lw=0.8)

for j, (param, a1v, a2v) in \
        enumerate(comp_rows):
    y = y_top - 0.02 - j * rh
    ax_comp.text(
        0.05, y, param,
        transform=ax_comp.transAxes,
        color='#64748B', fontsize=7.5,
        va='center')
    ax_comp.text(
        0.48, y, a1v,
        transform=ax_comp.transAxes,
        color='#F59E0B', fontsize=7.5,
        ha='center', va='center')
    ax_comp.text(
        0.78, y, a2v,
        transform=ax_comp.transAxes,
        color='#10B981', fontsize=7.5,
        ha='center', va='center')
    if j < len(comp_rows) - 1:
        ax_comp.plot(
            [0.03, 0.97],
            [y - rh * 0.62,
             y - rh * 0.62],
            transform=ax_comp.transAxes,
            color='#1E293B', lw=0.5)

plt.suptitle(
    'Skip Trajectory — '
    'Lofted Entry vs Ballistic\n'
    'The fix that made Artemis II '
    'safer than Artemis I',
    color='white', fontsize=11,
    fontweight='bold', y=1.01)

plt.tight_layout()
plt.savefig(
    'artemis_skip_trajectory.png',
    dpi=120, facecolor='#0D1117',
    bbox_inches='tight')
plt.show()
print("Saved: artemis_skip_trajectory.png")

# ============================================================
# CELL 4 — Deceleration + Parachute Sequence
# ============================================================
fig, (ax_decel, ax_chute) = plt.subplots(
    1, 2, figsize=(16, 8),
    gridspec_kw={'width_ratios': [1.2, 1]}
)
fig.patch.set_facecolor('#0D1117')

for ax in [ax_decel, ax_chute]:
    ax.set_facecolor('#0D1117')
    ax.tick_params(colors='#94A3B8',
                   labelsize=8)
    for sp in ['bottom', 'left']:
        ax.spines[sp].set_color('#334155')
    for sp in ['top', 'right']:
        ax.spines[sp].set_visible(False)
    ax.grid(color='#1E293B',
            lw=0.6, zorder=0)

# ── LEFT: velocity + g-force ──────────────────────────────────
ax_decel.set_title(
    'Velocity and g-force — '
    'full reentry sequence',
    color='white', fontsize=11, pad=10)
ax_decel.set_xlabel(
    'Minutes from entry interface',
    color='#94A3B8', fontsize=9)
ax_decel.set_ylabel(
    'Velocity (m/s)',
    color='#94A3B8', fontsize=9)

t_fine_r  = np.linspace(0, 13, 1000)
v_fine_r  = np.interp(t_fine_r, t_min, v_ms)
g_fine_r  = np.interp(t_fine_r, t_min, g_load)
h_fine_r  = np.interp(t_fine_r, t_min, h_m)

# velocity — log scale
ax_decel.set_yscale('log')

# colour by phase
from matplotlib.collections import LineCollection
pts  = np.array(
    [t_fine_r, v_fine_r]).T\
    .reshape(-1, 1, 2)
segs = np.concatenate(
    [pts[:-1], pts[1:]], axis=1)
g_norm = g_fine_r / g_fine_r.max()
lc = LineCollection(
    segs, cmap='RdYlGn_r',
    norm=plt.Normalize(0, 1),
    linewidth=3.0, zorder=5)
lc.set_array(g_norm[:-1])
ax_decel.add_collection(lc)

cbar = plt.colorbar(
    lc, ax=ax_decel, shrink=0.6,
    pad=0.01)
cbar.set_label(
    'G-force intensity',
    color='white', fontsize=8)
cbar.ax.tick_params(
    colors='#94A3B8', labelsize=7)
cbar.set_ticks([0, 0.5, 1.0])
cbar.set_ticklabels(
    ['0g', '~2g', f'{g_load.max():.1f}g'])

# reference lines
vref = [
    (V_ENTRY_MS, '#EF4444',
     f'Entry: {V_ENTRY_MPH:,} mph'),
    (343,        '#F59E0B',
     'Speed of sound (343 m/s)'),
    (8,          '#10B981',
     'Splashdown: ~17 mph (8 m/s)'),
]
for vval, col, label in vref:
    ax_decel.axhline(
        vval, color=col,
        lw=0.8, ls=':', alpha=0.7)
    ax_decel.text(
        0.3, vval * 1.15,
        label, color=col, fontsize=7.5)

# event markers
for t, h, v, tc, g, lbl in TIMELINE:
    short = lbl.split('\n')[0]
    col   = '#10B981' if g < 1 \
            else ('#EF4444'
                  if g > 2 else '#F59E0B')
    ax_decel.plot(t, v, 'o',
                  color=col, ms=8,
                  zorder=7,
                  markeredgecolor='#0D1117',
                  markeredgewidth=0.8)

# g-force overlay on twin axis
ax_g2 = ax_decel.twinx()
ax_g2.set_facecolor('#0D1117')
ax_g2.plot(t_fine_r, g_fine_r,
           color='#EC4899', lw=1.5,
           ls='--', alpha=0.8,
           zorder=4,
           label='G-force')
ax_g2.set_ylabel('G-force (g)',
                 color='#EC4899',
                 fontsize=9)
ax_g2.tick_params(
    colors='#EC4899', labelsize=8)
ax_g2.spines['right']\
     .set_color('#334155')
ax_g2.spines['top']\
     .set_visible(False)
ax_g2.set_ylim(-0.2, 6)

# peak g annotation
pk_g_idx = np.argmax(g_fine_r)
ax_g2.annotate(
    f'Peak: {g_load.max():.1f}g\n'
    f'(NASA nominal limit)',
    xy=(t_fine_r[pk_g_idx],
        g_fine_r[pk_g_idx]),
    xytext=(t_fine_r[pk_g_idx] + 1.5,
            g_fine_r[pk_g_idx] + 0.8),
    color='#EC4899', fontsize=8,
    linespacing=1.4,
    arrowprops=dict(
        arrowstyle='->',
        color='#EC4899', lw=0.8))

ax_g2.legend(
    facecolor='#1E293B',
    edgecolor='#334155',
    labelcolor='white', fontsize=8,
    loc='upper right')

ax_decel.set_xlim(0, 13.5)
ax_decel.set_ylim(5, 15_000)

# ── RIGHT: parachute sequence ─────────────────────────────────
ax_chute.set_title(
    'Parachute deployment sequence',
    color='white', fontsize=11, pad=10)
ax_chute.set_xlabel(
    'Minutes from entry interface',
    color='#94A3B8', fontsize=9)
ax_chute.set_ylabel(
    'Altitude (km)',
    color='#94A3B8', fontsize=9)

h_fine_c = np.interp(
    t_fine_r, t_min, h_m) / 1000
v_mph_c  = np.interp(
    t_fine_r, t_min, v_ms) * \
    2.237 / 1000  # convert to mph / 1000

# altitude profile — zoom on chute phase
ax_chute.plot(
    t_fine_r, h_fine_c,
    color='#3B82F6', lw=2.5,
    zorder=5)
ax_chute.fill_between(
    t_fine_r, h_fine_c, 0,
    color='#3B82F6', alpha=0.08)

# chute events
chute_events = [
    (8.0,  35.0,   'Forward bay cover\njettisoned',
     '#475569'),
    (9.5,   6.7,  'Drogue chutes deploy\n22,000 ft / 6.7 km',
     '#F59E0B'),
    (10.0,  1.83, '2 drogue chutes\nfully deployed',
     '#F59E0B'),
    (11.0,  1.83, 'Main chutes deploy\n6,000 ft / 1.8 km\n3 × 116 ft diameter',
     '#10B981'),
    (13.0,  0.0,  'Splashdown\n~17 mph / 7.6 m/s',
     '#3B82F6'),
]

for t_ev, h_ev, label, col in \
        chute_events:
    ax_chute.plot(
        t_ev, h_ev, 'o',
        color=col, ms=12, zorder=7,
        markeredgecolor='#0D1117',
        markeredgewidth=1.0)
    y_off = 2.5 if h_ev < 10 else -3
    ha    = 'left' if t_ev < 10 \
            else 'right'
    ax_chute.annotate(
        label,
        xy=(t_ev, h_ev),
        xytext=(t_ev + 0.3,
                h_ev + y_off),
        color=col, fontsize=7.5,
        linespacing=1.4,
        arrowprops=dict(
            arrowstyle='->',
            color=col, lw=0.8,
            alpha=0.7))

# velocity annotations at chute events
for t_ev, h_ev, _, col in \
        chute_events:
    v_at = np.interp(
        t_ev, t_fine_r,
        v_mph_c) * 1000   # back to mph
    if v_at > 20:
        ax_chute.text(
            t_ev, h_ev + 1.0,
            f'{v_at:.0f} mph',
            color=col, fontsize=6.5,
            ha='center',
            fontweight='bold')

# altitude reference lines
for h_ref, label, col in [
    (6.7,  '22,000 ft\n(drogue)',
     '#F59E0B'),
    (1.83, '6,000 ft\n(mains)',
     '#10B981'),
]:
    ax_chute.axhline(
        h_ref, color=col,
        lw=0.8, ls=':', alpha=0.5)

# plasma blackout shade
ax_chute.axvspan(
    2.5, 8.0,
    color='#EF4444', alpha=0.06)
ax_chute.text(
    5.25, 25,
    'Plasma\nblackout',
    color='#EF4444', fontsize=8,
    ha='center', fontweight='bold',
    linespacing=1.3)

# ocean fill
ax_chute.fill_between(
    [0, 13.5], -1, 0,
    color='#1B4FD8', alpha=0.3)
ax_chute.text(
    6.5, -0.6,
    'Pacific Ocean',
    color='#3B82F6', fontsize=8,
    ha='center')

ax_chute.set_xlim(0, 13.5)
ax_chute.set_ylim(-1, 45)

plt.suptitle(
    'Deceleration & Parachute Sequence — '
    'Artemis II Reentry\n'
    '25,000 mph → 17 mph  ·  '
    '3.9g peak  ·  13 minutes',
    color='white', fontsize=11,
    fontweight='bold', y=1.01)

plt.tight_layout()
plt.savefig(
    'artemis_deceleration_chutes.png',
    dpi=120, facecolor='#0D1117',
    bbox_inches='tight')
plt.show()
print("Saved: artemis_deceleration_chutes.png")

# ============================================================
# CELL 5 — Day 9 Summary Dashboard
# Falling Home
# ============================================================
now_utc = datetime.now(timezone.utc)

fig = plt.figure(figsize=(20, 12))
fig.patch.set_facecolor('#0D1117')
ax  = fig.add_axes([0, 0, 1, 1])
ax.set_xlim(0, 20)
ax.set_ylim(0, 12)
ax.axis('off')
ax.set_facecolor('#0D1117')

def card(x, y, w, h,
         fc='#1E293B', ec='#334155',
         lw=0.8):
    ax.add_patch(FancyBboxPatch(
        (x, y), w, h,
        boxstyle='round,pad=0.08',
        facecolor=fc, edgecolor=ec,
        linewidth=lw, zorder=2))

def txt(x, y, s, **kw):
    kw.setdefault('color', 'white')
    kw.setdefault('fontsize', 10)
    kw.setdefault('zorder', 4)
    kw.setdefault('va', 'center')
    ax.text(x, y, s, **kw)

def hln(x0, x1, y,
        col='#1E293B', lw=0.7):
    ax.plot([x0, x1], [y, y],
            color=col, lw=lw,
            zorder=3)

# ── HEADER ────────────────────────────────────────────────────
card(0.25, 10.7, 19.5, 1.1,
     fc='#0F172A', ec='#1E3A5C')
txt(10.0, 11.35,
    'DAY 9 — FALLING HOME: '
    'REENTRY PHYSICS & SKIP TRAJECTORY',
    fontsize=15, fontweight='bold',
    ha='center')
txt(10.0, 10.97,
    f'Code Beyond the Earth  ·  '
    f'April 9, 2026  ·  '
    f'Splashdown tomorrow: '
    f'Apr 10, 8:07 PM EDT  ·  '
    f'{now_utc.strftime("%H:%M UTC")}',
    fontsize=9, ha='center',
    color='#475569')

# ── ROW 1 ─────────────────────────────────────────────────────
metrics = [
    ('Entry velocity',
     '25,000', 'mph  (30× sound)',
     '#EF4444'),
    ('Entry angle',
     f'{ARTEMIS_II_ANGLE}°',
     'steeper than Artemis I',
     '#F59E0B'),
    ('Peak heat',
     '2,760', '°C  Avcoat ablates',
     '#EF4444'),
    ('Peak g-force',
     '3.9', 'g  (nominal)',
     '#EC4899'),
    ('Total time',
     '13', 'minutes EI → splash',
     '#10B981'),
]
cw = 3.6
for i, (label, val, unit, col) in \
        enumerate(metrics):
    bx = 0.25 + i * (cw + 0.25)
    card(bx, 9.25, cw, 1.25,
         fc='#0F172A', ec=col)
    txt(bx + cw/2, 10.15, label,
        fontsize=8.5, color='#64748B',
        ha='center')
    txt(bx + cw/2, 9.78, val,
        fontsize=18, fontweight='bold',
        color=col, ha='center')
    txt(bx + cw/2, 9.42, unit,
        fontsize=8, color='#475569',
        ha='center')

# ── ROW 2 ─────────────────────────────────────────────────────
CW   = 6.2
CGAP = 0.25
CY0  = 5.05
CH   = 4.0
CY1  = CY0 + CH
c1x  = 0.25
c2x  = c1x + CW + CGAP
c3x  = c2x + CW + CGAP

card(c1x, CY0, CW, CH)
card(c2x, CY0, CW, CH)
card(c3x, CY0, CW, CH)

# ── CARD 1: mini skip trajectory ──────────────────────────────
txt(c1x + CW/2, CY1 - 0.3,
    'Skip trajectory — altitude vs range',
    fontsize=9.5, fontweight='bold',
    ha='center')

ax_sk = fig.add_axes([
    (c1x + 0.25) / 20,
    (CY0 + 0.85) / 12,
    (CW - 0.5)   / 20,
    (CH - 1.5)   / 12
])
ax_sk.set_facecolor('#060F1A')
ax_sk.tick_params(
    colors='#475569', labelsize=6)
for sp in ['bottom', 'left']:
    ax_sk.spines[sp]\
         .set_color('#334155')
for sp in ['top', 'right']:
    ax_sk.spines[sp].set_visible(False)
ax_sk.grid(color='#1E293B',
           lw=0.4, zorder=0)

for y0, y1, col, _ in layers:
    ax_sk.axhspan(y0, y1,
                  color=col,
                  alpha=0.9, zorder=1)

ax_sk.plot(x_loft, h_loft,
           color='#10B981', lw=2.0,
           zorder=5, label='AII lofted')
ax_sk.plot(x_ball, h_ball,
           color='#EF4444', lw=1.5,
           ls=':', zorder=4,
           label='Ballistic',
           alpha=0.7)

ax_sk.axhline(0, color='#1B4FD8',
              lw=1.5, zorder=6)
ax_sk.fill_between(
    [0, max(x_ball.max(),
            x_loft.max())],
    -5, 0,
    color='#1B4FD8', alpha=0.2,
    zorder=5)

ax_sk.set_xlabel(
    'Downrange (km)',
    color='#475569', fontsize=6)
ax_sk.set_ylabel(
    'Alt (km)', color='#475569',
    fontsize=6)
ax_sk.legend(
    facecolor='#0D1117',
    edgecolor='#334155',
    labelcolor='white',
    fontsize=6, loc='upper right')
ax_sk.set_ylim(-5, 130)

card(c1x + 0.2, CY0 + 0.18,
     CW - 0.4, 0.55,
     fc='#0F172A', ec='#334155')
txt(c1x + CW/2, CY0 + 0.46,
    'Lofted arc extends path  ·  '
    'reduces peak g  ·  '
    'controls heating rate',
    fontsize=8, color='#64748B',
    ha='center')

# ── CARD 2: Artemis I vs II fix ───────────────────────────────
txt(c2x + CW/2, CY1 - 0.3,
    'The Artemis I fix explained',
    fontsize=9.5, fontweight='bold',
    ha='center')

fix_rows = [
    ('Entry angle',
     f'{ARTEMIS_I_ANGLE}° (shallow)',
     f'{ARTEMIS_II_ANGLE}° (steeper)',
     '#F59E0B'),
    ('Peak heat flux',
     'Lower',
     'Higher peak',
     '#EF4444'),
    ('Heating duration',
     'Longer',
     'Shorter ✓',
     '#10B981'),
    ('Total heat load',
     'Higher',
     'Lower ✓',
     '#10B981'),
    ('Avcoat ablation',
     'Chunks peeled off',
     'Controlled char ✓',
     '#10B981'),
    ('Peak g-force',
     '~4.5g',
     '3.9g ✓',
     '#10B981'),
    ('Fix type',
     'N/A',
     'Trajectory only\nno hardware change',
     '#3B82F6'),
]

# headers
txt(c2x + 0.25, CY1 - 0.72,
    'Parameter',
    fontsize=7.5, color='#64748B',
    ha='left', fontweight='bold')
txt(c2x + 2.70, CY1 - 0.72,
    'Artemis I',
    fontsize=7.5, color='#F59E0B',
    ha='center', fontweight='bold')
txt(c2x + 4.50, CY1 - 0.72,
    'Artemis II',
    fontsize=7.5, color='#10B981',
    ha='center', fontweight='bold')
hln(c2x + 0.2, c2x + CW - 0.2,
    CY1 - 0.85, col='#334155')

for j, (param, a1v, a2v, col) in \
        enumerate(fix_rows):
    ry = CY1 - 1.08 - j * 0.47
    txt(c2x + 0.25, ry, param,
        fontsize=7.5, color='#64748B',
        ha='left')
    txt(c2x + 2.70, ry, a1v,
        fontsize=7.5, color='#F59E0B',
        ha='center')
    txt(c2x + 4.50, ry, a2v,
        fontsize=7.5, color=col,
        ha='center')
    if j < len(fix_rows) - 1:
        hln(c2x + 0.2,
            c2x + CW - 0.2,
            ry - 0.28,
            col='#1E293B')

card(c2x + 0.2, CY0 + 0.18,
     CW - 0.4, 0.75,
     fc='#0F172A', ec='#334155')
txt(c2x + CW/2, CY0 + 0.56,
    '"We didn\'t change the hardware.\n'
    ' We changed the angle."',
    fontsize=8.5, ha='center',
    color='#64748B', linespacing=1.5,
    style='italic')

# ── CARD 3: parachute sequence ────────────────────────────────
txt(c3x + CW/2, CY1 - 0.3,
    'Parachute deployment sequence',
    fontsize=9.5, fontweight='bold',
    ha='center')

chute_seq = [
    ('7:33 PM',
     'Service module separates',
     '#475569'),
    ('7:37 PM',
     'Final trajectory burn',
     '#F59E0B'),
    ('7:53 PM',
     'Entry interface  ·  120 km',
     '#EF4444'),
    ('7:53 PM',
     'Plasma blackout begins',
     '#EF4444'),
    ('7:56 PM',
     'Peak heat 2,760°C  ·  3.9g',
     '#EF4444'),
    ('8:01 PM',
     'Plasma clears  ·  comms restored',
     '#10B981'),
    ('8:01 PM',
     'Forward bay cover jettisoned',
     '#F59E0B'),
    ('8:03 PM',
     'Drogue chutes  ·  22,000 ft',
     '#10B981'),
    ('8:04 PM',
     'Main chutes  ·  6,000 ft',
     '#10B981'),
    ('8:07 PM',
     'Splashdown  ·  Pacific Ocean ✓',
     '#3B82F6'),
]

for j, (time_s, label, col) in \
        enumerate(chute_seq):
    ry = CY1 - 0.78 - j * 0.37

    ax.plot(c3x + 0.35, ry, 'o',
            color=col, ms=7,
            zorder=5,
            markeredgecolor='#0D1117',
            markeredgewidth=0.8)

    if j < len(chute_seq) - 1:
        ax.plot(
            [c3x + 0.35,
             c3x + 0.35],
            [ry - 0.05,
             ry - 0.32],
            color='#334155',
            lw=0.8, zorder=3)

    txt(c3x + 0.52, ry + 0.03,
        time_s,
        fontsize=7.5, color=col,
        fontweight='bold', ha='left')
    txt(c3x + 0.52, ry - 0.11,
        label,
        fontsize=7, color='#475569',
        ha='left')

# ── ROW 3: reentry strip ──────────────────────────────────────
card(0.25, 0.85, 19.5, 4.0)
txt(10.0, 4.62,
    'Reentry sequence — velocity and altitude',
    fontsize=10, fontweight='bold',
    ha='center')

ax_strip = fig.add_axes([
    0.04, 0.09, 0.92, 0.255
])
ax_strip.set_facecolor('#0D1117')
ax_strip.tick_params(
    colors='#475569', labelsize=7.5)
for sp in ['bottom', 'left']:
    ax_strip.spines[sp]\
            .set_color('#334155')
for sp in ['top', 'right']:
    ax_strip.spines[sp]\
            .set_visible(False)
ax_strip.grid(color='#1E293B',
              lw=0.5, zorder=0)

t_s_fine = np.linspace(0, 13, 500)
v_s_fine = np.interp(
    t_s_fine, t_min, v_ms)
h_s_fine = np.interp(
    t_s_fine, t_min, h_m) / 1000

ax_strip.plot(t_s_fine, v_s_fine,
              color='#EF4444',
              lw=2.5, zorder=5,
              label='Velocity (m/s)')
ax_strip.set_ylabel(
    'Velocity (m/s)',
    color='#EF4444', fontsize=8)
ax_strip.tick_params(
    axis='y', colors='#EF4444')

ax_s2 = ax_strip.twinx()
ax_s2.set_facecolor('#0D1117')
ax_s2.plot(t_s_fine, h_s_fine,
           color='#3B82F6',
           lw=2.0, ls='--',
           zorder=4,
           label='Altitude (km)')
ax_s2.set_ylabel(
    'Altitude (km)',
    color='#3B82F6', fontsize=8)
ax_s2.tick_params(
    axis='y', colors='#3B82F6')
ax_s2.spines['right']\
     .set_color('#334155')
ax_s2.spines['top']\
     .set_visible(False)

# event dots on strip
for t, h, v, tc, g, lbl in TIMELINE:
    col = '#10B981' if g < 1 \
          else ('#EF4444'
                if g > 2
                else '#F59E0B')
    ax_strip.plot(t, v, 'o',
                  color=col, ms=7,
                  zorder=6,
                  markeredgecolor='#0D1117',
                  markeredgewidth=0.8)

# plasma blackout
ax_strip.axvspan(
    2.5, 8.0,
    color='#EF4444', alpha=0.07)
ax_strip.text(
    5.25, v_s_fine.max() * 0.5,
    'PLASMA BLACKOUT',
    color='#EF4444', fontsize=8,
    ha='center', fontweight='bold')

lines1, labs1 = \
    ax_strip.get_legend_handles_labels()
lines2, labs2 = \
    ax_s2.get_legend_handles_labels()
ax_strip.legend(
    lines1 + lines2,
    labs1 + labs2,
    facecolor='#1E293B',
    edgecolor='#334155',
    labelcolor='white',
    fontsize=7.5, loc='upper right')

ax_strip.set_xlim(0, 13.5)
ax_strip.set_xlabel(
    'Minutes from entry interface (EI)',
    color='#475569', fontsize=8)

# ── FOOTER ────────────────────────────────────────────────────
card(0.25, 0.12, 19.5, 0.62,
     fc='#0F172A', ec='#1E293B')
txt(10.0, 0.44,
    f'Code Beyond the Earth  ·  '
    f'codebeyondtheearth.substack.com  ·  '
    f'Generated '
    f'{now_utc.strftime("%B %d, %Y  %H:%M UTC")}'
    f'  ·  Sources: NASA Flight Director '
    f'Rick Henfling briefing Apr 8, 2026  ·  '
    f'Sutton-Graves heating model  ·  '
    f'Orion mission data',
    fontsize=8, ha='center',
    color='#475569')

plt.savefig(
    'artemis_day9_summary.png',
    dpi=150, facecolor='#0D1117',
    bbox_inches='tight')
plt.show()

print("=" * 60)
print("   DAY 9 COMPLETE — FALLING HOME")
print("=" * 60)
print()
print("  Saved files:")
print("    artemis_thermal_model.png")
print("    artemis_skip_trajectory.png")
print("    artemis_deceleration_chutes.png")
print("    artemis_day9_summary.png")
print()
print("  Key physics:")
print(f"    Entry velocity  : "
      f"{V_ENTRY_MPH:,} mph")
print(f"    Entry angle fix : "
      f"{ARTEMIS_I_ANGLE}° → "
      f"{ARTEMIS_II_ANGLE}°")
print(f"    Peak heat       : "
      f"2,760°C")
print(f"    Peak g-force    : "
      f"{g_load.max():.1f}g")
print(f"    Ballistic coeff : "
      f"{ORION_BETA:.1f} kg/m²")
print(f"    Heat shield     : "
      f"Avcoat  ·  same as Apollo")
print()
print("  Splashdown: Apr 10, 8:07 PM EDT")
print("  Recovery  : USS John P. Murtha")
print("=" * 60)