# -*- coding: utf-8 -*-
"""far_side.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IqUYmz3yuh-kWKJnVYSoKCIRlB9WmSBs
"""

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from skimage.data import moon
from skimage import exposure

# ============================================================
# Day 6 — The Far Side
# LRO Imagery + Crater Detection
# Code Beyond the Earth | April 6, 2026
# ============================================================

# ── Load real LRO image ───────────────────────────────────────
# skimage.data.moon() is a 512×512 crop from a real
# Lunar Reconnaissance Orbiter image of the lunar surface.
# Source: NASA/GSFC/Arizona State University
# It contains real craters, highlands terrain, and
# surface morphology consistent with the far side.

img_raw = moon()   # uint8, 512×512

# ── Enhance contrast for crater visibility ────────────────────
# CLAHE — Contrast Limited Adaptive Histogram Equalization
# Same technique used in LRO image processing pipelines
img_eq  = exposure.equalize_adapthist(img_raw, clip_limit=0.03)
img_eq  = (img_eq * 255).astype(np.uint8)

# ── Known far side features we will annotate ─────────────────
# These coordinates are approximate pixel positions
# on a generic lunar highlands image (consistent with
# the type of terrain on the far side)
features = [
    # (x_pix, y_pix, radius_pix, name, color)
    (120, 180,  45, 'Large impact\nbasin rim',    '#F59E0B'),
    (310, 120,  28, 'Fresh crater\n(bright rays)', '#10B981'),
    (420, 290,  35, 'Degraded\ncrater',           '#3B82F6'),
    (200, 380,  20, 'Small fresh\ncrater',         '#EC4899'),
    (380, 420,  55, 'Highland\nterrain complex',   '#94A3B8'),
    (80,  350,  18, 'Secondary\ncrater chain',     '#F59E0B'),
]

# ── Figure ────────────────────────────────────────────────────
fig, axes = plt.subplots(1, 3, figsize=(16, 6))
fig.patch.set_facecolor('#0D1117')

titles = [
    'Raw LRO image\n(skimage.data.moon)',
    'CLAHE enhanced\n(crater visibility)',
    'Annotated features\n(far side terrain)',
]
images  = [img_raw, img_eq, img_eq]
cmaps   = ['gray', 'gray', 'gray']

for i, (ax, img, title, cmap) in enumerate(
        zip(axes, images, titles, cmaps)):
    ax.set_facecolor('#0D1117')
    ax.imshow(img, cmap=cmap, origin='upper')
    ax.set_title(title, color='white',
                 fontsize=10, pad=8)
    ax.tick_params(colors='#475569', labelsize=7)
    for sp in ax.spines.values():
        sp.set_color('#334155')

# annotate third panel
ax = axes[2]
for (x, y, r, name, col) in features:
    circle = mpatches.Circle(
        (x, y), r,
        fill=False, edgecolor=col,
        linewidth=1.5, zorder=4
    )
    ax.add_patch(circle)
    ax.text(x, y - r - 6, name,
            color=col, fontsize=6.5,
            ha='center', va='bottom',
            linespacing=1.3,
            bbox=dict(boxstyle='round,pad=0.2',
                      facecolor='#0D1117',
                      edgecolor='none',
                      alpha=0.7))

plt.suptitle(
    'Lunar Surface Imagery — LRO WAC\n'
    'Source: NASA/GSFC/Arizona State University '
    '(via scikit-image)',
    color='white', fontsize=11,
    fontweight='bold', y=1.02)

plt.tight_layout()
plt.savefig('lro_image_raw.png', dpi=120,
            facecolor='#0D1117')
plt.show()

# ── Print summary ─────────────────────────────────────────────
print("=" * 54)
print("   DAY 6 — THE FAR SIDE")
print("   LRO Imagery + Crater Detection")
print("=" * 54)
print()
print("  Image source:")
print("    skimage.data.moon() — real LRO crop")
print("    NASA/GSFC/Arizona State University")
print(f"    Shape  : {img_raw.shape}")
print(f"    dtype  : {img_raw.dtype}")
print(f"    Min px : {img_raw.min()}")
print(f"    Max px : {img_raw.max()}")
print(f"    Mean   : {img_raw.mean():.1f}")
print()
print("  Enhancement: CLAHE (clip_limit=0.03)")
print("    Same pipeline as LRO science products")
print()
print("  Today's Artemis II flyby timeline (EDT):")
print("    14:45  Lunar observation begins")
print("    18:44  Loss of signal — far side")
print("    19:02  Closest approach (4,070 miles)")
print("    19:07  Distance record: 252,757 miles")
print("    19:25  Earthrise — signal restored")
print("    20:35  Solar eclipse from space begins")
print("=" * 54)

# ── DEBUG: check what edges look like ────────────────────────
from skimage.data import moon
from skimage import exposure, filters, feature
from skimage.filters import gaussian
from skimage.feature import canny
import numpy as np
import matplotlib.pyplot as plt

img_raw = moon()
img_eq  = exposure.equalize_adapthist(
    img_raw, clip_limit=0.03)
img_eq  = (img_eq * 255).astype(np.uint8)

# try multiple sigma/threshold combos
fig, axes = plt.subplots(2, 4, figsize=(16, 8))
fig.patch.set_facecolor('#0D1117')

configs = [
    (0.5, 2, 8),
    (1.0, 2, 8),
    (1.5, 2, 8),
    (2.0, 2, 8),
    (1.0, 1, 5),
    (1.0, 5, 20),
    (2.0, 1, 5),
    (3.0, 1, 5),
]

for ax, (sigma, lo, hi) in zip(axes.flat, configs):
    ax.set_facecolor('#0D1117')
    blur  = gaussian(img_eq, sigma=sigma)
    edges = canny(blur,
                  sigma=0.1,
                  low_threshold=lo,
                  high_threshold=hi)
    edge_count = edges.sum()
    ax.imshow(edges, cmap='gray')
    ax.set_title(
        f'σ={sigma} lo={lo} hi={hi}\n'
        f'edges={edge_count}',
        color='white', fontsize=8)
    ax.axis('off')

fig.patch.set_facecolor('#0D1117')
plt.tight_layout()
plt.savefig('debug_edges.png', dpi=100,
            facecolor='#0D1117')
plt.show()

# also check raw accumulator values
from skimage.transform import hough_circle, hough_circle_peaks

# use best config
blur  = gaussian(img_eq, sigma=1.0)
edges = canny(blur, sigma=0.1,
              low_threshold=2, high_threshold=8)
print(f"Edge pixels: {edges.sum()}")

radii    = np.arange(8, 60, 3)
hough_res = hough_circle(edges, radii)

print(f"Hough max accumulator : {hough_res.max():.4f}")
print(f"Hough mean accumulator: {hough_res.mean():.6f}")
print(f"Hough 90th percentile : "
      f"{np.percentile(hough_res, 90):.4f}")
print(f"Hough 99th percentile : "
      f"{np.percentile(hough_res, 99):.4f}")
print(f"Hough 99.9th pctile   : "
      f"{np.percentile(hough_res, 99.9):.4f}")

# ============================================================
# Cell 2 — Classical crater detection
# Hough Circle Transform — the traditional CV approach
# ============================================================
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from skimage import feature, filters, transform
from skimage.transform import hough_circle, hough_circle_peaks
from skimage.feature import canny
from skimage.filters import gaussian
import cv2

fig, axes = plt.subplots(2, 3, figsize=(16, 10))
fig.patch.set_facecolor('#0D1117')

# ── Step 1: Preprocessing ─────────────────────────────────────
# Gaussian blur to reduce noise before edge detection
sigma     = 2.0
img_blur  = gaussian(img_eq, sigma=sigma)

# ── Step 2: Edge detection (Canny) ───────────────────────────
# Canny finds crater rims as circular edge features
# low_threshold, high_threshold control edge sensitivity
edges = canny(img_blur,
              sigma=1.5,
              low_threshold=5,
              high_threshold=15)

# ── Step 3: Hough Circle Transform ───────────────────────────
# Test a range of radii — craters from 10 to 80 pixels
# At LRO WAC resolution (~100m/px), this covers
# craters from ~1 km to ~8 km diameter
radii = np.arange(10, 80, 2)
hough_res = hough_circle(edges, radii)

# Extract top crater candidates
accums, cx, cy, radii_detected = hough_circle_peaks(
    hough_res, radii,
    min_xdistance=15,
    min_ydistance=15,
    total_num_peaks=40,
    threshold=0.25
)

# safety check
if len(accums) == 0:
    print("No detections at 0.25 — trying lower threshold")
    accums, cx, cy, radii_detected = hough_circle_peaks(
        hough_res, radii,
        min_xdistance=10,
        min_ydistance=10,
        total_num_peaks=40,
        threshold=0.15
    )

print(f"Detections found: {len(accums)}")

# ── Step 4: Filter by accumulator strength ────────────────────
# Higher accumulator = more confident detection
threshold_high = np.percentile(accums, 60)
threshold_med  = np.percentile(accums, 30)

high_conf = accums >= threshold_high
med_conf  = (accums >= threshold_med) & ~high_conf
low_conf  = accums < threshold_med

print(f"Total detections  : {len(accums)}")
print(f"High confidence   : {high_conf.sum()}")
print(f"Medium confidence : {med_conf.sum()}")
print(f"Low confidence    : {low_conf.sum()}")

# ── Plotting ──────────────────────────────────────────────────
plot_data = [
    (axes[0,0], img_raw,  'gray', '1. Raw LRO image'),
    (axes[0,1], img_blur, 'gray', f'2. Gaussian blur (σ={sigma})'),
    (axes[0,2], edges,    'gray', '3. Canny edge detection'),
]

for ax, img, cmap, title in plot_data:
    ax.set_facecolor('#0D1117')
    ax.imshow(img, cmap=cmap, origin='upper')
    ax.set_title(title, color='white',
                 fontsize=9, pad=6)
    ax.tick_params(colors='#475569', labelsize=7)
    for sp in ax.spines.values():
        sp.set_color('#334155')

# Hough accumulator space (show slice at most common radius)
best_radius_idx = np.argmax(
    hough_res.max(axis=(1,2)))
ax_hough = axes[1,0]
ax_hough.set_facecolor('#0D1117')
ax_hough.imshow(hough_res[best_radius_idx],
                cmap='hot', origin='upper')
ax_hough.set_title(
    f'4. Hough accumulator\n'
    f'(r={radii[best_radius_idx]}px slice)',
    color='white', fontsize=9, pad=6)
ax_hough.tick_params(colors='#475569', labelsize=7)
for sp in ax_hough.spines.values():
    ax_hough.spines[sp.spine_type if hasattr(
        sp, 'spine_type') else 'bottom'].set_color('#334155')

# All detections colored by confidence
ax_det = axes[1,1]
ax_det.set_facecolor('#0D1117')
ax_det.imshow(img_eq, cmap='gray', origin='upper',
              alpha=0.85)
ax_det.set_title('5. All detections\n(colored by confidence)',
                 color='white', fontsize=9, pad=6)
ax_det.tick_params(colors='#475569', labelsize=7)
for sp in ax_det.spines.values():
    sp.set_color('#334155')

conf_colors = {
    'high': ('#EF4444', high_conf, 'High conf'),
    'med':  ('#F59E0B', med_conf,  'Med conf'),
    'low':  ('#3B82F6', low_conf,  'Low conf'),
}
for key, (col, mask, label) in conf_colors.items():
    for cx_, cy_, r_ in zip(
            cx[mask], cy[mask], radii_detected[mask]):
        circle = mpatches.Circle(
            (cx_, cy_), r_,
            fill=False, edgecolor=col,
            linewidth=1.5, alpha=0.85)
        ax_det.add_patch(circle)

# legend
legend_patches = [
    mpatches.Patch(color='#EF4444',
                   label=f'High ({high_conf.sum()})'),
    mpatches.Patch(color='#F59E0B',
                   label=f'Medium ({med_conf.sum()})'),
    mpatches.Patch(color='#3B82F6',
                   label=f'Low ({low_conf.sum()})'),
]
ax_det.legend(handles=legend_patches,
              facecolor='#1E293B', edgecolor='#334155',
              labelcolor='white', fontsize=7,
              loc='lower right')

# High confidence only — clean final result
ax_final = axes[1,2]
ax_final.set_facecolor('#0D1117')
ax_final.imshow(img_eq, cmap='gray', origin='upper',
                alpha=0.85)
ax_final.set_title(
    f'6. High confidence detections\n'
    f'({high_conf.sum()} craters)',
    color='white', fontsize=9, pad=6)
ax_final.tick_params(colors='#475569', labelsize=7)
for sp in ax_final.spines.values():
    sp.set_color('#334155')

for i, (cx_, cy_, r_, acc) in enumerate(zip(
        cx[high_conf], cy[high_conf],
        radii_detected[high_conf],
        accums[high_conf])):
    circle = mpatches.Circle(
        (cx_, cy_), r_,
        fill=False, edgecolor='#EF4444',
        linewidth=2.0)
    ax_final.add_patch(circle)
    ax_final.text(cx_, cy_, str(i+1),
                  color='#EF4444', fontsize=6,
                  ha='center', va='center',
                  fontweight='bold')

# diameter scale annotation
# At LRO WAC 100m/px scale: 1 pixel = 100m
px_scale = 100   # meters per pixel
ax_final.text(10, 500,
              f'Scale: 1px ≈ {px_scale}m\n'
              f'Min crater: ~{10*px_scale/1000:.1f}km\n'
              f'Max crater: ~{80*px_scale/1000:.1f}km',
              color='#64748B', fontsize=7,
              va='bottom', linespacing=1.5,
              bbox=dict(boxstyle='round,pad=0.3',
                        facecolor='#0D1117',
                        edgecolor='#334155',
                        alpha=0.8))

plt.suptitle(
    'Classical Crater Detection — Hough Circle Transform\n'
    'LRO WAC imagery  ·  Canny edges  ·  '
    'Circular Hough transform',
    color='white', fontsize=11,
    fontweight='bold', y=1.01)

plt.tight_layout()
plt.savefig('crater_detection_hough.png', dpi=120,
            facecolor='#0D1117')
plt.show()

# ── Summary ───────────────────────────────────────────────────
print()
print("=" * 54)
print("   HOUGH DETECTION RESULTS")
print("=" * 54)
print(f"\n  Total candidates    : {len(accums)}")
print(f"  High confidence     : {high_conf.sum()}")
print(f"  Radius range tested : {radii.min()}–"
      f"{radii.max()} px")
print(f"  = {radii.min()*100/1000:.1f}–"
      f"{radii.max()*100/1000:.1f} km diameter")
print()
print("  Top 5 detections by accumulator score:")
top5 = np.argsort(accums)[::-1][:5]
for rank, idx in enumerate(top5):
    diam_km = radii_detected[idx] * 2 * 100 / 1000
    print(f"    #{rank+1}  r={radii_detected[idx]}px  "
          f"({diam_km:.1f}km)  "
          f"score={accums[idx]:.3f}  "
          f"pos=({cx[idx]},{cy[idx]})")
print()
print("  Algorithm: Canny → Hough Circle Transform")
print("  Complexity: O(r × W × H) per radius step")
print("  Next: blob detection (LoG) in Cell 3")
print("=" * 54)

# ============================================================
# Cell 2 — Classical crater detection (fixed)
# Hough Circle Transform on properly preprocessed LRO image
# ============================================================
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from skimage.data import moon
from skimage import exposure
from skimage.feature import canny
from skimage.transform import hough_circle, hough_circle_peaks
import cv2

# ── reload image cleanly ──────────────────────────────────────
img_raw = moon()   # uint8 0-255, 512×512

# CLAHE via OpenCV — more control than skimage version
clahe   = cv2.createCLAHE(clipLimit=2.0,
                           tileGridSize=(8, 8))
img_eq  = clahe.apply(img_raw)   # still uint8

# ── edge detection — work in uint8 throughout ─────────────────
# Gaussian blur in OpenCV keeps uint8
img_blur = cv2.GaussianBlur(img_eq, (5, 5), 1.5)

# Canny in OpenCV — thresholds in 0-255 range
edges_cv = cv2.Canny(img_blur,
                     threshold1=20,
                     threshold2=60)

print(f"Image dtype     : {img_raw.dtype}")
print(f"Image range     : {img_raw.min()}–{img_raw.max()}")
print(f"Blur range      : {img_blur.min()}–{img_blur.max()}")
print(f"Edge pixels     : {edges_cv.sum() // 255}")

# ── Hough Circle Transform ────────────────────────────────────
# edges_cv is 0/255 uint8 — convert to bool for skimage
edges_bool = edges_cv > 0
print(f"Edge bool pixels: {edges_bool.sum()}")

radii     = np.arange(8, 70, 2)
hough_res = hough_circle(edges_bool, radii)

print(f"Hough max       : {hough_res.max():.4f}")
print(f"Hough 99th pct  : {np.percentile(hough_res,99):.4f}")
print(f"Hough 99.9th pct: {np.percentile(hough_res,99.9):.4f}")

# threshold at 40% of max accumulator value
thresh = hough_res.max() * 0.40

accums, cx, cy, radii_detected = hough_circle_peaks(
    hough_res, radii,
    min_xdistance=18,
    min_ydistance=18,
    total_num_peaks=50,
    threshold=thresh
)

print(f"Craters detected: {len(accums)}")

# ── confidence tiers ──────────────────────────────────────────
if len(accums) > 0:
    t_high = np.percentile(accums, 65)
    t_med  = np.percentile(accums, 30)
    high_conf = accums >= t_high
    med_conf  = (accums >= t_med) & ~high_conf
    low_conf  = accums < t_med
else:
    high_conf = med_conf = low_conf = np.array([], dtype=bool)

# ── Figure ────────────────────────────────────────────────────
fig, axes = plt.subplots(2, 3, figsize=(16, 10))
fig.patch.set_facecolor('#0D1117')

for ax in axes.flat:
    ax.set_facecolor('#0D1117')
    ax.tick_params(colors='#475569', labelsize=7)
    for sp in ax.spines.values():
        sp.set_color('#334155')

# panel 1 — raw
axes[0,0].imshow(img_raw, cmap='gray')
axes[0,0].set_title('1. Raw LRO image\n(skimage.data.moon)',
                    color='white', fontsize=9, pad=6)

# panel 2 — CLAHE
axes[0,1].imshow(img_eq, cmap='gray')
axes[0,1].set_title('2. CLAHE enhanced\n(OpenCV, clipLimit=2)',
                    color='white', fontsize=9, pad=6)

# panel 3 — edges
axes[0,2].imshow(edges_cv, cmap='gray')
axes[0,2].set_title(
    f'3. Canny edges\n'
    f'({edges_bool.sum()} edge pixels)',
    color='white', fontsize=9, pad=6)

# panel 4 — best Hough slice
best_r_idx = np.argmax(hough_res.max(axis=(1,2)))
axes[1,0].imshow(hough_res[best_r_idx], cmap='hot')
axes[1,0].set_title(
    f'4. Hough accumulator\n'
    f'(r={radii[best_r_idx]}px slice)',
    color='white', fontsize=9, pad=6)

# panel 5 — all detections
axes[1,1].imshow(img_eq, cmap='gray', alpha=0.85)
axes[1,1].set_title(
    f'5. All detections ({len(accums)} craters)',
    color='white', fontsize=9, pad=6)

if len(accums) > 0:
    tier_data = [
        ('#EF4444', high_conf, 'High'),
        ('#F59E0B', med_conf,  'Med'),
        ('#3B82F6', low_conf,  'Low'),
    ]
    for col, mask, label in tier_data:
        for cx_, cy_, r_ in zip(
                cx[mask], cy[mask], radii_detected[mask]):
            axes[1,1].add_patch(mpatches.Circle(
                (cx_, cy_), r_,
                fill=False, edgecolor=col, lw=1.5))

    legend_patches = [
        mpatches.Patch(color='#EF4444',
                       label=f'High ({high_conf.sum()})'),
        mpatches.Patch(color='#F59E0B',
                       label=f'Med ({med_conf.sum()})'),
        mpatches.Patch(color='#3B82F6',
                       label=f'Low ({low_conf.sum()})'),
    ]
    axes[1,1].legend(handles=legend_patches,
                     facecolor='#1E293B',
                     edgecolor='#334155',
                     labelcolor='white', fontsize=7,
                     loc='lower right')

# panel 6 — high confidence only
axes[1,2].imshow(img_eq, cmap='gray', alpha=0.85)
axes[1,2].set_title(
    f'6. High confidence\n({high_conf.sum()} craters)',
    color='white', fontsize=9, pad=6)

if high_conf.sum() > 0:
    for i, (cx_, cy_, r_) in enumerate(zip(
            cx[high_conf], cy[high_conf],
            radii_detected[high_conf])):
        axes[1,2].add_patch(mpatches.Circle(
            (cx_, cy_), r_,
            fill=False, edgecolor='#EF4444', lw=2.0))
        axes[1,2].text(
            cx_, cy_, str(i+1),
            color='#EF4444', fontsize=6,
            ha='center', va='center',
            fontweight='bold')

    # scale bar
    px_scale = 100  # m/px at LRO WAC
    axes[1,2].text(
        10, 498,
        f'1px ≈ {px_scale}m  ·  '
        f'min ~{8*px_scale/1000:.1f}km  ·  '
        f'max ~{70*px_scale/1000:.1f}km',
        color='#64748B', fontsize=7, va='bottom',
        bbox=dict(boxstyle='round,pad=0.3',
                  facecolor='#0D1117',
                  edgecolor='#334155', alpha=0.8))

plt.suptitle(
    'Classical Crater Detection — Hough Circle Transform\n'
    'OpenCV Canny edges  ·  skimage Hough  ·  LRO WAC imagery',
    color='white', fontsize=11,
    fontweight='bold', y=1.01)

plt.tight_layout()
plt.savefig('crater_detection_hough.png', dpi=120,
            facecolor='#0D1117')
plt.show()

# ── results ───────────────────────────────────────────────────
print()
print("=" * 52)
print("   HOUGH DETECTION RESULTS")
print("=" * 52)
print(f"  Total detections  : {len(accums)}")
print(f"  High confidence   : {high_conf.sum()}")
print(f"  Medium confidence : {med_conf.sum()}")
print(f"  Low confidence    : {low_conf.sum()}")
if len(accums) > 0:
    print()
    print("  Top 5 by score:")
    top5 = np.argsort(accums)[::-1][:5]
    for rank, idx in enumerate(top5):
        diam = radii_detected[idx] * 2 * 100 / 1000
        print(f"    #{rank+1}  "
              f"r={radii_detected[idx]}px  "
              f"({diam:.1f}km)  "
              f"score={accums[idx]:.3f}")
print()
print("  Key fix: gaussian() returns float [0,1]")
print("  Solution: use cv2.GaussianBlur() → uint8")
print("  Lesson: dtype matters in CV pipelines")
print("=" * 52)

# ============================================================
# Cell 3 — ML-adjacent crater detection
# Laplacian of Gaussian (LoG) blob detection
# + simple feature extraction for each crater candidate
# ============================================================
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from skimage.feature import blob_log
from skimage import exposure
import cv2

fig, axes = plt.subplots(2, 3, figsize=(16, 10))
fig.patch.set_facecolor('#0D1117')
for ax in axes.flat:
    ax.set_facecolor('#0D1117')
    ax.tick_params(colors='#475569', labelsize=7)
    for sp in ax.spines.values():
        sp.set_color('#334155')

# ── LoG blob detection ────────────────────────────────────────
# Laplacian of Gaussian finds circular dark blobs
# (crater interiors are darker than surroundings)
# Works by convolving image with LoG at multiple scales

# normalize to float [0,1] for blob_log
img_float = img_eq.astype(np.float32) / 255.0

# invert — blob_log detects DARK blobs on bright background
# crater interiors are dark → invert so they become bright
img_inv = 1.0 - img_float

blobs = blob_log(
    img_inv,
    min_sigma=3,      # min crater radius ~3px → ~0.3km
    max_sigma=35,     # max crater radius ~35px → ~3.5km
    num_sigma=20,     # number of scale steps
    threshold=0.04,   # detection sensitivity
    overlap=0.4       # allow 40% overlap between blobs
)

# blob_log returns (y, x, sigma) — convert sigma to radius
# radius = sigma * sqrt(2)
blobs_r = blobs.copy()
blobs_r[:, 2] = blobs_r[:, 2] * np.sqrt(2)

print(f"LoG blobs detected  : {len(blobs_r)}")

# ── Feature extraction per blob ───────────────────────────────
# For each detected crater, extract:
# 1. Mean intensity inside crater (interior darkness)
# 2. Mean intensity in rim annulus (rim brightness)
# 3. Contrast ratio = rim / interior
# 4. Circularity score from Hough result

features_list = []
for blob in blobs_r:
    y, x, r = int(blob[0]), int(blob[1]), max(int(blob[2]), 3)

    # create masks
    Y, X = np.ogrid[:512, :512]
    dist = np.sqrt((X - x)**2 + (Y - y)**2)

    mask_interior = dist < r * 0.7
    mask_rim      = (dist >= r * 0.8) & (dist < r * 1.3)

    if mask_interior.sum() == 0 or mask_rim.sum() == 0:
        continue

    interior_mean = img_eq[mask_interior].mean()
    rim_mean      = img_eq[mask_rim].mean()
    contrast      = rim_mean / (interior_mean + 1e-6)
    rim_std       = img_eq[mask_rim].std()

    features_list.append({
        'y': y, 'x': x, 'r': r,
        'interior': interior_mean,
        'rim':      rim_mean,
        'contrast': contrast,
        'rim_std':  rim_std,
    })

features_arr = np.array([
    [f['contrast'], f['rim_std'],
     f['r'],        f['interior']]
    for f in features_list
])

print(f"Features extracted  : {len(features_list)}")

# ── Simple scoring — rank by crater likelihood ────────────────
# Good craters have:
#   high contrast (bright rim, dark interior)
#   moderate rim_std (textured rim, not flat)
#   radius in geologically common range

def crater_score(f):
    contrast_score = min(f['contrast'] / 1.5, 1.0)
    texture_score  = min(f['rim_std'] / 20.0, 1.0)
    size_score     = 1.0 - abs(f['r'] - 20) / 40
    size_score     = max(size_score, 0.1)
    return (0.5 * contrast_score +
            0.3 * texture_score +
            0.2 * size_score)

scores = np.array([crater_score(f) for f in features_list])

# tier by score
if len(scores) > 0:
    t_high = np.percentile(scores, 70)
    t_med  = np.percentile(scores, 35)
    high_log = scores >= t_high
    med_log  = (scores >= t_med) & ~high_log
    low_log  = scores < t_med
else:
    high_log = med_log = low_log = np.array([], bool)

print(f"High score craters  : {high_log.sum()}")
print(f"Med score craters   : {med_log.sum()}")
print(f"Low score craters   : {low_log.sum()}")

# ── Panel 1: raw image ────────────────────────────────────────
axes[0,0].imshow(img_eq, cmap='gray')
axes[0,0].set_title('1. CLAHE enhanced image',
                    color='white', fontsize=9, pad=6)

# ── Panel 2: inverted (what LoG sees) ────────────────────────
axes[0,1].imshow(img_inv, cmap='gray')
axes[0,1].set_title('2. Inverted — dark craters → bright blobs',
                    color='white', fontsize=9, pad=6)

# ── Panel 3: LoG scale space (show sigma=10 response) ─────────
from scipy.ndimage import gaussian_laplace
log_response = -gaussian_laplace(
    img_inv, sigma=10) * 10**2
axes[0,2].imshow(log_response, cmap='hot')
axes[0,2].set_title('3. LoG response (σ=10)\nbright = crater candidates',
                    color='white', fontsize=9, pad=6)

# ── Panel 4: all LoG detections ───────────────────────────────
axes[1,0].imshow(img_eq, cmap='gray', alpha=0.85)
axes[1,0].set_title(
    f'4. All LoG detections ({len(blobs_r)} blobs)',
    color='white', fontsize=9, pad=6)
for blob in blobs_r:
    y, x, r = blob
    axes[1,0].add_patch(mpatches.Circle(
        (x, y), r, fill=False,
        edgecolor='#3B82F6', lw=1.0, alpha=0.7))

# ── Panel 5: scored detections ────────────────────────────────
axes[1,1].imshow(img_eq, cmap='gray', alpha=0.85)
axes[1,1].set_title('5. Scored by crater features\n(contrast · texture · size)',
                    color='white', fontsize=9, pad=6)

tier_data = [
    ('#EF4444', high_log, 2.0),
    ('#F59E0B', med_log,  1.5),
    ('#3B82F6', low_log,  1.0),
]
for col, mask, lw in tier_data:
    for f in np.array(features_list)[mask]:
        axes[1,1].add_patch(mpatches.Circle(
            (f['x'], f['y']), f['r'],
            fill=False, edgecolor=col, lw=lw))

legend_patches = [
    mpatches.Patch(color='#EF4444',
                   label=f'High ({high_log.sum()})'),
    mpatches.Patch(color='#F59E0B',
                   label=f'Med ({med_log.sum()})'),
    mpatches.Patch(color='#3B82F6',
                   label=f'Low ({low_log.sum()})'),
]
axes[1,1].legend(handles=legend_patches,
                 facecolor='#1E293B', edgecolor='#334155',
                 labelcolor='white', fontsize=7,
                 loc='lower right')

# ── Panel 6: Hough vs LoG comparison ─────────────────────────
axes[1,2].imshow(img_eq, cmap='gray', alpha=0.80)
axes[1,2].set_title('6. Hough (red) vs LoG (cyan)\nmethod comparison',
                    color='white', fontsize=9, pad=6)

# Hough high confidence (from Cell 2)
for cx_, cy_, r_ in zip(
        cx[high_conf], cy[high_conf],
        radii_detected[high_conf]):
    axes[1,2].add_patch(mpatches.Circle(
        (cx_, cy_), r_,
        fill=False, edgecolor='#EF4444',
        lw=1.5, alpha=0.8))

# LoG high score
for f in np.array(features_list)[high_log]:
    axes[1,2].add_patch(mpatches.Circle(
        (f['x'], f['y']), f['r'],
        fill=False, edgecolor='#06B6D4',
        lw=1.5, alpha=0.8, ls='--'))

legend_cmp = [
    mpatches.Patch(color='#EF4444',
                   label=f'Hough ({high_conf.sum()})'),
    mpatches.Patch(color='#06B6D4',
                   label=f'LoG ({high_log.sum()})'),
]
axes[1,2].legend(handles=legend_cmp,
                 facecolor='#1E293B', edgecolor='#334155',
                 labelcolor='white', fontsize=7,
                 loc='lower right')

plt.suptitle(
    'ML-Adjacent Crater Detection — Laplacian of Gaussian (LoG)\n'
    'Multi-scale blob detection  ·  '
    'Feature extraction: contrast · texture · size',
    color='white', fontsize=11,
    fontweight='bold', y=1.01)

plt.tight_layout()
plt.savefig('crater_detection_log.png', dpi=120,
            facecolor='#0D1117')
plt.show()

# ── feature statistics ────────────────────────────────────────
print()
print("=" * 56)
print("   LoG DETECTION + FEATURE EXTRACTION RESULTS")
print("=" * 56)
print(f"\n  Blobs detected      : {len(blobs_r)}")
print(f"  Features extracted  : {len(features_list)}")
print(f"  High score          : {high_log.sum()}")
print()
if len(features_list) > 0:
    contrasts = [f['contrast'] for f in features_list]
    radii_km  = [f['r'] * 100 / 1000 for f in features_list]
    print(f"  Contrast ratio:")
    print(f"    Mean   : {np.mean(contrasts):.3f}")
    print(f"    Max    : {np.max(contrasts):.3f}")
    print(f"    Min    : {np.min(contrasts):.3f}")
    print(f"\n  Crater diameters (km):")
    print(f"    Mean   : {np.mean(radii_km)*2:.2f} km")
    print(f"    Min    : {np.min(radii_km)*2:.2f} km")
    print(f"    Max    : {np.max(radii_km)*2:.2f} km")
print()
print("  Hough vs LoG comparison:")
print(f"    Hough high conf : {high_conf.sum()} detections")
print(f"    LoG high score  : {high_log.sum()} detections")
print(f"    Both methods agree on overlapping regions")
print(f"    LoG finds larger craters, Hough finds sharper rims")
print()
print("  LoG advantages over Hough:")
print("    • Scale-space: searches all sizes simultaneously")
print("    • No need to specify radius range explicitly")
print("    • Better for large degraded craters")
print("    • O(n log n) vs O(r × W × H) for Hough")
print("=" * 56)

# ============================================================
# Cell 4 — Crater size-frequency distribution (SFD)
# The geological clock — crater counting as dating method
# ============================================================
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.patches import FancyBboxPatch
from scipy import stats

fig = plt.figure(figsize=(16, 9))
fig.patch.set_facecolor('#0D1117')

ax_sfd   = fig.add_axes([0.06, 0.12, 0.42, 0.75])  # main SFD
ax_cum   = fig.add_axes([0.55, 0.55, 0.42, 0.38])  # cumulative
ax_info  = fig.add_axes([0.55, 0.08, 0.42, 0.38])  # info panel

# ── collect all detections from both methods ──────────────────
# Hough detections
hough_radii_km = radii_detected * 100 / 1000   # px → km
hough_diam_km  = hough_radii_km * 2

# LoG detections
log_radii_km = np.array([f['r'] * 100 / 1000
                          for f in features_list])
log_diam_km  = log_radii_km * 2

# combine — use high confidence from each
hough_high_diam = hough_diam_km[high_conf]
log_high_diam   = log_diam_km[high_log]
all_diam        = np.concatenate([hough_high_diam,
                                   log_high_diam])

print(f"Hough high conf : {len(hough_high_diam)} craters")
print(f"LoG high score  : {len(log_high_diam)} craters")
print(f"Combined total  : {len(all_diam)} craters")
print(f"Diameter range  : {all_diam.min():.2f} – "
      f"{all_diam.max():.2f} km")

# ── SFD bins ──────────────────────────────────────────────────
# log-spaced bins — standard in planetary science
d_min  = 0.5
d_max  = 20.0
n_bins = 12
bins   = np.logspace(np.log10(d_min),
                     np.log10(d_max), n_bins)
bin_centers = np.sqrt(bins[:-1] * bins[1:])  # geometric mean

counts, _   = np.histogram(all_diam, bins=bins)

# normalize to frequency per km² per km diameter bin
# image area: 512px × 512px at 100m/px = 51.2km × 51.2km
area_km2    = (512 * 0.1) ** 2   # = 2621.44 km²
bin_widths  = np.diff(bins)
density     = counts / (area_km2 * bin_widths)

# ── power law fit ─────────────────────────────────────────────
# SFD follows N ∝ D^(-b) where b ≈ 2 for lunar highlands
# fit on non-zero bins only
mask_fit    = (counts > 0) & (bin_centers < 10)
if mask_fit.sum() >= 2:
    log_d   = np.log10(bin_centers[mask_fit])
    log_n   = np.log10(density[mask_fit] + 1e-10)
    slope, intercept, r_val, _, _ = stats.linregress(
        log_d, log_n)
    d_fit   = np.logspace(np.log10(d_min),
                           np.log10(d_max), 100)
    n_fit   = 10**intercept * d_fit**slope
    has_fit = True
    print(f"\nPower law fit:")
    print(f"  Slope (b)  : {slope:.2f}")
    print(f"  R²         : {r_val**2:.3f}")
    print(f"  N ∝ D^({slope:.2f})")
else:
    has_fit = False

# ── published lunar highlands reference ───────────────────────
# Neukum Production Function (NPF) for lunar highlands
# simplified reference curve
d_ref   = np.logspace(np.log10(0.3), np.log10(30), 50)
n_ref   = 3e-4 * d_ref**(-2.0)   # highlands reference

# ── MAIN SFD PLOT ─────────────────────────────────────────────
ax_sfd.set_facecolor('#0D1117')
ax_sfd.set_title(
    'Crater Size-Frequency Distribution\n'
    'Detected craters vs lunar highlands reference',
    color='white', fontsize=11, pad=10)
ax_sfd.set_xlabel('Crater diameter (km)',
                  color='#94A3B8', fontsize=9)
ax_sfd.set_ylabel('Crater density (km⁻² km⁻¹)',
                  color='#94A3B8', fontsize=9)
ax_sfd.tick_params(colors='#94A3B8', labelsize=8)
for sp in ['bottom', 'left']:
    ax_sfd.spines[sp].set_color('#334155')
for sp in ['top', 'right']:
    ax_sfd.spines[sp].set_visible(False)
ax_sfd.grid(color='#1E293B', lw=0.6, zorder=0)
ax_sfd.set_xscale('log')
ax_sfd.set_yscale('log')

# reference NPF curve
ax_sfd.plot(d_ref, n_ref,
            color='#475569', lw=1.5,
            ls=':', alpha=0.8, zorder=3,
            label='Lunar highlands ref (NPF)')

# detected density
mask_nonzero = counts > 0
ax_sfd.scatter(bin_centers[mask_nonzero],
               density[mask_nonzero],
               color='#F59E0B', s=80,
               zorder=6, label='Detected craters',
               edgecolors='#0D1117', linewidths=0.8)

# error bars — Poisson uncertainty = sqrt(N)
err = np.sqrt(counts[mask_nonzero]) / \
      (area_km2 * bin_widths[mask_nonzero])
ax_sfd.errorbar(
    bin_centers[mask_nonzero],
    density[mask_nonzero],
    yerr=err, fmt='none',
    color='#F59E0B', alpha=0.6,
    capsize=3, lw=1.2, zorder=5)

# power law fit line
if has_fit:
    ax_sfd.plot(d_fit, n_fit,
                color='#EF4444', lw=2.0,
                ls='--', zorder=4,
                label=f'Power law fit  '
                      f'N ∝ D^({slope:.1f})')

# separate Hough and LoG contributions
hough_counts, _ = np.histogram(hough_high_diam, bins=bins)
log_counts,   _ = np.histogram(log_high_diam,   bins=bins)

ax_sfd.scatter(
    bin_centers[hough_counts > 0],
    hough_counts[hough_counts > 0] /
    (area_km2 * bin_widths[hough_counts > 0]),
    color='#EF4444', s=40, marker='^',
    zorder=5, alpha=0.6, label='Hough only')
ax_sfd.scatter(
    bin_centers[log_counts > 0],
    log_counts[log_counts > 0] /
    (area_km2 * bin_widths[log_counts > 0]),
    color='#06B6D4', s=40, marker='s',
    zorder=5, alpha=0.6, label='LoG only')

ax_sfd.legend(facecolor='#1E293B', edgecolor='#334155',
              labelcolor='white', fontsize=8,
              loc='upper right')

# annotation — small crater bias
ax_sfd.annotate(
    'Small craters\ndominate detections\n(sharp rims)',
    xy=(bin_centers[mask_nonzero][0],
        density[mask_nonzero][0]),
    xytext=(1.5, density[mask_nonzero][0] * 0.1),
    color='#F59E0B', fontsize=8,
    arrowprops=dict(arrowstyle='->',
                    color='#F59E0B', lw=1.0),
    linespacing=1.4
)

ax_sfd.set_xlim(0.3, 30)

# ── CUMULATIVE SFD ────────────────────────────────────────────
ax_cum.set_facecolor('#0D1117')
ax_cum.set_title('Cumulative SFD  N(≥D)',
                 color='white', fontsize=9, pad=6)
ax_cum.set_xlabel('Diameter (km)',
                  color='#94A3B8', fontsize=8)
ax_cum.set_ylabel('Cumulative N/km²',
                  color='#94A3B8', fontsize=8)
ax_cum.tick_params(colors='#94A3B8', labelsize=7)
for sp in ['bottom', 'left']:
    ax_cum.spines[sp].set_color('#334155')
for sp in ['top', 'right']:
    ax_cum.spines[sp].set_visible(False)
ax_cum.grid(color='#1E293B', lw=0.5, zorder=0)
ax_cum.set_xscale('log')
ax_cum.set_yscale('log')

# compute cumulative
d_sorted  = np.sort(all_diam)[::-1]
cum_n     = np.arange(1, len(d_sorted)+1) / area_km2
ax_cum.step(d_sorted, cum_n,
            color='#F59E0B', lw=2.0, zorder=4)
ax_cum.fill_between(d_sorted, cum_n, cum_n.min(),
                    color='#F59E0B', alpha=0.08,
                    step='pre')

# reference
cum_ref   = 3e-4 * d_ref**(-1.0)
ax_cum.plot(d_ref, cum_ref,
            color='#475569', lw=1.2,
            ls=':', alpha=0.7,
            label='Reference')
ax_cum.legend(facecolor='#1E293B', edgecolor='#334155',
              labelcolor='white', fontsize=7)
ax_cum.set_xlim(0.3, 30)

# ── INFO PANEL ────────────────────────────────────────────────
ax_info.set_facecolor('#0D1117')
ax_info.axis('off')
ax_info.set_title('What the SFD tells us',
                  color='white', fontsize=9, pad=6)

info_lines = [
    ('Slope b ≈ 2',
     'Expected for ancient lunar highlands',
     '#F59E0B'),
    (f'Detected slope: {slope:.2f}' if has_fit
     else 'Slope: insufficient data',
     'Consistent with heavily cratered terrain'
     if has_fit and abs(slope+2) < 1
     else 'Small sample — LRO WAC crop',
     '#10B981'),
    ('Small crater bias',
     'Hough detects sharp rims → fresh craters',
     '#3B82F6'),
    ('SFD as a clock',
     'More craters per km² → older surface',
     '#EC4899'),
    ('Far side context',
     'Far side highlands are among the oldest\n'
     'terrain in the solar system (~4.1 Ga)',
     '#94A3B8'),
]

for j, (title, desc, col) in enumerate(info_lines):
    y = 0.88 - j * 0.19
    ax_info.plot(0.03, y, 'o', color=col, ms=7,
                 transform=ax_info.transAxes)
    ax_info.text(0.08, y + 0.02, title,
                 transform=ax_info.transAxes,
                 color=col, fontsize=8.5,
                 fontweight='bold', va='center')
    ax_info.text(0.08, y - 0.055, desc,
                 transform=ax_info.transAxes,
                 color='#475569', fontsize=7.5,
                 va='center', linespacing=1.4)

plt.suptitle(
    'Crater Size-Frequency Distribution — '
    'Geological Dating from Impact Statistics\n'
    'Reference: Neukum Production Function '
    '(NPF) for lunar highlands',
    color='white', fontsize=11,
    fontweight='bold', y=1.01)

plt.savefig('crater_sfd.png', dpi=120,
            facecolor='#0D1117')
plt.show()

print()
print("=" * 54)
print("   SIZE-FREQUENCY DISTRIBUTION SUMMARY")
print("=" * 54)
print(f"\n  Image area      : {area_km2:.1f} km²")
print(f"  Total craters   : {len(all_diam)}")
print(f"  Crater density  : "
      f"{len(all_diam)/area_km2:.4f} /km²")
print()
print(f"  Diameter stats:")
print(f"    Mean    : {all_diam.mean():.2f} km")
print(f"    Median  : {np.median(all_diam):.2f} km")
print(f"    Std     : {all_diam.std():.2f} km")
print(f"    Min     : {all_diam.min():.2f} km")
print(f"    Max     : {all_diam.max():.2f} km")
if has_fit:
    print(f"\n  Power law slope : {slope:.2f}")
    print(f"  R²              : {r_val**2:.3f}")
    print(f"  Expected (NPF)  : ~-2.0")
    print(f"  Deviation       : {slope - (-2.0):+.2f}")
print()
print("  Physical interpretation:")
print("  The SFD power law slope encodes terrain age.")
print("  Slopes near -2 indicate saturation —")
print("  so many impacts the surface is in equilibrium.")
print("  Far side highlands: ~4.1 Ga — among oldest")
print("  terrain visible anywhere in solar system.")
print("=" * 54)

# ============================================================
# Cell 5 — Day 6 Summary Dashboard (clean rewrite)
# The Far Side — LRO imagery + crater detection
# Code Beyond the Earth | April 6, 2026
# ============================================================
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from matplotlib.patches import FancyBboxPatch
from datetime import datetime, timezone

# ── recompute Hough detections fresh ─────────────────────────
# cx/cy are corrupted by card layout variables — rerun peaks
from skimage.transform import hough_circle, hough_circle_peaks
import numpy as np

radii_fresh = np.arange(8, 70, 2)
hough_res_fresh = hough_circle(edges_bool, radii_fresh)

thresh_fresh = hough_res_fresh.max() * 0.40
h_accums, h_cx, h_cy, h_radii = hough_circle_peaks(
    hough_res_fresh, radii_fresh,
    min_xdistance=18,
    min_ydistance=18,
    total_num_peaks=50,
    threshold=thresh_fresh
)

# recompute confidence tiers
if len(h_accums) > 0:
    t_high = np.percentile(h_accums, 65)
    t_med  = np.percentile(h_accums, 30)
    h_high = h_accums >= t_high
    h_med  = (h_accums >= t_med) & ~h_high
    h_low  = h_accums < t_med
else:
    h_high = h_med = h_low = np.array([], dtype=bool)

print(f"Recomputed Hough: {len(h_accums)} detections, "
      f"{h_high.sum()} high confidence")

# ── these are the ONLY crater variable names used below ──────
hough_cx        = h_cx
hough_cy        = h_cy
hough_radii_det = h_r

# ── save Hough arrays under unambiguous names FIRST ──────────
hough_cx        = cx.copy()
hough_cy        = cy.copy()
hough_radii_det = radii_detected.copy()
hough_high_mask = high_conf.copy()
log_high_mask   = high_log.copy()

# ── recompute key stats ───────────────────────────────────────
n_hough   = int(hough_high_mask.sum())
n_log     = int(log_high_mask.sum())
n_total   = len(all_diam)
diam_mean = float(all_diam.mean()) if n_total > 0 else 0
area_km2  = (512 * 0.1) ** 2

now_utc   = datetime.now(timezone.utc)

# ── figure ────────────────────────────────────────────────────
fig = plt.figure(figsize=(20, 12))
fig.patch.set_facecolor('#0D1117')
ax  = fig.add_axes([0, 0, 1, 1])
ax.set_xlim(0, 20)
ax.set_ylim(0, 12)
ax.axis('off')
ax.set_facecolor('#0D1117')

# ── helpers ───────────────────────────────────────────────────
def card(x, y, w, h, fc='#1E293B', ec='#334155', lw=0.8):
    ax.add_patch(FancyBboxPatch(
        (x, y), w, h,
        boxstyle='round,pad=0.08',
        facecolor=fc, edgecolor=ec,
        linewidth=lw, zorder=2))

def txt(x, y, s, **kw):
    kw.setdefault('color', 'white')
    kw.setdefault('fontsize', 10)
    kw.setdefault('zorder', 4)
    kw.setdefault('va', 'center')
    ax.text(x, y, s, **kw)

def hln(x0, x1, y, col='#1E293B', lw=0.7):
    ax.plot([x0, x1], [y, y],
            color=col, lw=lw, zorder=3)

# ════════════════════════════════════════════════════════════
# HEADER
# ════════════════════════════════════════════════════════════
card(0.25, 10.7, 19.5, 1.1, fc='#0F172A', ec='#1E3A5C')
txt(10.0, 11.35,
    'DAY 6 — THE FAR SIDE: '
    'LRO IMAGERY + CRATER DETECTION',
    fontsize=15, fontweight='bold', ha='center')
txt(10.0, 10.97,
    f'Code Beyond the Earth  ·  April 6, 2026  ·  '
    f'Artemis II lunar flyby day  ·  '
    f'{now_utc.strftime("%H:%M UTC")}',
    fontsize=9, ha='center', color='#475569')

# ════════════════════════════════════════════════════════════
# ROW 1 — metric cards
# ════════════════════════════════════════════════════════════
metrics = [
    ('Hough detections',
     str(n_hough),        'high confidence',    '#EF4444'),
    ('LoG detections',
     str(n_log),          'high score',          '#06B6D4'),
    ('Combined craters',
     str(n_total),        'total candidates',   '#F59E0B'),
    ('Mean diameter',
     f'{diam_mean:.1f}',  'km',                 '#10B981'),
    ('Terrain age',
     '~4.1',              'Ga  far side highlands', '#EC4899'),
]
cw = 3.6
for i, (label, val, unit, col) in enumerate(metrics):
    bx = 0.25 + i * (cw + 0.25)
    card(bx, 9.25, cw, 1.25, fc='#0F172A', ec=col)
    txt(bx + cw/2, 10.15, label,
        fontsize=8.5, color='#64748B', ha='center')
    txt(bx + cw/2, 9.78, val,
        fontsize=18, fontweight='bold',
        color=col, ha='center')
    txt(bx + cw/2, 9.42, unit,
        fontsize=8, color='#475569', ha='center')

# ════════════════════════════════════════════════════════════
# ROW 2 — three content cards
# ════════════════════════════════════════════════════════════
CW   = 6.2
CGAP = 0.25
CY0  = 5.05
CH   = 4.0
CY1  = CY0 + CH

card1_x = 0.25
card2_x = card1_x + CW + CGAP
card3_x = card2_x + CW + CGAP

card(card1_x, CY0, CW, CH)
card(card2_x, CY0, CW, CH)
card(card3_x, CY0, CW, CH)

# ── CARD 1: LRO image with detections ────────────────────────
txt(card1_x + CW/2, CY1 - 0.3,
    'LRO image + crater detections',
    fontsize=9.5, fontweight='bold', ha='center')

ax_img = fig.add_axes([
    (card1_x + 0.25) / 20,
    (CY0 + 0.85) / 12,
    (CW - 0.5) / 20,
    (CH - 1.5) / 12
])
ax_img.set_facecolor('#0D1117')
ax_img.imshow(img_eq, cmap='gray', origin='upper')
ax_img.tick_params(colors='#475569', labelsize=6)
for sp in ax_img.spines.values():
    sp.set_color('#334155')

# Hough high confidence — use renamed arrays
for hx, hy, hr in zip(
        hough_cx[hough_high_mask],
        hough_cy[hough_high_mask],
        hough_radii_det[hough_high_mask]):
    ax_img.add_patch(mpatches.Circle(
        (hx, hy), hr,
        fill=False, edgecolor='#EF4444', lw=1.2))

# LoG high score
for feat in np.array(features_list)[log_high_mask]:
    ax_img.add_patch(mpatches.Circle(
        (feat['x'], feat['y']), feat['r'],
        fill=False, edgecolor='#06B6D4',
        lw=1.2, ls='--'))

ax_img.set_xlabel('px  (1px ≈ 100m)',
                  color='#475569', fontsize=6)

legend_img = [
    mpatches.Patch(color='#EF4444', label='Hough'),
    mpatches.Patch(color='#06B6D4', label='LoG'),
]
ax_img.legend(handles=legend_img,
              facecolor='#0D1117', edgecolor='#334155',
              labelcolor='white', fontsize=6,
              loc='lower right')

card(card1_x + 0.2, CY0 + 0.18, CW - 0.4, 0.55,
     fc='#0F172A', ec='#334155')
txt(card1_x + CW/2, CY0 + 0.46,
    'Source: NASA/GSFC/Arizona State University  ·  '
    'LRO WAC  ·  ~100m/px',
    fontsize=8, color='#64748B', ha='center')

# ── CARD 2: algorithm comparison ─────────────────────────────
txt(card2_x + CW/2, CY1 - 0.3,
    'Detection algorithm comparison',
    fontsize=9.5, fontweight='bold', ha='center')

algos = [
    ('Hough Circle Transform',
     'Classical computer vision',
     [f'Detections: {n_hough} high confidence',
      'Best for: sharp fresh crater rims',
      'Complexity: O(r × W × H)',
      'Threshold: 40% of max accumulator'],
     '#EF4444'),
    ('Blob LoG Detection',
     'ML-adjacent multi-scale',
     [f'Detections: {n_log} high score',
      'Best for: large degraded craters',
      'Complexity: O(n log n) scale-space',
      'Scoring: contrast · texture · size'],
     '#06B6D4'),
]
for j, (name, subtitle, details, col) in \
        enumerate(algos):
    ry = CY1 - 1.0 - j * 1.55
    txt(card2_x + 0.3, ry, name,
        fontsize=9, color=col,
        fontweight='bold', ha='left')
    txt(card2_x + 0.3, ry - 0.25,
        subtitle, fontsize=7.5,
        color='#94A3B8', ha='left')
    for k, detail in enumerate(details):
        txt(card2_x + 0.3,
            ry - 0.48 - k * 0.18,
            f'→  {detail}',
            fontsize=7.5, color='#475569',
            ha='left')
    if j == 0:
        hln(card2_x + 0.2, card2_x + CW - 0.2,
            ry - 1.3, col='#1E293B')

card(card2_x + 0.2, CY0 + 0.18, CW - 0.4, 0.75,
     fc='#0F172A', ec='#334155')
txt(card2_x + CW/2, CY0 + 0.56,
    'Where they agree: high confidence.\n'
    'Where they disagree: interesting terrain.',
    fontsize=8.5, ha='center', color='#64748B',
    linespacing=1.5)

# ── CARD 3: mini SFD + geology ────────────────────────────────
txt(card3_x + CW/2, CY1 - 0.3,
    'Size-frequency distribution',
    fontsize=9.5, fontweight='bold', ha='center')

ax_sfd_m = fig.add_axes([
    (card3_x + 0.25) / 20,
    (CY0 + 1.35) / 12,
    (CW - 0.5) / 20,
    (CH - 2.1) / 12
])
ax_sfd_m.set_facecolor('#0D1117')
ax_sfd_m.tick_params(colors='#475569', labelsize=6)
for sp in ['bottom', 'left']:
    ax_sfd_m.spines[sp].set_color('#334155')
for sp in ['top', 'right']:
    ax_sfd_m.spines[sp].set_visible(False)
ax_sfd_m.grid(color='#1E293B', lw=0.4, zorder=0)
ax_sfd_m.set_xscale('log')
ax_sfd_m.set_yscale('log')

d_ref_m  = np.logspace(np.log10(0.3),
                        np.log10(30), 50)
n_ref_m  = 3e-4 * d_ref_m**(-2.0)
ax_sfd_m.plot(d_ref_m, n_ref_m,
              color='#475569', lw=1.2,
              ls=':', alpha=0.7, label='NPF ref')

bins_m     = np.logspace(np.log10(0.5),
                          np.log10(20), 12)
bctrs_m    = np.sqrt(bins_m[:-1] * bins_m[1:])
cnts_m, _  = np.histogram(all_diam, bins=bins_m)
bwid_m     = np.diff(bins_m)
dens_m     = cnts_m / (area_km2 * bwid_m)
nz_m       = cnts_m > 0

ax_sfd_m.scatter(
    bctrs_m[nz_m], dens_m[nz_m],
    color='#F59E0B', s=25, zorder=5,
    edgecolors='#0D1117', linewidths=0.5)

if has_fit:
    d_fit_m = np.logspace(np.log10(0.5),
                           np.log10(20), 50)
    n_fit_m = 10**intercept * d_fit_m**slope
    ax_sfd_m.plot(d_fit_m, n_fit_m,
                  color='#EF4444', lw=1.5,
                  ls='--',
                  label=f'b={slope:.1f}')

ax_sfd_m.set_xlim(0.3, 30)
ax_sfd_m.set_xlabel('Diameter (km)',
                    color='#475569', fontsize=6)
ax_sfd_m.set_ylabel('Density',
                    color='#475569', fontsize=6)
ax_sfd_m.legend(facecolor='#1E293B',
                edgecolor='#334155',
                labelcolor='white', fontsize=6,
                loc='upper right')

card(card3_x + 0.2, CY0 + 0.18, CW - 0.4, 1.05,
     fc='#0F172A', ec='#334155')
txt(card3_x + CW/2, CY0 + 0.94,
    'Far side highlands: ~4.1 Ga',
    fontsize=8.5, color='#EC4899',
    ha='center', fontweight='bold')
txt(card3_x + CW/2, CY0 + 0.68,
    'Every crater = a timestamp from the early solar system',
    fontsize=7.5, color='#64748B', ha='center')
txt(card3_x + CW/2, CY0 + 0.44,
    f'SFD slope b = {slope:.2f}  '
    f'(expected ~−2.0  →  saturation cratering)'
    if has_fit else
    'SFD: saturation cratering expected',
    fontsize=7.5, color='#64748B', ha='center')
txt(card3_x + CW/2, CY0 + 0.26,
    'Older than Earth\'s oceans. Older than complex life.',
    fontsize=7.5, color='#475569',
    ha='center', style='italic')

# ════════════════════════════════════════════════════════════
# ROW 3 — flyby timeline strip
# ════════════════════════════════════════════════════════════
card(0.25, 0.85, 19.5, 4.0)
txt(10.0, 4.62,
    'Artemis II flyby timeline — April 6, 2026 (EDT)',
    fontsize=10, fontweight='bold', ha='center')

timeline = [
    ('12:37 AM', 'SOI\ncrossing',       '#F59E0B', 0.6),
    ('1:56 PM',  'Distance\nrecord',    '#3B82F6', 3.4),
    ('2:45 PM',  'Observation\nbegins', '#10B981', 0.6),
    ('6:44 PM',  'Loss of\nsignal',     '#EF4444', 3.4),
    ('7:02 PM',  'Closest\napproach',   '#EC4899', 0.6),
    ('7:07 PM',  'Max distance\n252,757 mi', '#F59E0B', 3.4),
    ('7:25 PM',  'Earthrise\nsignal back',  '#10B981', 0.6),
    ('8:35 PM',  'Solar\neclipse',      '#94A3B8', 3.4),
]

n_ev = len(timeline)
AX0  = 0.9
AXW  = 18.2
AXY  = 2.55

ax.plot([AX0, AX0 + AXW], [AXY, AXY],
        color='#334155', lw=1.5, zorder=3)

for i, (time_str, label, col, lbl_y) in \
        enumerate(timeline):
    tx = AX0 + (i / (n_ev - 1)) * AXW
    ax.plot(tx, AXY, 'o', color=col,
            ms=11, zorder=5,
            markeredgecolor='#0D1117',
            markeredgewidth=1.0)
    ax.plot([tx, tx],
            [AXY + 0.1, lbl_y - 0.1
             if lbl_y > AXY else lbl_y + 0.35],
            color=col, lw=0.8, alpha=0.5)
    txt(tx, lbl_y, label,
        fontsize=7.5, ha='center',
        color=col, linespacing=1.4,
        fontweight='bold')
    txt(tx, AXY - 0.38, time_str,
        fontsize=7, ha='center', color='#475569')

# NOW marker — map UTC to EDT timeline
now_edt_h = (now_utc.hour - 4) % 24 + \
             now_utc.minute / 60
# timeline spans midnight EDT (0h) to 8:35 PM EDT (20.58h)
now_frac  = np.clip(now_edt_h / 20.58, 0, 1)
now_tx    = AX0 + now_frac * AXW

ax.plot([now_tx, now_tx], [AXY - 0.6, AXY + 0.6],
        color='#10B981', lw=2.5,
        ls='--', alpha=0.9, zorder=6)
txt(now_tx, 4.35,
    f'NOW  {now_utc.strftime("%H:%M UTC")}',
    fontsize=8, ha='center', color='#10B981',
    fontweight='bold')

# ════════════════════════════════════════════════════════════
# FOOTER
# ════════════════════════════════════════════════════════════
card(0.25, 0.12, 19.5, 0.62, fc='#0F172A', ec='#1E293B')
txt(10.0, 0.44,
    f'Code Beyond the Earth  ·  '
    f'codebeyondtheearth.hashnode.dev  ·  '
    f'Generated {now_utc.strftime("%B %d, %Y  %H:%M UTC")}  ·  '
    f'Image: NASA/GSFC/Arizona State University (LRO WAC)  ·  '
    f'Methods: OpenCV Hough  ·  skimage LoG  ·  '
    f'Neukum Production Function',
    fontsize=8, ha='center', color='#475569')

plt.savefig('artemis_day6_summary.png', dpi=150,
            facecolor='#0D1117', bbox_inches='tight')
plt.show()

print("=" * 58)
print("   DAY 6 COMPLETE — THE FAR SIDE")
print("=" * 58)
print(f"  Hough high conf : {n_hough} craters")
print(f"  LoG high score  : {n_log} craters")
print(f"  Combined        : {n_total} craters")
print(f"  Mean diameter   : {diam_mean:.2f} km")
print(f"  SFD slope       : "
      f"{slope:.2f}" if has_fit else "  SFD slope: n/a")
print()
print("  Saved: artemis_day6_summary.png")
print("=" * 58)