# -*- coding: utf-8 -*-
"""lunar-sphere-of-influence.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ts3oWA0hmhjCxh93VG1131JjQQR-r1bp
"""

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.patches import FancyBboxPatch, Circle,Wedge
from datetime import datetime, timezone, timedelta
from IPython.display import HTML

# ============================================================
# Day 5 — Where Earth Ends
# Lunar Sphere of Influence + L1 Lagrange Point Analysis
# Code Beyond the Earth | April 5, 2026
# ============================================================

# ── Gravitational constants ───────────────────────────────────
GM_earth = 3.986004418e14   # [m³/s²]
GM_moon  = 4.902800066e12   # [m³/s²]
G        = 6.674e-11        # [m³ kg⁻¹ s⁻²]

M_earth  = GM_earth / G     # [kg]
M_moon   = GM_moon  / G     # [kg]

# ── Orbital parameters ────────────────────────────────────────
D_moon   = 384_400_000      # Earth-Moon distance [m]
R_earth  = 6_371_000        # Earth radius [m]
R_moon   = 1_737_400        # Moon radius [m]

# ── Current mission state (from Euronews Day 5 update) ───────
dist_from_earth_now = 271_979_000   # m  (271,979 km)
dist_from_moon_now  = 178_154_000   # m  (178,154 km)

# ════════════════════════════════════════════════════════════
# COMPUTATION 1: Lunar Sphere of Influence (SOI)
# ════════════════════════════════════════════════════════════
# Laplace's formula:
# r_SOI = D_moon * (M_moon / M_earth)^(2/5)
#
# Physical meaning: the distance from the Moon at which
# the Moon's gravitational perturbation on a spacecraft
# equals Earth's gravitational perturbation.
# Used in patched conic approximation for mission planning.

r_SOI = D_moon * (M_moon / M_earth) ** (2/5)

# ════════════════════════════════════════════════════════════
# COMPUTATION 2: L1 Lagrange Point
# ════════════════════════════════════════════════════════════
# The L1 point is where the gravitational forces of Earth
# and Moon plus the centrifugal force in the rotating frame
# exactly balance. Solved numerically from:
#
# GM_earth / r² = GM_moon / (D-r)² + ω²r
# where ω = orbital angular velocity of Moon around Earth
# and r = distance from Earth to L1

omega = np.sqrt(GM_earth / D_moon**3)  # Moon's angular velocity

# Solve for L1 numerically along Earth-Moon line
# Rearrange: f(r) = 0
def L1_equation(r):
    """Force balance equation at L1 in rotating frame."""
    F_earth = GM_earth / r**2
    F_moon  = GM_moon  / (D_moon - r)**2
    F_cent  = omega**2 * r
    return F_earth - F_moon - F_cent

# Newton-Raphson from initial guess
r_L1 = D_moon * 0.85   # start near Moon
for _ in range(1000):
    f  = L1_equation(r_L1)
    # numerical derivative
    dr = 1000  # 1 km step
    df = (L1_equation(r_L1 + dr) - L1_equation(r_L1 - dr)) / (2*dr)
    r_L1 -= f / df
    if abs(f) < 1e-6:
        break

# distance from Moon to L1
r_L1_from_moon = D_moon - r_L1

# ════════════════════════════════════════════════════════════
# COMPUTATION 3: Simple gravity balance point
# (where |F_earth| = |F_moon|, no rotation)
# ════════════════════════════════════════════════════════════
# GM_earth/r² = GM_moon/(D-r)²
# Solve analytically:
# sqrt(GM_earth)*(D-r) = sqrt(GM_moon)*r
# r = D * sqrt(GM_earth) / (sqrt(GM_earth) + sqrt(GM_moon))

r_balance = D_moon * np.sqrt(GM_earth) / \
            (np.sqrt(GM_earth) + np.sqrt(GM_moon))
r_balance_from_moon = D_moon - r_balance

# ════════════════════════════════════════════════════════════
# COMPUTATION 4: When does Orion cross the SOI?
# ════════════════════════════════════════════════════════════
# NASA published: 12:41 AM ET Monday = 04:41 UTC April 6
# = 07:41 UTC April 6 (corrected from NBC)
# Current distance from Moon: 178,154 km
# SOI radius: ~66,100 km
# Orion needs to travel: 178,154 - 66,100 = ~112,054 km
# Average approach speed: ~0.9 km/s at this stage
dist_to_SOI    = (dist_from_moon_now - r_SOI) / 1000  # km
# corrected from NASA published crossing time
# 178,154 km to go, ~12 hours remaining → ~4.1 km/s approach speed
avg_speed      = 4.1   # km/s — accelerating under lunar gravity
time_to_SOI_hr = dist_to_SOI / avg_speed / 3600

# ── Print summary ─────────────────────────────────────────────
print("=" * 60)
print("   DAY 5 — WHERE EARTH ENDS")
print("   Lunar Sphere of Influence + L1 Lagrange Point")
print("=" * 60)
print()
print("  Physical constants:")
print(f"    GM_earth     : {GM_earth:.4e} m³/s²")
print(f"    GM_moon      : {GM_moon:.4e} m³/s²")
print(f"    Mass ratio   : {M_earth/M_moon:,.1f} × "
      f"(Earth is {M_earth/M_moon:.0f}× heavier)")
print(f"    Earth-Moon D : {D_moon/1e6:.3f} × 10⁶ m")
print()
print("  Sphere of Influence (Laplace formula):")
print(f"    r_SOI        : {r_SOI/1e6:.4f} × 10⁶ m")
print(f"                 : {r_SOI/1000:.1f} km from Moon")
print(f"                 : {(D_moon-r_SOI)/1e6:.3f} × 10⁶ m "
      f"from Earth")
print()
print("  L1 Lagrange Point (rotating frame):")
print(f"    r_L1         : {r_L1/1e6:.4f} × 10⁶ m from Earth")
print(f"                 : {r_L1_from_moon/1000:.1f} km from Moon")
print()
print("  Simple gravity balance (no rotation):")
print(f"    r_balance    : {r_balance/1e6:.4f} × 10⁶ m from Earth")
print(f"                 : {r_balance_from_moon/1000:.1f} km from Moon")
print()
print("  Three boundaries compared:")
print(f"    SOI          : {r_SOI/1000:,.0f} km from Moon")
print(f"    L1 point     : {r_L1_from_moon/1000:,.0f} km from Moon")
print(f"    Gravity bal. : {r_balance_from_moon/1000:,.0f} km from Moon")
print()
print("  Current mission state:")
print(f"    From Earth   : {dist_from_earth_now/1000:,.0f} km")
print(f"    From Moon    : {dist_from_moon_now/1000:,.0f} km")
print(f"    Distance to SOI crossing : "
      f"{dist_to_SOI:,.0f} km remaining")
print(f"    Est. time to SOI         : "
      f"~{time_to_SOI_hr:.1f} hours")
print()
print("  NASA published crossing time:")
print(f"    12:41 AM ET Monday = 04:41 UTC April 6")
print(f"    = 07:41 Istanbul time")
print("=" * 60)

# ============================================================
# Cell 2 — Gravitational acceleration along Earth-Moon line
# Shows all three boundary crossings on one plot
# ============================================================

fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(14, 10),
                                gridspec_kw={'height_ratios': [2, 1]})
fig.patch.set_facecolor('#0D1117')

# ── position array along Earth-Moon line ─────────────────────
# r = distance from Earth center [m]
# avoid singularities near Earth and Moon surfaces
r_min = R_earth  + 100_000      # just above Earth surface
r_max = D_moon   - R_moon - 100_000  # just above Moon surface

r = np.linspace(r_min, r_max, 10_000)

# ── gravitational accelerations ──────────────────────────────
# Earth pulls spacecraft toward Earth (negative = toward Earth)
g_earth = GM_earth / r**2         # magnitude [m/s²]

# Moon pulls spacecraft toward Moon (away from Earth)
r_from_moon = D_moon - r
g_moon  = GM_moon / r_from_moon**2  # magnitude [m/s²]

# net acceleration (positive = toward Moon)
g_net   = g_moon - g_earth

# centrifugal term in rotating frame
omega   = np.sqrt(GM_earth / D_moon**3)
g_cent  = omega**2 * r            # centrifugal [m/s²]

# effective potential gradient (rotating frame)
g_eff   = g_moon - g_earth + g_cent  # positive = toward Moon

# ── TOP: individual gravity curves ───────────────────────────
ax1.set_facecolor('#0D1117')
ax1.set_title(
    'Gravitational acceleration along the Earth-Moon line',
    color='white', fontsize=12, pad=10)
ax1.set_ylabel('Gravitational acceleration (m/s²)',
               color='#94A3B8', fontsize=9)
ax1.tick_params(colors='#94A3B8', labelsize=8)
for sp in ['bottom', 'left']:
    ax1.spines[sp].set_color('#334155')
for sp in ['top', 'right']:
    ax1.spines[sp].set_visible(False)
ax1.grid(color='#1E293B', lw=0.6, zorder=0)
ax1.set_yscale('log')

# Earth gravity
ax1.plot(r/1e6, g_earth, color='#3B82F6',
         lw=2.0, zorder=4, label='Earth gravity')

# Moon gravity
ax1.plot(r/1e6, g_moon, color='#94A3B8',
         lw=2.0, zorder=4, label='Moon gravity')

# centrifugal
ax1.plot(r/1e6, g_cent, color='#475569',
         lw=1.2, ls=':', zorder=3,
         label='Centrifugal (rotating frame)')

# ── boundary lines ────────────────────────────────────────────
boundaries = [
    (r_SOI/1e6,         '#F59E0B', 'SOI\n66,183 km\nfrom Moon'),
    (r_L1/1e6,          '#10B981', 'L1\n58,082 km\nfrom Moon'),
    (r_balance/1e6,     '#EC4899', 'Gravity balance\n38,376 km\nfrom Moon'),
]
for bx, col, label in boundaries:
    ax1.axvline(bx, color=col, lw=1.5,
                ls='--', alpha=0.8, zorder=5)
    y_pos = ax1.get_ylim()[1] if ax1.get_ylim()[1] > 0 else 1e-3
    ax1.text(bx + 1.5, 1e-4, label,
             color=col, fontsize=7.5,
             linespacing=1.4, zorder=6)

# intersection markers
# SOI: where g_earth = g_moon (approximately)
soi_idx = np.argmin(np.abs(r - (D_moon - r_SOI)))
ax1.plot(r[soi_idx]/1e6, g_earth[soi_idx], 'o',
         color='#F59E0B', ms=9, zorder=7,
         markeredgecolor='#0D1117', markeredgewidth=1)

# L1: where g_eff = 0
l1_idx  = np.argmin(np.abs(r - r_L1))
ax1.plot(r[l1_idx]/1e6,  g_earth[l1_idx],  'o',
         color='#10B981', ms=9, zorder=7,
         markeredgecolor='#0D1117', markeredgewidth=1)

# current Orion position
orion_r = dist_from_earth_now
orion_idx = np.argmin(np.abs(r - orion_r))
ax1.axvline(orion_r/1e6, color='#10B981',
            lw=1.5, ls='-.', alpha=0.9, zorder=5)
ax1.text(orion_r/1e6 + 1.5, 1e-2,
         f'Orion now\n{orion_r/1e6:.0f} Mm',
         color='#10B981', fontsize=7.5,
         linespacing=1.4)

ax1.set_xlim(0, D_moon/1e6)
ax1.set_ylim(1e-5, 1e1)
ax1.legend(facecolor='#1E293B', edgecolor='#334155',
           labelcolor='white', fontsize=8,
           loc='upper right')

# Earth / Moon labels
ax1.text(5, 5e0, 'Earth\nsurface',
         color='#3B82F6', fontsize=7.5,
         ha='left', linespacing=1.3)
ax1.text(D_moon/1e6 - 5, 5e0, 'Moon\nsurface',
         color='#94A3B8', fontsize=7.5,
         ha='right', linespacing=1.3)

ax1.set_xticklabels([])

# ── BOTTOM: net gravity (which body dominates) ────────────────
ax2.set_facecolor('#0D1117')
ax2.set_title(
    'Net gravitational pull — positive = toward Moon',
    color='white', fontsize=10, pad=8)
ax2.set_xlabel('Distance from Earth center (×10⁶ m = Mm)',
               color='#94A3B8', fontsize=9)
ax2.set_ylabel('Net acceleration (m/s²)',
               color='#94A3B8', fontsize=9)
ax2.tick_params(colors='#94A3B8', labelsize=8)
for sp in ['bottom', 'left']:
    ax2.spines[sp].set_color('#334155')
for sp in ['top', 'right']:
    ax2.spines[sp].set_visible(False)
ax2.grid(color='#1E293B', lw=0.6, zorder=0)

# fill regions
ax2.fill_between(r/1e6, g_net, 0,
                 where=(g_net < 0),
                 color='#3B82F6', alpha=0.15,
                 label='Earth dominates')
ax2.fill_between(r/1e6, g_net, 0,
                 where=(g_net >= 0),
                 color='#94A3B8', alpha=0.15,
                 label='Moon dominates')

ax2.plot(r/1e6, g_net, color='#F59E0B',
         lw=2.0, zorder=4)
ax2.axhline(0, color='#334155', lw=0.8)

# boundary lines
for bx, col, label in boundaries:
    ax2.axvline(bx, color=col, lw=1.5,
                ls='--', alpha=0.8, zorder=5)

# Orion now
ax2.axvline(orion_r/1e6, color='#10B981',
            lw=1.5, ls='-.', alpha=0.9)

# zero crossing annotation (SOI)
soi_cross_r = D_moon - r_SOI
ax2.plot(soi_cross_r/1e6, 0, 'o',
         color='#F59E0B', ms=10, zorder=7,
         markeredgecolor='#0D1117', markeredgewidth=1)
ax2.annotate(
    f'SOI crossing\n{soi_cross_r/1e6:.1f} Mm from Earth\n'
    f'({r_SOI/1000:.0f} km from Moon)',
    xy=(soi_cross_r/1e6, 0),
    xytext=(soi_cross_r/1e6 - 40, -1.5e-5),
    color='#F59E0B', fontsize=8,
    arrowprops=dict(arrowstyle='->',
                    color='#F59E0B', lw=1.0),
    linespacing=1.4
)

# region labels
ax2.text(150, -3e-5, 'Earth pulls\nharder',
         color='#3B82F6', fontsize=8,
         ha='center', style='italic')
ax2.text(360, 3e-5, 'Moon pulls\nharder',
         color='#94A3B8', fontsize=8,
         ha='center', style='italic')

ax2.set_xlim(0, D_moon/1e6)
ax2.legend(facecolor='#1E293B', edgecolor='#334155',
           labelcolor='white', fontsize=8,
           loc='lower right')

plt.tight_layout()
plt.savefig('artemis_gravity_field.png', dpi=120,
            facecolor='#0D1117')
plt.show()

# ── printout ─────────────────────────────────────────────────
print("=" * 56)
print("   GRAVITY FIELD SUMMARY")
print("=" * 56)
print(f"\n  At Earth surface (r = {R_earth/1e6:.3f} Mm):")
print(f"    Earth gravity  : {GM_earth/R_earth**2:.4f} m/s²  (= 9.8 m/s²) ✓")
print(f"\n  At Moon surface (r = {(D_moon-R_moon)/1e6:.3f} Mm):")
print(f"    Moon gravity   : {GM_moon/R_moon**2:.4f} m/s²  (= 1.62 m/s²) ✓")
print(f"\n  At SOI boundary ({(D_moon-r_SOI)/1e6:.1f} Mm from Earth):")
g_e_soi = GM_earth / (D_moon - r_SOI)**2
g_m_soi = GM_moon  / r_SOI**2
print(f"    Earth gravity  : {g_e_soi:.4e} m/s²")
print(f"    Moon gravity   : {g_m_soi:.4e} m/s²")
print(f"    Ratio          : {g_m_soi/g_e_soi:.4f}  (≈1.0 ✓)")
print(f"\n  At L1 ({r_L1/1e6:.1f} Mm from Earth):")
g_e_l1  = GM_earth / r_L1**2
g_m_l1  = GM_moon  / (D_moon - r_L1)**2
g_c_l1  = omega**2 * r_L1
print(f"    Earth gravity  : {g_e_l1:.4e} m/s²")
print(f"    Moon gravity   : {g_m_l1:.4e} m/s²")
print(f"    Centrifugal    : {g_c_l1:.4e} m/s²")
print(f"    Net (≈0)       : {g_e_l1 - g_m_l1 - g_c_l1:.2e} m/s² ✓")
print(f"\n  At Orion now ({dist_from_earth_now/1e6:.0f} Mm from Earth):")
g_e_now = GM_earth / dist_from_earth_now**2
g_m_now = GM_moon  / dist_from_moon_now**2
print(f"    Earth gravity  : {g_e_now:.4e} m/s²")
print(f"    Moon gravity   : {g_m_now:.4e} m/s²")
print(f"    Earth/Moon ratio: {g_e_now/g_m_now:.2f}×  "
      f"(Earth still {g_e_now/g_m_now:.1f}× stronger)")
print(f"\n  SOI crossing in: ~{(dist_from_moon_now - r_SOI)/1000/4.1/3600:.1f} hours")
print("=" * 56)

# ============================================================
# Cell 3 — Orion crossing SOI, L1 and gravity balance
# Timeline of boundary crossings with real mission data
# ============================================================

fig, (ax1, ax2, ax3) = plt.subplots(
    3, 1, figsize=(14, 12),
    gridspec_kw={'height_ratios': [2, 1, 1]}
)
fig.patch.set_facecolor('#0D1117')

# ── mission timeline ──────────────────────────────────────────
# Launch: April 1, 22:35 UTC
# TLI:    April 2, 23:49 UTC  (T+25.23h)
# SOI:    April 6, 04:41 UTC  (T+102.1h) — NASA published
# Flyby:  April 6, ~18:45 UTC (T+116.2h) — closest approach
# Max dist: April 6, ~23:05 UTC (T+120.5h)

LAUNCH_UTC  = datetime(2026, 4, 1,  22, 35, tzinfo=timezone.utc)
TLI_UTC     = datetime(2026, 4, 2,  23, 49, tzinfo=timezone.utc)
SOI_UTC     = datetime(2026, 4, 6,   4, 41, tzinfo=timezone.utc)
FLYBY_UTC   = datetime(2026, 4, 6,  18, 45, tzinfo=timezone.utc)
MAXDIST_UTC = datetime(2026, 4, 6,  23,  5, tzinfo=timezone.utc)
NOW_UTC     = datetime.now(timezone.utc)

def met(dt):
    """Mission elapsed time in hours."""
    return (dt - LAUNCH_UTC).total_seconds() / 3600

MET_TLI     = met(TLI_UTC)
MET_SOI     = met(SOI_UTC)
MET_FLYBY   = met(FLYBY_UTC)
MET_MAXDIST = met(MAXDIST_UTC)
MET_NOW     = met(NOW_UTC)

# ── build distance profile (from Moon) ───────────────────────
t_hours = np.linspace(MET_TLI, MET_FLYBY + 10, 5000)

def dist_from_moon(t):
    """Distance from Moon center [km] as function of MET [hours]."""
    d = np.zeros_like(t)
    for i, ti in enumerate(t):
        if ti < MET_TLI:
            d[i] = D_moon/1000 - 185   # parking orbit
        elif ti < MET_SOI:
            # outbound coast — approaching Moon
            frac  = (ti - MET_TLI) / (MET_SOI - MET_TLI)
            ease  = 3*frac**2 - 2*frac**3  # cubic ease-in
            d[i]  = (D_moon/1000 - 185) - \
                    ((D_moon/1000 - 185) - r_SOI/1000) * ease
        elif ti < MET_FLYBY:
            # inside SOI — falling toward Moon
            frac  = (ti - MET_SOI) / (MET_FLYBY - MET_SOI)
            ease  = 3*frac**2 - 2*frac**3
            d[i]  = r_SOI/1000 - \
                    (r_SOI/1000 - 4066*1.609) * ease
        else:
            # post flyby — receding
            frac  = (ti - MET_FLYBY) / 10
            d[i]  = 4066*1.609 + frac * 50000
    return d

d_moon_km = dist_from_moon(t_hours)
d_earth_km = D_moon/1000 - d_moon_km

# boundary crossings in MET hours
# SOI: d_moon = r_SOI/1000
# L1:  d_earth = r_L1/1000
# bal: d_earth = r_balance/1000

soi_cross_met  = MET_SOI   # NASA published
# find crossings by searching the distance array directly
# only search inbound leg (before closest approach)
flyby_idx = np.argmin(np.abs(t_hours - MET_FLYBY))

l1_idx  = np.argmin(np.abs(
    d_moon_km[:flyby_idx] - r_L1_from_moon/1000))
bal_idx = np.argmin(np.abs(
    d_moon_km[:flyby_idx] - r_balance_from_moon/1000))

l1_cross_met  = t_hours[l1_idx]
bal_cross_met = t_hours[bal_idx]

# ── TOP: distance from Moon timeline ─────────────────────────
ax1.set_facecolor('#0D1117')
ax1.set_title(
    'Orion approaching the Moon — boundary crossings',
    color='white', fontsize=12, pad=10)
ax1.set_ylabel('Distance from Moon (km)',
               color='#94A3B8', fontsize=9)
ax1.tick_params(colors='#94A3B8', labelsize=8)
for sp in ['bottom', 'left']:
    ax1.spines[sp].set_color('#334155')
for sp in ['top', 'right']:
    ax1.spines[sp].set_visible(False)
ax1.grid(color='#1E293B', lw=0.6, zorder=0)

# distance curve
ax1.plot(t_hours, d_moon_km,
         color='#3B82F6', lw=2.5, zorder=5)
ax1.fill_between(t_hours, d_moon_km, 0,
                 color='#3B82F6', alpha=0.06)

# three boundary lines
boundary_lines = [
    (r_SOI/1000,             soi_cross_met,
     '#F59E0B', 'SOI',          '66,183 km'),
    (r_L1_from_moon/1000,    l1_cross_met,
     '#10B981', 'L1 point',     '58,082 km'),
    (r_balance_from_moon/1000, bal_cross_met,
     '#EC4899', 'Gravity bal.', '38,376 km'),
]
for r_km, t_cross, col, name, dist_str in boundary_lines:
    ax1.axhline(r_km, color=col, lw=1.2,
                ls='--', alpha=0.7, zorder=4)
    ax1.axvline(t_cross, color=col, lw=1.0,
                ls=':', alpha=0.5, zorder=3)
    ax1.text(MET_TLI + 2, r_km + 1500,
             f'{name}: {dist_str}',
             color=col, fontsize=8,
             fontweight='bold')

# Moon surface
ax1.axhline(R_moon/1000, color='#6B7280',
            lw=1.0, ls=':', alpha=0.5)
ax1.text(MET_TLI + 2, R_moon/1000 + 500,
         'Moon surface (1,737 km)',
         color='#6B7280', fontsize=7.5)

# closest approach
ax1.plot(MET_FLYBY, 4066*1.609, 'o',
         color='#EC4899', ms=10, zorder=7,
         markeredgecolor='#0D1117', markeredgewidth=1)
ax1.annotate(
    f'Closest approach\n~6,540 km altitude',
    xy=(MET_FLYBY, 4066*1.609),
    xytext=(MET_FLYBY - 8, 15000),
    color='#EC4899', fontsize=8,
    arrowprops=dict(arrowstyle='->',
                    color='#EC4899', lw=1.0),
    linespacing=1.4
)

# Orion now
ax1.axvline(MET_NOW, color='#10B981',
            lw=1.5, ls='-.', alpha=0.9)
ax1.plot(MET_NOW, dist_from_moon_now/1000,
         'o', color='#10B981', ms=8, zorder=7,
         markeredgecolor='#0D1117', markeredgewidth=1)
ax1.text(MET_NOW + 0.5,
         dist_from_moon_now/1000 + 3000,
         f'Orion now\n{dist_from_moon_now/1000:,.0f} km',
         color='#10B981', fontsize=7.5,
         linespacing=1.4)

ax1.set_xlim(MET_TLI, MET_FLYBY + 10)
ax1.set_ylim(0, D_moon/1000 * 0.55)
ax1.set_xticklabels([])

# ── MIDDLE: gravity ratio ─────────────────────────────────────
ax2.set_facecolor('#0D1117')
ax2.set_title(
    'Moon/Earth gravity ratio along Orion trajectory',
    color='white', fontsize=10, pad=8)
ax2.set_ylabel('g_moon / g_earth',
               color='#94A3B8', fontsize=9)
ax2.tick_params(colors='#94A3B8', labelsize=8)
for sp in ['bottom', 'left']:
    ax2.spines[sp].set_color('#334155')
for sp in ['top', 'right']:
    ax2.spines[sp].set_visible(False)
ax2.grid(color='#1E293B', lw=0.6, zorder=0)

# compute ratio along trajectory
g_ratio = np.zeros_like(t_hours)
for i, (dm, de) in enumerate(
        zip(d_moon_km * 1000, d_earth_km * 1000)):
    gm = GM_moon  / dm**2
    ge = GM_earth / de**2
    g_ratio[i] = gm / ge

ax2.plot(t_hours, g_ratio,
         color='#F59E0B', lw=2.0, zorder=4)
ax2.fill_between(t_hours, g_ratio, 1,
                 where=(g_ratio >= 1),
                 color='#94A3B8', alpha=0.12,
                 label='Moon dominant')
ax2.fill_between(t_hours, g_ratio, 1,
                 where=(g_ratio < 1),
                 color='#3B82F6', alpha=0.08,
                 label='Earth dominant')

ax2.axhline(1, color='#F59E0B', lw=1.5,
            ls='--', alpha=0.8)
ax2.text(MET_TLI + 2, 1.05,
         'Ratio = 1.0  (SOI boundary)',
         color='#F59E0B', fontsize=8)

# boundary crossings
for r_km, t_cross, col, name, _ in boundary_lines:
    ax2.axvline(t_cross, color=col, lw=1.0,
                ls=':', alpha=0.6)

ax2.axvline(MET_NOW, color='#10B981',
            lw=1.5, ls='-.', alpha=0.9)

ax2.set_xlim(MET_TLI, MET_FLYBY + 10)
ax2.set_ylim(0, 5)
ax2.legend(facecolor='#1E293B', edgecolor='#334155',
           labelcolor='white', fontsize=8,
           loc='upper left')
ax2.set_xticklabels([])

# ── BOTTOM: crossing timeline strip ──────────────────────────
ax3.set_facecolor('#0D1117')
ax3.set_title(
    'Boundary crossing timeline',
    color='white', fontsize=10, pad=8)
ax3.set_xlabel('Mission elapsed time (hours from launch)',
               color='#94A3B8', fontsize=9)
ax3.tick_params(colors='#94A3B8', labelsize=8)
for sp in ['bottom', 'left']:
    ax3.spines[sp].set_color('#334155')
for sp in ['top', 'right']:
    ax3.spines[sp].set_visible(False)
ax3.set_xlim(MET_TLI, MET_FLYBY + 10)
ax3.set_ylim(-0.5, 3.5)
ax3.set_yticks([])

# timeline base
ax3.axhline(1.5, color='#334155',
            lw=1.5, zorder=2,
            xmin=0, xmax=1)

# events
events = [
    (MET_TLI,      'TLI\nburn',       '#3B82F6', 0.5),
    (MET_SOI,      'SOI\ncrossing',   '#F59E0B', 2.5),
    (l1_cross_met, 'L1\npoint',       '#10B981', 0.5),
    (bal_cross_met,'Gravity\nbalance','#EC4899', 2.5),
    (MET_FLYBY,    'Closest\napproach','#EC4899',0.5),
]
for t_ev, label, col, y_lbl in events:
    ax3.plot(t_ev, 1.5, 'o', color=col,
             ms=11, zorder=5,
             markeredgecolor='#0D1117',
             markeredgewidth=1.2)
    ax3.plot([t_ev, t_ev], [1.5, y_lbl + 0.3],
             color=col, lw=0.8, alpha=0.5)
    ax3.text(t_ev, y_lbl, label,
             color=col, fontsize=7.5,
             ha='center', va='center',
             linespacing=1.3, fontweight='bold')

# now marker
ax3.axvline(MET_NOW, color='#10B981',
            lw=1.5, ls='-.', alpha=0.9)
ax3.text(MET_NOW, 3.1, 'NOW',
         color='#10B981', fontsize=8,
         ha='center', fontweight='bold')

# time labels on x axis
key_times = [MET_TLI, MET_SOI, l1_cross_met,
             bal_cross_met, MET_FLYBY]
for t_ev in key_times:
    ax3.text(t_ev, -0.25,
             f'T+{t_ev:.1f}h',
             color='#475569', fontsize=7,
             ha='center')

plt.tight_layout()
plt.savefig('artemis_boundary_crossings.png', dpi=120,
            facecolor='#0D1117')
plt.show()

# ── printout ─────────────────────────────────────────────────
def met_to_utc(met_h):
    return LAUNCH_UTC + timedelta(hours=met_h)

print("=" * 58)
print("   BOUNDARY CROSSING TIMELINE")
print("=" * 58)
print()
print(f"  TLI burn         : T+{MET_TLI:.1f}h  "
      f"({met_to_utc(MET_TLI).strftime('%b %d %H:%M UTC')})")
print()
print(f"  SOI crossing     : T+{MET_SOI:.1f}h  "
      f"({met_to_utc(MET_SOI).strftime('%b %d %H:%M UTC')})")
print(f"    Distance from Moon : {r_SOI/1000:,.0f} km")
print(f"    NASA published     : Apr 6, 04:41 UTC ✓")
print()
print(f"  L1 Lagrange point: T+{l1_cross_met:.1f}h  "
      f"({met_to_utc(l1_cross_met).strftime('%b %d %H:%M UTC')})")
print(f"    Distance from Moon : {r_L1_from_moon/1000:,.0f} km")
print()
print(f"  Gravity balance  : T+{bal_cross_met:.1f}h  "
      f"({met_to_utc(bal_cross_met).strftime('%b %d %H:%M UTC')})")
print(f"    Distance from Moon : {r_balance_from_moon/1000:,.0f} km")
print()
print(f"  Closest approach : T+{MET_FLYBY:.1f}h  "
      f"({met_to_utc(MET_FLYBY).strftime('%b %d %H:%M UTC')})")
print(f"    Altitude           : ~6,540 km")
print()
print(f"  Current position : T+{MET_NOW:.1f}h  NOW")
print(f"    From Moon          : {dist_from_moon_now/1000:,.0f} km")
print(f"    From Earth         : {dist_from_earth_now/1000:,.0f} km")
print(f"    Hours to SOI       : "
      f"{MET_SOI - MET_NOW:.1f}h")
print("=" * 58)

# ============================================================
# Cell 4 — Gravity field visualization
# 2D potential field map of the Earth-Moon system
# Shows SOI, L1, and all five Lagrange points
# ============================================================
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.patches import Circle
from matplotlib.colors import TwoSlopeNorm

fig, (ax_pot, ax_line) = plt.subplots(
    1, 2, figsize=(16, 8),
    gridspec_kw={'width_ratios': [1.4, 1]}
)
fig.patch.set_facecolor('#0D1117')

# ── 2D grid in rotating frame ─────────────────────────────────
# Units: normalized to Earth-Moon distance = 1
# Earth at (-mu, 0), Moon at (1-mu, 0)
# mu = M_moon / (M_earth + M_moon)

mu    = M_moon / (M_earth + M_moon)   # ~0.01215
omega = np.sqrt(GM_earth / D_moon**3)

# grid in normalized units
N     = 600
xlim  = 1.4
ylim  = 1.2
x_arr = np.linspace(-xlim, xlim, N)
y_arr = np.linspace(-ylim, ylim, N)
X, Y  = np.meshgrid(x_arr, y_arr)

# positions relative to Earth and Moon (normalized)
# Earth at x = -mu, Moon at x = 1-mu
x_earth = -mu
x_moon  = 1 - mu

r1 = np.sqrt((X - x_earth)**2 + Y**2)   # from Earth
r2 = np.sqrt((X - x_moon)**2  + Y**2)   # from Moon

# effective potential in rotating frame
# U_eff = -GM_earth/r1 - GM_moon/r2 - 0.5*omega²*r²
# normalized: -( (1-mu)/r1 + mu/r2 + 0.5*(x²+y²) )
U_eff = -((1 - mu) / np.maximum(r1, 0.01) +
           mu       / np.maximum(r2, 0.01) +
           0.5 * (X**2 + Y**2))

# clip for visualization
U_clip = np.clip(U_eff, -4.5, -1.3)

# ── LEFT: 2D potential map ────────────────────────────────────
ax_pot.set_facecolor('#0D1117')
ax_pot.set_title(
    'Effective gravitational potential — Earth-Moon rotating frame',
    color='white', fontsize=11, pad=10)
ax_pot.set_xlabel('x (normalized, Earth-Moon = 1)',
                  color='#94A3B8', fontsize=9)
ax_pot.set_ylabel('y (normalized)',
                  color='#94A3B8', fontsize=9)
ax_pot.tick_params(colors='#94A3B8', labelsize=8)
for sp in ax_pot.spines.values():
    sp.set_color('#334155')

# potential map
im = ax_pot.contourf(X, Y, U_clip,
                     levels=60,
                     cmap='plasma',
                     zorder=1)
ax_pot.contour(X, Y, U_eff,
               levels=20,
               colors='white',
               alpha=0.08,
               linewidths=0.5,
               zorder=2)

# colorbar
cbar = plt.colorbar(im, ax=ax_pot, shrink=0.8)
cbar.ax.tick_params(colors='#94A3B8', labelsize=7)
cbar.set_label('Effective potential (normalized)',
               color='#94A3B8', fontsize=8)

# ── Lagrange points ───────────────────────────────────────────
# L1: between Earth and Moon
L1_x = (1 - mu) - (mu/3)**(1/3)

# L2: beyond Moon
L2_x = (1 - mu) + (mu/3)**(1/3)

# L3: opposite side of Earth
L3_x = -(1 + 5*mu/12)

# L4, L5: equilateral triangle points
L4_x, L4_y =  0.5 - mu,  np.sqrt(3)/2
L5_x, L5_y =  0.5 - mu, -np.sqrt(3)/2

lagrange_pts = [
    (L1_x, 0,    'L1', '#10B981'),
    (L2_x, 0,    'L2', '#3B82F6'),
    (L3_x, 0,    'L3', '#F59E0B'),
    (L4_x, L4_y, 'L4', '#EC4899'),
    (L5_x, L5_y, 'L5', '#EC4899'),
]
for lx, ly, name, col in lagrange_pts:
    ax_pot.plot(lx, ly, '*', color=col,
                ms=12, zorder=6,
                markeredgecolor='#0D1117',
                markeredgewidth=0.8)
    offset_y = 0.06 if ly >= 0 else -0.09
    ax_pot.text(lx, ly + offset_y, name,
                color=col, fontsize=9,
                ha='center', fontweight='bold',
                zorder=7)

# Earth
ax_pot.add_patch(Circle((x_earth, 0), 0.04,
                 color='#1B4FD8', zorder=5))
ax_pot.text(x_earth, -0.09, 'Earth',
            color='white', ha='center',
            fontsize=8, fontweight='bold')

# Moon
ax_pot.add_patch(Circle((x_moon, 0), 0.02,
                 color='#6B7280', zorder=5))
ax_pot.text(x_moon, -0.07, 'Moon',
            color='white', ha='center',
            fontsize=8, fontweight='bold')

# SOI circle around Moon
theta_c = np.linspace(0, 2*np.pi, 300)
soi_r_norm = r_SOI / D_moon
ax_pot.plot(x_moon + soi_r_norm * np.cos(theta_c),
            soi_r_norm * np.sin(theta_c),
            color='#F59E0B', lw=1.5,
            ls='--', alpha=0.8, zorder=4,
            label=f'SOI ({r_SOI/1000:.0f} km)')

# Orion trajectory (normalized)
t_norm = np.linspace(0, 1, 500)
# simplified outbound arc
orion_x_norm = np.linspace(x_earth + 0.05,
                            x_moon - soi_r_norm * 0.3, 500)
orion_y_norm = 0.15 * np.sin(np.pi * t_norm)
ax_pot.plot(orion_x_norm, orion_y_norm,
            color='#10B981', lw=1.5,
            ls='-.', alpha=0.7, zorder=4,
            label='Orion trajectory (approx)')

# current Orion position
orion_now_x = x_earth + (dist_from_earth_now / D_moon)
orion_now_y = 0.15 * np.sin(np.pi * 0.72)
ax_pot.plot(orion_now_x, orion_now_y, 'o',
            color='#10B981', ms=9, zorder=7,
            markeredgecolor='#0D1117', markeredgewidth=1)
ax_pot.text(orion_now_x, orion_now_y + 0.07,
            'Orion\nnow', color='#10B981',
            fontsize=7.5, ha='center',
            linespacing=1.3)

ax_pot.set_xlim(-xlim, xlim)
ax_pot.set_ylim(-ylim, ylim)
ax_pot.set_aspect('equal')
ax_pot.legend(facecolor='#1E293B', edgecolor='#334155',
              labelcolor='white', fontsize=8,
              loc='upper left')

# ── RIGHT: 1D potential along Earth-Moon line ─────────────────
ax_line.set_facecolor('#0D1117')
ax_line.set_title(
    'Effective potential along\nEarth-Moon line',
    color='white', fontsize=10, pad=8)
ax_line.set_xlabel('x (normalized)',
                   color='#94A3B8', fontsize=9)
ax_line.set_ylabel('Effective potential',
                   color='#94A3B8', fontsize=9)
ax_line.tick_params(colors='#94A3B8', labelsize=8)
for sp in ['bottom', 'left']:
    ax_line.spines[sp].set_color('#334155')
for sp in ['top', 'right']:
    ax_line.spines[sp].set_visible(False)
ax_line.grid(color='#1E293B', lw=0.6, zorder=0)

# potential along x-axis (y=0)
x_1d  = np.linspace(-xlim, xlim, 5000)
r1_1d = np.abs(x_1d - x_earth)
r2_1d = np.abs(x_1d - x_moon)
r1_1d = np.maximum(r1_1d, 0.01)
r2_1d = np.maximum(r2_1d, 0.01)

U_1d  = -((1 - mu) / r1_1d +
           mu       / r2_1d +
           0.5 * x_1d**2)

# clip for readability
U_clip_1d = np.clip(U_1d, -5, -1.2)

ax_line.plot(x_1d, U_clip_1d,
             color='#F59E0B', lw=2.0, zorder=4)

# Lagrange point markers on 1D plot
for lx, ly, name, col in lagrange_pts[:3]:  # L1, L2, L3 only
    u_val = np.clip(
        -((1-mu)/abs(lx-x_earth) +
          mu/abs(lx-x_moon) +
          0.5*lx**2), -5, -1.2)
    ax_line.plot(lx, u_val, '*',
                 color=col, ms=12, zorder=6,
                 markeredgecolor='#0D1117',
                 markeredgewidth=0.8)
    ax_line.text(lx, u_val - 0.15, name,
                 color=col, fontsize=9,
                 ha='center', fontweight='bold')

# Earth and Moon positions
ax_line.axvline(x_earth, color='#3B82F6',
                lw=1.0, ls=':', alpha=0.6)
ax_line.axvline(x_moon, color='#6B7280',
                lw=1.0, ls=':', alpha=0.6)
ax_line.text(x_earth, -1.28, 'Earth',
             color='#3B82F6', ha='center',
             fontsize=8)
ax_line.text(x_moon, -1.28, 'Moon',
             color='#6B7280', ha='center',
             fontsize=8)

# Orion now
orion_x_norm_now = x_earth + dist_from_earth_now / D_moon
ax_line.axvline(orion_x_norm_now, color='#10B981',
                lw=1.5, ls='-.', alpha=0.9)
ax_line.text(orion_x_norm_now + 0.03, -1.35,
             'Orion\nnow', color='#10B981',
             fontsize=7.5, linespacing=1.3)

ax_line.set_xlim(-xlim, xlim)
ax_line.set_ylim(-4.5, -1.2)

# L1 saddle point annotation
ax_line.annotate(
    'L1 — saddle point\n(unstable equilibrium)',
    xy=(L1_x, np.clip(
        -((1-mu)/abs(L1_x-x_earth) +
          mu/abs(L1_x-x_moon) +
          0.5*L1_x**2), -5, -1.2)),
    xytext=(L1_x - 0.35, -2.0),
    color='#10B981', fontsize=8,
    arrowprops=dict(arrowstyle='->',
                    color='#10B981', lw=1.0),
    linespacing=1.4
)

plt.suptitle(
    'Earth-Moon Gravitational Potential — Rotating Reference Frame\n'
    'Five Lagrange Points + Lunar Sphere of Influence',
    color='white', fontsize=11,
    fontweight='bold', y=1.01)

plt.savefig('artemis_gravity_potential.png', dpi=120,
            facecolor='#0D1117')
plt.show()

print("=" * 54)
print("   LAGRANGE POINTS — NORMALIZED COORDINATES")
print("=" * 54)
print(f"\n  mu = M_moon/(M_earth+M_moon) = {mu:.5f}")
print(f"\n  L1: x = {L1_x:.5f}  "
      f"({(1-L1_x)*D_moon/1e6:.3f} Mm from Moon)")
print(f"  L2: x = {L2_x:.5f}  "
      f"({(L2_x-(1-mu))*D_moon/1e6:.3f} Mm beyond Moon)")
print(f"  L3: x = {L3_x:.5f}  "
      f"(opposite Earth)")
print(f"  L4: ({L4_x:.4f}, {L4_y:.4f})  "
      f"(60° ahead of Moon)")
print(f"  L5: ({L5_x:.4f}, {L5_y:.4f})  "
      f"(60° behind Moon)")
print(f"\n  SOI radius (normalized): {soi_r_norm:.4f}")
print(f"  SOI radius (km)        : {r_SOI/1000:,.0f}")
print(f"\n  Note: L1 sits INSIDE the SOI.")
print(f"  SOI is {r_SOI/1000:,.0f} km from Moon")
print(f"  L1 is  {r_L1_from_moon/1000:,.0f} km from Moon")
print(f"  Difference: {(r_SOI-r_L1_from_moon)/1000:,.0f} km")
print("=" * 54)

# ============================================================
# Cell 5 — Gravity transition animation
# Orion approaching Moon, live gravity balance meter
# ============================================================


fig = plt.figure(figsize=(15, 8))
fig.patch.set_facecolor('#0D1117')

# three axes
ax_space = fig.add_axes([0.02, 0.12, 0.50, 0.80])  # space view
ax_meter = fig.add_axes([0.55, 0.55, 0.42, 0.38])  # gravity meter
ax_plot  = fig.add_axes([0.55, 0.08, 0.42, 0.38])  # ratio plot

# ════════════════════════════════════════════════════════════
# SPACE VIEW — Earth, Moon, boundaries, Orion
# ════════════════════════════════════════════════════════════
ax_space.set_facecolor('#060F1A')
ax_space.set_xlim(-0.15, 1.15)
ax_space.set_ylim(-0.35, 0.35)
ax_space.set_aspect('equal')
ax_space.axis('off')
ax_space.set_title(
    'Orion approaching Moon — gravity transition',
    color='white', fontsize=10, pad=8)

# stars
np.random.seed(42)
ax_space.scatter(
    np.random.uniform(-0.15, 1.15, 120),
    np.random.uniform(-0.35, 0.35, 120),
    s=0.3, color='white', alpha=0.4, zorder=0
)

# Earth
ax_space.add_patch(Circle((0, 0), 0.055,
                   color='#1B4FD8', zorder=5))
ax_space.add_patch(Circle((0, 0), 0.055,
                   color='none', ec='#3B82F6',
                   lw=0.8, alpha=0.3, zorder=6))
ax_space.text(0, -0.08, 'Earth',
              color='white', ha='center',
              fontsize=7.5, fontweight='bold')

# Moon
ax_space.add_patch(Circle((1.0, 0), 0.025,
                   color='#6B7280', zorder=5))
ax_space.text(1.0, -0.06, 'Moon',
              color='#94A3B8', ha='center',
              fontsize=7.5, fontweight='bold')

# SOI circle (around Moon, normalized)
soi_norm  = r_SOI / D_moon
l1_norm   = r_L1_from_moon / D_moon
bal_norm  = r_balance_from_moon / D_moon

theta_c = np.linspace(0, 2*np.pi, 200)
ax_space.plot(1.0 + soi_norm * np.cos(theta_c),
              soi_norm * np.sin(theta_c),
              color='#F59E0B', lw=1.2,
              ls='--', alpha=0.6, zorder=3)
ax_space.text(1.0 - soi_norm - 0.02, 0.01,
              'SOI', color='#F59E0B',
              fontsize=7, ha='right')

ax_space.plot(1.0 + l1_norm * np.cos(theta_c),
              l1_norm * np.sin(theta_c),
              color='#10B981', lw=1.0,
              ls='--', alpha=0.5, zorder=3)
ax_space.text(1.0 - l1_norm - 0.01, 0.01,
              'L1', color='#10B981',
              fontsize=7, ha='right')

ax_space.plot(1.0 + bal_norm * np.cos(theta_c),
              bal_norm * np.sin(theta_c),
              color='#EC4899', lw=0.8,
              ls='--', alpha=0.4, zorder=3)
ax_space.text(1.0 - bal_norm - 0.01, 0.01,
              'Balance', color='#EC4899',
              fontsize=7, ha='right')

# trajectory path (faint)
t_traj = np.linspace(0, 1, 300)
traj_x = t_traj
traj_y = 0.12 * np.sin(np.pi * t_traj)
ax_space.plot(traj_x, traj_y,
              color='#334155', lw=1.0,
              ls='--', alpha=0.4, zorder=2)

# dynamic elements
orion_dot, = ax_space.plot([], [], 's',
                            color='white', ms=8,
                            zorder=8,
                            markeredgecolor='#F59E0B',
                            markeredgewidth=1.0)

# gravity arrows (Earth pulls left, Moon pulls right)
earth_arrow = ax_space.annotate('',
    xy=(0, 0), xytext=(0, 0),
    arrowprops=dict(arrowstyle='->', lw=2,
                    color='#3B82F6'),
    zorder=7)
moon_arrow = ax_space.annotate('',
    xy=(0, 0), xytext=(0, 0),
    arrowprops=dict(arrowstyle='->', lw=2,
                    color='#94A3B8'),
    zorder=7)

# phase label
phase_text = ax_space.text(
    0.5, -0.28, '',
    color='white', ha='center',
    fontsize=9, fontweight='bold', zorder=8)

# boundary crossed indicators
crossed_soi = ax_space.text(
    0.5, -0.32, '',
    color='#F59E0B', ha='center',
    fontsize=8, zorder=8)

# ════════════════════════════════════════════════════════════
# GRAVITY METER — visual balance scale
# ════════════════════════════════════════════════════════════
ax_meter.set_facecolor('#0D1117')
ax_meter.set_title('Gravity balance',
                   color='white', fontsize=9, pad=6)
ax_meter.set_xlim(0, 1)
ax_meter.set_ylim(0, 1)
ax_meter.axis('off')

# meter background
ax_meter.add_patch(FancyBboxPatch(
    (0.05, 0.1), 0.9, 0.35,
    boxstyle='round,pad=0.02',
    facecolor='#1E293B', edgecolor='#334155',
    zorder=2))

# Earth side label
ax_meter.text(0.08, 0.55, 'Earth',
              color='#3B82F6', fontsize=9,
              fontweight='bold', va='center')
# Moon side label
ax_meter.text(0.92, 0.55, 'Moon',
              color='#94A3B8', fontsize=9,
              fontweight='bold', va='center',
              ha='right')

# balance line
ax_meter.plot([0.5, 0.5], [0.12, 0.55],
              color='#334155', lw=1.0,
              transform=ax_meter.transAxes,
              zorder=3)
ax_meter.text(0.5, 0.58, 'SOI',
              color='#F59E0B', fontsize=7.5,
              ha='center', transform=ax_meter.transAxes)

# dynamic meter bars
earth_bar = ax_meter.add_patch(FancyBboxPatch(
    (0.05, 0.12), 0.0, 0.30,
    boxstyle='round,pad=0.01',
    facecolor='#3B82F6', edgecolor='none',
    zorder=3))
moon_bar = ax_meter.add_patch(FancyBboxPatch(
    (0.95, 0.12), 0.0, 0.30,
    boxstyle='round,pad=0.01',
    facecolor='#6B7280', edgecolor='none',
    zorder=3))

# ratio readout
ratio_text = ax_meter.text(
    0.5, 0.75,
    'g_moon / g_earth = 0.000',
    color='white', fontsize=9,
    fontweight='bold', ha='center',
    transform=ax_meter.transAxes)

dominant_text = ax_meter.text(
    0.5, 0.88,
    'Earth dominant',
    color='#3B82F6', fontsize=10,
    fontweight='bold', ha='center',
    transform=ax_meter.transAxes)

# ════════════════════════════════════════════════════════════
# RATIO PLOT — builds over time
# ════════════════════════════════════════════════════════════
ax_plot.set_facecolor('#0D1117')
ax_plot.set_title('g_moon / g_earth ratio',
                  color='white', fontsize=9, pad=6)
ax_plot.set_xlabel('Progress toward Moon (%)',
                   color='#94A3B8', fontsize=8)
ax_plot.tick_params(colors='#94A3B8', labelsize=7)
for sp in ['bottom', 'left']:
    ax_plot.spines[sp].set_color('#334155')
for sp in ['top', 'right']:
    ax_plot.spines[sp].set_visible(False)
ax_plot.grid(color='#1E293B', lw=0.5, zorder=0)

ax_plot.axhline(1.0, color='#F59E0B',
                lw=1.2, ls='--', alpha=0.7)
ax_plot.text(2, 1.05, 'SOI (ratio=1)',
             color='#F59E0B', fontsize=7)
ax_plot.set_xlim(0, 100)
ax_plot.set_ylim(0, 8)

ratio_line, = ax_plot.plot([], [], '-',
                            color='#F59E0B',
                            lw=2.0, zorder=4)
ratio_dot,  = ax_plot.plot([], [], 'o',
                            color='#F59E0B',
                            ms=6, zorder=5)

# ════════════════════════════════════════════════════════════
# Animation parameters
# ════════════════════════════════════════════════════════════
N_FRAMES = 150
# animate from TLI to just past closest approach
progress = np.linspace(0, 1.05, N_FRAMES)

prog_t   = []
prog_rat = []

def get_position(p):
    """Get (x_norm, y_norm) along trajectory."""
    p = np.clip(p, 0, 1)
    x = p
    y = 0.12 * np.sin(np.pi * p)
    return x, y

def get_distances(p):
    """Get distance from Earth and Moon in meters."""
    p  = np.clip(p, 0, 1)
    x  = p * D_moon
    de = x                      # from Earth
    dm = D_moon - x             # from Moon
    return max(de, 1e6), max(dm, 1e6)

def get_gravity_ratio(p):
    de, dm = get_distances(p)
    g_e = GM_earth / de**2
    g_m = GM_moon  / dm**2
    return g_m / g_e, g_e, g_m

def init():
    orion_dot.set_data([], [])
    ratio_line.set_data([], [])
    ratio_dot.set_data([], [])
    phase_text.set_text('')
    crossed_soi.set_text('')
    ratio_text.set_text('g_moon / g_earth = 0.000')
    dominant_text.set_text('Earth dominant')
    dominant_text.set_color('#3B82F6')
    prog_t.clear()
    prog_rat.clear()
    return (orion_dot, ratio_line, ratio_dot,
            phase_text, crossed_soi,
            ratio_text, dominant_text,
            earth_bar, moon_bar)

def update(frame):
    p   = progress[frame]
    pc  = min(p, 1.0)   # clamp for distance calc
    pct = p * 100

    # position
    x, y = get_position(pc)
    orion_dot.set_data([x], [y])

    # distances and gravity
    de, dm = get_distances(pc)
    ratio, g_e, g_m = get_gravity_ratio(pc)

    # gravity arrows — point toward each body
    arrow_scale = 0.08
    e_len = min(g_e / (GM_earth / D_moon**2) * arrow_scale,
                0.25)
    m_len = min(g_m / (GM_earth / D_moon**2) * arrow_scale,
                0.25)

    # update arrows via set_position
    earth_arrow.xy     = (x - e_len, y)
    earth_arrow.xytext = (x, y)
    moon_arrow.xy      = (x + m_len, y)
    moon_arrow.xytext  = (x, y)

    # gravity meter bars
    max_w = 0.40
    e_w   = min(g_e / (g_e + g_m) * max_w * 2, max_w)
    m_w   = min(g_m / (g_e + g_m) * max_w * 2, max_w)
    earth_bar.set_width(e_w)
    moon_bar.set_x(0.95 - m_w)
    moon_bar.set_width(m_w)

    # ratio readout
    ratio_text.set_text(
        f'g_moon / g_earth = {ratio:.4f}')

    # dominant body
    if ratio < 1.0:
        dominant_text.set_text('Earth dominant')
        dominant_text.set_color('#3B82F6')
        orion_dot.set_markeredgecolor('#3B82F6')
    elif ratio < 1.05:
        dominant_text.set_text('⟵ SOI CROSSING ⟶')
        dominant_text.set_color('#F59E0B')
        orion_dot.set_markeredgecolor('#F59E0B')
    else:
        dominant_text.set_text('Moon dominant')
        dominant_text.set_color('#94A3B8')
        orion_dot.set_markeredgecolor('#94A3B8')

    # phase label
    if p < soi_norm:
        phase = 'Outbound coast — Earth dominant'
        col   = '#3B82F6'
    elif p < l1_norm:
        phase = 'Inside SOI — Moon dominant'
        col   = '#F59E0B'
    elif p < bal_norm:
        phase = 'Past L1 — deep lunar influence'
        col   = '#10B981'
    elif p <= 1.0:
        phase = 'Past gravity balance — falling toward Moon'
        col   = '#EC4899'
    else:
        phase = 'Post flyby — receding'
        col   = '#94A3B8'

    phase_text.set_text(phase)
    phase_text.set_color(col)

    # boundary crossed text
    crossings = []
    if p * D_moon >= D_moon - r_SOI:
        crossings.append('SOI ✓')
    if p * D_moon >= D_moon - r_L1_from_moon:
        crossings.append('L1 ✓')
    if p * D_moon >= D_moon - r_balance_from_moon:
        crossings.append('Balance ✓')
    crossed_soi.set_text(
        '  '.join(crossings) if crossings else '')

    # ratio plot
    prog_t.append(pct)
    prog_rat.append(min(ratio, 8))
    ratio_line.set_data(prog_t, prog_rat)
    ratio_dot.set_data([pct], [min(ratio, 8)])

    # color ratio line by phase
    ratio_line.set_color(col)
    ratio_dot.set_color(col)

    return (orion_dot, ratio_line, ratio_dot,
            phase_text, crossed_soi,
            ratio_text, dominant_text,
            earth_bar, moon_bar)

anim5 = animation.FuncAnimation(
    fig, update, frames=N_FRAMES,
    init_func=init, interval=60, blit=True
)

plt.suptitle(
    'Artemis II — Gravity Transition: Earth to Moon',
    color='white', fontsize=11,
    fontweight='bold', y=1.0)

anim5.save('artemis_gravity_animation.gif',
           writer='pillow', fps=25, dpi=100,
           savefig_kwargs={'facecolor': '#0D1117'})
print("Saved: artemis_gravity_animation.gif")

HTML(anim5.to_jshtml())

# ============================================================
# Cell 6 — Day 5 Summary Dashboard
# Where Earth Ends — complete gravity transition analysis
# Code Beyond the Earth | April 5, 2026
# ============================================================

fig = plt.figure(figsize=(20, 12))
fig.patch.set_facecolor('#0D1117')
ax  = fig.add_axes([0, 0, 1, 1])
ax.set_xlim(0, 20)
ax.set_ylim(0, 12)
ax.axis('off')
ax.set_facecolor('#0D1117')

# ── helpers ───────────────────────────────────────────────────
def card(x, y, w, h, fc='#1E293B', ec='#334155', lw=0.8):
    ax.add_patch(FancyBboxPatch(
        (x, y), w, h,
        boxstyle='round,pad=0.08',
        facecolor=fc, edgecolor=ec,
        linewidth=lw, zorder=2
    ))

def txt(x, y, s, **kw):
    kw.setdefault('color', 'white')
    kw.setdefault('fontsize', 10)
    kw.setdefault('zorder', 4)
    kw.setdefault('va', 'center')
    ax.text(x, y, s, **kw)

def hline(x0, x1, y, col='#1E293B', lw=0.7):
    ax.plot([x0, x1], [y, y],
            color=col, lw=lw, zorder=3)

def fmt_km(km):
    return f'{km:,.0f} km'

# ════════════════════════════════════════════════════════════
# HEADER
# ════════════════════════════════════════════════════════════
card(0.25, 10.7, 19.5, 1.1, fc='#0F172A', ec='#1E3A5C')
txt(10.0, 11.35,
    'DAY 5 — WHERE EARTH ENDS: '
    'LUNAR SPHERE OF INFLUENCE & L1 LAGRANGE POINT',
    fontsize=15, fontweight='bold', ha='center')
txt(10.0, 10.97,
    f'Code Beyond the Earth  ·  MET T+{MET_NOW:.1f}h  ·  '
    f'SOI crossing in ~{MET_SOI - MET_NOW:.1f}h  ·  '
    f'April 5, 2026',
    fontsize=9, ha='center', color='#475569')

# ════════════════════════════════════════════════════════════
# ROW 1 — five metric cards
# ════════════════════════════════════════════════════════════
metrics = [
    ('SOI radius',
     f'{r_SOI/1000:,.0f}', 'km from Moon',   '#F59E0B'),
    ('L1 distance',
     f'{r_L1_from_moon/1000:,.0f}', 'km from Moon', '#10B981'),
    ('Gravity balance',
     f'{r_balance_from_moon/1000:,.0f}', 'km from Moon', '#EC4899'),
    ('SOI crossing',
     'Apr 6  04:41', 'UTC',              '#F59E0B'),
    ('Mass ratio',
     '81.3×', 'Earth / Moon',            '#3B82F6'),
]
card_w = 3.6
for i, (label, val, unit, col) in enumerate(metrics):
    cx = 0.25 + i * (card_w + 0.25)
    card(cx, 9.25, card_w, 1.25, fc='#0F172A', ec=col)
    txt(cx + card_w/2, 10.15, label,
        fontsize=8.5, color='#64748B', ha='center')
    txt(cx + card_w/2, 9.78, val,
        fontsize=16, fontweight='bold',
        color=col, ha='center')
    txt(cx + card_w/2, 9.42, unit,
        fontsize=8, color='#475569', ha='center')

# ════════════════════════════════════════════════════════════
# ROW 2 — three cards
# ════════════════════════════════════════════════════════════
CW, CGap = 6.2, 0.25
CY0, CH  = 5.05, 4.0
CY1      = CY0 + CH
cx1 = 0.25
cx2 = cx1 + CW + CGap
cx3 = cx2 + CW + CGap

card(cx1, CY0, CW, CH)
card(cx2, CY0, CW, CH)
card(cx3, CY0, CW, CH)

# ── CARD 1: three boundaries explained ───────────────────────
txt(cx1 + CW/2, CY1 - 0.3,
    'Three boundaries — one approach',
    fontsize=9.5, fontweight='bold', ha='center')

boundaries_explained = [
    ('Sphere of Influence',
     f'{r_SOI/1000:,.0f} km from Moon',
     "Laplace's formula: r = D·(M_moon/M_earth)^(2/5)\n"
     "Mission planning boundary — patched conic\n"
     "approximation switches here",
     '#F59E0B'),
    ('L1 Lagrange Point',
     f'{r_L1_from_moon/1000:,.0f} km from Moon',
     "Rotating frame force balance = 0\n"
     "True gravitational saddle point\n"
     "Unstable — sits INSIDE the SOI",
     '#10B981'),
    ('Gravity Balance',
     f'{r_balance_from_moon/1000:,.0f} km from Moon',
     "Raw |F_earth| = |F_moon|, no rotation\n"
     "Deepest inside — least operationally\n"
     "relevant of the three",
     '#EC4899'),
]

row_h = 1.12
for j, (name, dist, desc, col) in \
        enumerate(boundaries_explained):
    ry = CY1 - 1.0 - j * row_h
    txt(cx1 + 0.25, ry, name,
        fontsize=9, color=col,
        fontweight='bold', ha='left')
    txt(cx1 + 0.25, ry - 0.25, dist,
        fontsize=8, color='white', ha='left')
    for k, line in enumerate(desc.split('\n')):
        txt(cx1 + 0.25, ry - 0.48 - k*0.18,
            line, fontsize=7.2,
            color='#475569', ha='left')
    if j < 2:
        hline(cx1 + 0.2, cx1 + CW - 0.2,
              ry - 0.95, col='#1E293B')

# bottom insight
card(cx1 + 0.2, CY0 + 0.18, CW - 0.4, 0.75,
     fc='#0F172A', ec='#334155')
txt(cx1 + CW/2, CY0 + 0.56,
    'All three are different. SOI is largest.\n'
    'L1 is inside SOI. Balance is deepest.',
    fontsize=8.5, ha='center', color='#64748B',
    linespacing=1.5)

# ── CARD 2: crossing timeline ─────────────────────────────────
txt(cx2 + CW/2, CY1 - 0.3,
    'Boundary crossing timeline — April 6',
    fontsize=9.5, fontweight='bold', ha='center')

timeline_events = [
    ('TLI burn',
     f'T+{MET_TLI:.1f}h', 'Apr 2, 23:49 UTC',
     '#3B82F6'),
    ('SOI crossing',
     f'T+{MET_SOI:.1f}h', 'Apr 6, 04:41 UTC  ← NASA',
     '#F59E0B'),
    ('L1 Lagrange point',
     f'T+{l1_cross_met:.1f}h', 'Apr 6, 07:56 UTC',
     '#10B981'),
    ('Gravity balance',
     f'T+{bal_cross_met:.1f}h', 'Apr 6, 11:24 UTC',
     '#EC4899'),
    ('Closest approach',
     f'T+{MET_FLYBY:.1f}h', 'Apr 6, 18:45 UTC',
     '#EC4899'),
]
for j, (name, met_str, utc, col) in \
        enumerate(timeline_events):
    ry = CY1 - 0.85 - j * 0.60

    # dot
    ax.plot(cx2 + 0.35, ry, 'o',
            color=col, ms=8, zorder=5,
            markeredgecolor='#0D1117',
            markeredgewidth=0.8)

    # connector line
    if j < len(timeline_events) - 1:
        ax.plot([cx2 + 0.35, cx2 + 0.35],
                [ry - 0.08, ry - 0.52],
                color='#334155', lw=0.8,
                zorder=3)

    txt(cx2 + 0.55, ry + 0.06, name,
        fontsize=8.5, color=col,
        fontweight='bold', ha='left')
    txt(cx2 + 0.55, ry - 0.14,
        f'{met_str}  ·  {utc}',
        fontsize=7.5, color='#475569', ha='left')

# now marker
now_ry = CY1 - 0.85 - 0 * 0.60 - \
    (MET_NOW - MET_TLI) / \
    (MET_FLYBY - MET_TLI) * \
    (len(timeline_events) - 1) * 0.60
card(cx2 + 0.2, CY0 + 0.18, CW - 0.4, 0.75,
     fc='#0A1628', ec='#10B981')
txt(cx2 + CW/2, CY0 + 0.56,
    f'Now: T+{MET_NOW:.1f}h  ·  '
    f'{MET_SOI - MET_NOW:.1f}h to SOI crossing',
    fontsize=8.5, ha='center', color='#10B981',
    fontweight='bold')

# ── CARD 3: Lagrange points reference ────────────────────────
txt(cx3 + CW/2, CY1 - 0.3,
    'All five Lagrange points',
    fontsize=9.5, fontweight='bold', ha='center')

lagrange_data = [
    ('L1', f'{r_L1_from_moon/1000:,.0f} km from Moon',
     'Between Earth & Moon — unstable saddle\n'
     'Gateway to lunar orbit insertion',
     '#10B981'),
    ('L2', f'{(r_L1/1000 - D_moon/1000)*-1:,.0f} km beyond Moon',
     'Behind Moon — unstable saddle\n'
     'Lunar far side relay satellites',
     '#3B82F6'),
    ('L3', 'Opposite Earth',
     'Behind Earth — unstable saddle\n'
     'Theoretically perfect, practically useless',
     '#F59E0B'),
    ('L4', '60° ahead of Moon',
     'Equilateral triangle — STABLE\n'
     'Trojan asteroids accumulate here',
     '#EC4899'),
    ('L5', '60° behind Moon',
     'Equilateral triangle — STABLE\n'
     'Mirror of L4, equally stable',
     '#EC4899'),
]

row_h3 = 0.70
for j, (name, dist, desc, col) in \
        enumerate(lagrange_data):
    ry = CY1 - 0.85 - j * row_h3

    txt(cx3 + 0.25, ry,
        f'{name}  —  {dist}',
        fontsize=8.5, color=col,
        fontweight='bold', ha='left')
    for k, line in enumerate(desc.split('\n')):
        txt(cx3 + 0.25, ry - 0.20 - k*0.16,
            line, fontsize=7.2,
            color='#475569', ha='left')
    if j < len(lagrange_data) - 1:
        hline(cx3 + 0.2, cx3 + CW - 0.2,
              ry - 0.52, col='#1E293B')

card(cx3 + 0.2, CY0 + 0.18, CW - 0.4, 0.75,
     fc='#0F172A', ec='#334155')
txt(cx3 + CW/2, CY0 + 0.56,
    'L1, L2, L3 unstable — any nudge escapes.\n'
    'L4, L5 stable — objects orbit for eons.',
    fontsize=8.5, ha='center', color='#64748B',
    linespacing=1.5)

# ════════════════════════════════════════════════════════════
# ROW 3 — gravity ratio strip
# ════════════════════════════════════════════════════════════
card(0.25, 0.85, 19.5, 4.0)
txt(10.0, 4.62,
    'Moon/Earth gravity ratio along Orion trajectory',
    fontsize=10, fontweight='bold', ha='center')

# embed mini axes for the ratio plot
ax_strip = fig.add_axes([
    0.04, 0.085/1, 0.92, 0.27/1
])
ax_strip.set_facecolor('#0D1117')
ax_strip.tick_params(colors='#475569', labelsize=7)
for sp in ['bottom', 'left']:
    ax_strip.spines[sp].set_color('#334155')
for sp in ['top', 'right']:
    ax_strip.spines[sp].set_visible(False)
ax_strip.grid(color='#1E293B', lw=0.5, zorder=0)

# recompute ratio along normalized distance
x_norm = np.linspace(0.01, 0.99, 2000)
ratio_arr = np.zeros_like(x_norm)
for i, xn in enumerate(x_norm):
    de = xn * D_moon
    dm = (1 - xn) * D_moon
    ge = GM_earth / de**2
    gm = GM_moon  / dm**2
    ratio_arr[i] = gm / ge

# color by phase
soi_xn  = 1 - r_SOI / D_moon
l1_xn   = 1 - r_L1_from_moon / D_moon
bal_xn  = 1 - r_balance_from_moon / D_moon

ax_strip.fill_between(x_norm * 100, ratio_arr, 1,
                      where=(ratio_arr >= 1),
                      color='#94A3B8', alpha=0.15)
ax_strip.fill_between(x_norm * 100, ratio_arr, 1,
                      where=(ratio_arr < 1),
                      color='#3B82F6', alpha=0.10)

ax_strip.plot(x_norm * 100,
              np.clip(ratio_arr, 0, 6),
              color='#F59E0B', lw=2.0, zorder=4)
ax_strip.axhline(1.0, color='#F59E0B',
                 lw=1.2, ls='--', alpha=0.7)

# boundary markers
for xn, col, label in [
    (soi_xn,  '#F59E0B', 'SOI'),
    (l1_xn,   '#10B981', 'L1'),
    (bal_xn,  '#EC4899', 'Balance'),
]:
    ax_strip.axvline(xn * 100, color=col,
                     lw=1.2, ls='--', alpha=0.7)
    ax_strip.text(xn * 100 + 0.5, 5.2, label,
                  color=col, fontsize=7.5,
                  fontweight='bold')

# Orion now
orion_xn = dist_from_earth_now / D_moon
orion_ratio = ratio_arr[np.argmin(
    np.abs(x_norm - orion_xn))]
ax_strip.axvline(orion_xn * 100, color='#10B981',
                 lw=1.5, ls='-.', alpha=0.9)
ax_strip.plot(orion_xn * 100,
              min(orion_ratio, 6), 'o',
              color='#10B981', ms=7, zorder=6,
              markeredgecolor='#0D1117',
              markeredgewidth=0.8)
ax_strip.text(orion_xn * 100 + 0.5, 4.0,
              f'Now\n{orion_ratio:.4f}',
              color='#10B981', fontsize=7.5,
              linespacing=1.3)

ax_strip.text(30, 4.5, 'Earth dominant',
              color='#3B82F6', fontsize=8,
              style='italic', alpha=0.7)
ax_strip.text(92, 4.5, 'Moon dominant',
              color='#94A3B8', fontsize=8,
              style='italic', alpha=0.7,
              ha='right')

ax_strip.set_xlim(0, 100)
ax_strip.set_ylim(0, 6)
ax_strip.set_xlabel(
    'Position along Earth-Moon line (%)',
    color='#475569', fontsize=8)
ax_strip.set_ylabel('g_moon / g_earth',
                    color='#475569', fontsize=8)

# ════════════════════════════════════════════════════════════
# FOOTER
# ════════════════════════════════════════════════════════════
card(0.25, 0.12, 19.5, 0.62, fc='#0F172A', ec='#1E293B')
now_str = datetime.now(timezone.utc).strftime(
    '%B %d, %Y  %H:%M UTC')
txt(10.0, 0.44,
    f'Code Beyond the Earth  ·  '
    f'codebeyondtheearth.hashnode.dev  ·  '
    f'Generated {now_str}  ·  '
    f'Sources: NASA Artemis II  ·  '
    f'Laplace SOI formula  ·  JPL Horizons',
    fontsize=8.5, ha='center', color='#475569')

plt.savefig('artemis_day5_summary.png', dpi=150,
            facecolor='#0D1117', bbox_inches='tight')
plt.show()

print("=" * 58)
print("   DAY 5 COMPLETE — WHERE EARTH ENDS")
print("=" * 58)
print()
print("  Cells completed:")
print("    Cell 1  Constants + SOI + L1 + gravity balance")
print("    Cell 2  Gravity field along Earth-Moon line")
print("    Cell 3  Orion trajectory + boundary crossings")
print("    Cell 4  2D potential field + Lagrange points")
print("    Cell 5  Gravity transition animation (GIF)")
print("    Cell 6  This summary dashboard")
print()
print("  Three boundaries:")
print(f"    SOI          : {r_SOI/1000:,.0f} km from Moon")
print(f"    L1 point     : {r_L1_from_moon/1000:,.0f} km from Moon")
print(f"    Gravity bal. : {r_balance_from_moon/1000:,.0f} km from Moon")
print()
print("  Crossing times (April 6):")
print(f"    SOI          : 04:41 UTC  (NASA confirmed ✓)")
print(f"    L1           : 07:56 UTC")
print(f"    Balance      : 11:24 UTC")
print(f"    Closest appr.: 18:45 UTC")
print()
print("  Current state:")
print(f"    From Moon    : {dist_from_moon_now/1000:,.0f} km")
print(f"    Hours to SOI : {MET_SOI - MET_NOW:.1f}h")
print(f"    Gravity ratio: {orion_ratio:.5f}  "
      f"(Earth {1/orion_ratio:.0f}× stronger)")
print()
print("  Saved files:")
print("    artemis_gravity_field.png")
print("    artemis_boundary_crossings.png")
print("    artemis_gravity_potential.png")
print("    artemis_gravity_animation.gif")
print("    artemis_day5_summary.png  ← blog header")
print("=" * 58)