# -*- coding: utf-8 -*-
"""the_long_way_to_home.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mrzpfdyFZ_gRrTwRS_Sdvipg08t0BUfJ
"""

# ============================================================
# Day 8 — The Long Way Home
# Return trajectory + Apollo 13 comparison
# Code Beyond the Earth | April 8, 2026
# ============================================================

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from matplotlib.patches import FancyBboxPatch
from datetime import datetime, timezone, timedelta

# ── Physical constants ────────────────────────────────────────
GM_earth  = 3.986004418e14   # m³/s²
GM_moon   = 4.902800066e12   # m³/s²
G         = 6.674e-11
M_earth   = GM_earth / G
M_moon    = GM_moon  / G
R_earth   = 6_371            # km
R_moon    = 1_737            # km
D_moon    = 384_400          # km
C_KMS     = 299_792.458      # km/s

# ── Artemis II timeline ───────────────────────────────────────
AII_LAUNCH   = datetime(2026, 4,  1, 22, 35, tzinfo=timezone.utc)
AII_TLI      = datetime(2026, 4,  2, 23, 49, tzinfo=timezone.utc)
AII_SOI_IN   = datetime(2026, 4,  6,  4, 41, tzinfo=timezone.utc)
AII_FLYBY    = datetime(2026, 4,  6, 23,  2, tzinfo=timezone.utc)
AII_MAX_DIST = datetime(2026, 4,  6, 23,  7, tzinfo=timezone.utc)
AII_SOI_OUT  = datetime(2026, 4,  7, 12,  0, tzinfo=timezone.utc)
AII_TCB1     = datetime(2026, 4,  7,  0,  3, tzinfo=timezone.utc)
AII_SPLASH   = datetime(2026, 4, 10,  0,  7, tzinfo=timezone.utc)

# ── Apollo 13 timeline ────────────────────────────────────────
AP13_LAUNCH   = datetime(1970, 4, 11, 19, 13, tzinfo=timezone.utc)
AP13_TLI      = datetime(1970, 4, 11, 22, 53, tzinfo=timezone.utc)
AP13_ACCIDENT = datetime(1970, 4, 13, 23,  8, tzinfo=timezone.utc)
AP13_FLYBY    = datetime(1970, 4, 15,  0,  0, tzinfo=timezone.utc)
AP13_MAX_DIST = datetime(1970, 4, 15,  0, 21, tzinfo=timezone.utc)
AP13_SPLASH   = datetime(1970, 4, 17, 18,  7, tzinfo=timezone.utc)

def met_hours(event, launch):
    """Mission elapsed time in hours."""
    return (event - launch).total_seconds() / 3600

# ── Key mission parameters ────────────────────────────────────
AII_MAX_KM    = 406_771
AII_PERIGEE   = 185
AII_CLOSE_KM  = 6_540
AII_DURATION  = met_hours(AII_SPLASH,  AII_LAUNCH)

AP13_MAX_KM   = 400_171
AP13_CLOSE_KM = 252
AP13_DURATION = met_hours(AP13_SPLASH, AP13_LAUNCH)

# ── Return correction burn (Day 7) ────────────────────────────
TCB1_DURATION_S = 15
TCB1_DV_FPS     = 1.6
TCB1_DV_MS      = TCB1_DV_FPS * 0.3048
TCB1_DV_KMS     = TCB1_DV_MS / 1000

# ── Reentry parameters ────────────────────────────────────────
REENTRY_V_MPH = 25_000
REENTRY_V_MS  = REENTRY_V_MPH * 1.60934 * 1000 / 3600
SPLASH_V_MPH  = 17
SPLASH_V_MS   = SPLASH_V_MPH * 0.44704
HEAT_SHIELD_C = 2_760

# ── Trajectory builder ────────────────────────────────────────
def build_trajectory(
        t_launch, t_tli, t_flyby,
        t_splash, max_km, close_km,
        n_pts=3000):
    t_total = met_hours(t_splash, t_launch)
    t_tli_h = met_hours(t_tli,    t_launch)
    t_fly_h = met_hours(t_flyby,  t_launch)
    t_max_h = t_fly_h + 0.08

    t = np.linspace(0, t_total, n_pts)
    d = np.zeros_like(t)

    for i, ti in enumerate(t):
        if ti < t_tli_h:
            d[i] = 185
        elif ti < t_fly_h:
            frac  = (ti - t_tli_h) / \
                    (t_fly_h - t_tli_h)
            ease  = 3*frac**2 - 2*frac**3
            d[i]  = 185 + (max_km - 185) * ease
        elif ti < t_max_h:
            frac  = (ti - t_fly_h) / \
                    (t_max_h - t_fly_h)
            d[i]  = max_km - \
                    (max_km - close_km) * \
                    np.sin(frac * np.pi * 0.5)
        else:
            frac  = (ti - t_max_h) / \
                    (t_total - t_max_h)
            ease  = frac**1.8
            d[i]  = max_km * (1 - ease) + \
                    185 * ease
    return t, d

t_a2,   d_a2   = build_trajectory(
    AII_LAUNCH,  AII_TLI,  AII_FLYBY,
    AII_SPLASH,  AII_MAX_KM, AII_CLOSE_KM)

t_ap13, d_ap13 = build_trajectory(
    AP13_LAUNCH, AP13_TLI, AP13_FLYBY,
    AP13_SPLASH, AP13_MAX_KM, AP13_CLOSE_KM)

# ── Mission status ────────────────────────────────────────────
now_utc          = datetime.now(timezone.utc)
mission_complete = now_utc >= AII_SPLASH

if mission_complete:
    # post-splashdown — retrospective analysis
    met_display    = AII_DURATION
    status_str     = "SPLASHDOWN COMPLETE ✓"
    d_display      = 0.0
    v_display      = SPLASH_V_MS / 1000   # km/s
    hrs_remaining  = 0.0
else:
    met_display    = met_hours(now_utc, AII_LAUNCH)
    met_display    = max(0, met_display)
    d_display      = float(np.interp(
                        met_display, t_a2, d_a2))
    # vis-viva velocity
    r_m            = d_display * 1000
    a_m            = (AII_MAX_KM + R_earth) * \
                     1000 / 2  # rough semi-major axis
    v_sq           = GM_earth * \
                     (2/r_m - 1/a_m)
    v_display      = max(0, np.sqrt(v_sq)) / 1000
    hrs_remaining  = met_hours(AII_SPLASH, now_utc)
    status_str     = "Return coast in progress"

# ── Print summary ─────────────────────────────────────────────
print("=" * 62)
print("   DAY 8 — THE LONG WAY HOME")
print("   Return trajectory + Apollo 13 comparison")
print("=" * 62)
print()
print("  ── ARTEMIS II ──────────────────────────────────────")
print(f"    Launch        : Apr 1,  22:35 UTC")
print(f"    TLI burn      : Apr 2,  23:49 UTC  "
      f"(T+{met_hours(AII_TLI,AII_LAUNCH):.1f}h)")
print(f"    SOI entry     : Apr 6,  04:41 UTC  "
      f"(T+{met_hours(AII_SOI_IN,AII_LAUNCH):.1f}h)")
print(f"    Lunar flyby   : Apr 6,  23:02 UTC  "
      f"(T+{met_hours(AII_FLYBY,AII_LAUNCH):.1f}h)")
print(f"    Max distance  : {AII_MAX_KM:,} km  "
      f"(Apr 6, 23:07 UTC)")
print(f"    TCB-1 burn    : 15 s  ·  "
      f"{TCB1_DV_FPS} ft/s  ·  "
      f"{TCB1_DV_MS:.3f} m/s")
print(f"    Splashdown    : Apr 10, 00:07 UTC  "
      f"(T+{AII_DURATION:.1f}h)")
print()
print("  ── APOLLO 13 ───────────────────────────────────────")
print(f"    Launch        : Apr 11, 19:13 UTC (1970)")
print(f"    TLI burn      : Apr 11, 22:53 UTC  "
      f"(T+{met_hours(AP13_TLI,AP13_LAUNCH):.1f}h)")
print(f"    O2 explosion  : Apr 13, 23:08 UTC  "
      f"(T+{met_hours(AP13_ACCIDENT,AP13_LAUNCH):.1f}h)")
print(f"    Lunar flyby   : Apr 15, 00:00 UTC  "
      f"(T+{met_hours(AP13_FLYBY,AP13_LAUNCH):.1f}h)")
print(f"    Max distance  : {AP13_MAX_KM:,} km")
print(f"    Closest Moon  : {AP13_CLOSE_KM} km  "
      f"(Artemis II: {AII_CLOSE_KM:,} km)")
print(f"    Splashdown    : Apr 17, 18:07 UTC  "
      f"(T+{AP13_DURATION:.1f}h)")
print()
print("  ── COMPARISON ──────────────────────────────────────")
rows = [
    ('Max distance',
     f'{AP13_MAX_KM:,} km',
     f'{AII_MAX_KM:,} km',
     f'+{AII_MAX_KM-AP13_MAX_KM:,} km'),
    ('Closest Moon approach',
     f'{AP13_CLOSE_KM} km',
     f'{AII_CLOSE_KM:,} km',
     f'{AII_CLOSE_KM/AP13_CLOSE_KM:.0f}× further'),
    ('Mission duration',
     f'{AP13_DURATION:.1f}h',
     f'{AII_DURATION:.1f}h',
     f'{AP13_DURATION-AII_DURATION:.1f}h shorter'),
    ('Free-return arc',
     'yes — emergency',
     'yes — by design',
     '56 years apart'),
    ('Purpose',
     'Survive accident',
     'Test spacecraft',
     'Same physics'),
    ('TCB delta-v',
     '860 m/s (PC-2)',
     f'{TCB1_DV_MS:.3f} m/s',
     'Apollo needed much more'),
]
print(f"    {'Parameter':<24} {'Apollo 13':<22} "
      f"{'Artemis II':<22} {'Δ'}")
print(f"    {'-'*24} {'-'*22} {'-'*22} {'-'*20}")
for label, ap13_val, a2_val, delta in rows:
    print(f"    {label:<24} {ap13_val:<22} "
          f"{a2_val:<22} {delta}")
print()
print("  ── MISSION STATUS ──────────────────────────────────")
print(f"    {status_str}")
if mission_complete:
    print(f"    Splashdown     : Apr 10, 00:07 UTC")
    print(f"    Recovery ship  : USS John P. Murtha")
    print(f"    Duration       : {AII_DURATION:.1f}h "
          f"= {AII_DURATION/24:.2f} days")
    print(f"    Total distance : ~695,081 miles")
    print()
    print("    This notebook is retrospective —")
    print("    the trajectory below is what happened,")
    print("    not a prediction.")
else:
    print(f"    MET            : T+{met_display:.1f}h")
    print(f"    Distance       : {d_display:,.0f} km")
    print(f"    Est. velocity  : {v_display:.3f} km/s")
    print(f"    Hours to splash: {hrs_remaining:.1f}h")
print()
print("  ── REENTRY ─────────────────────────────────────────")
print(f"    Entry velocity : {REENTRY_V_MPH:,} mph  "
      f"({REENTRY_V_MS:.0f} m/s)")
print(f"    Splashdown vel : {SPLASH_V_MPH} mph  "
      f"({SPLASH_V_MS:.1f} m/s)")
print(f"    Speed reduction: "
      f"{REENTRY_V_MPH/SPLASH_V_MPH:.0f}×")
print(f"    Heat shield    : {HEAT_SHIELD_C:,}°C peak")
print(f"    Sequence time  : ~13 minutes")
print("=" * 62)

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.patches import Circle, FancyArrowPatch
import matplotlib.patheffects as pe
from datetime import datetime, timezone, timedelta

# ── Physical constants ────────────────────────────────────────
GM_earth  = 3.986004418e14   # m³/s²
GM_moon   = 4.902800066e12   # m³/s²
G         = 6.674e-11
M_earth   = GM_earth / G
M_moon    = GM_moon  / G
R_earth   = 6_371            # km
R_moon    = 1_737            # km
D_moon    = 384_400          # km
C_KMS     = 299_792.458      # km/s

# ── Artemis II timeline ───────────────────────────────────────
AII_LAUNCH   = datetime(2026, 4,  1, 22, 35, tzinfo=timezone.utc)
AII_TLI      = datetime(2026, 4,  2, 23, 49, tzinfo=timezone.utc)
AII_SOI_IN   = datetime(2026, 4,  6,  4, 41, tzinfo=timezone.utc)
AII_FLYBY    = datetime(2026, 4,  6, 23,  2, tzinfo=timezone.utc)
AII_MAX_DIST = datetime(2026, 4,  6, 23,  7, tzinfo=timezone.utc)
AII_SOI_OUT  = datetime(2026, 4,  7, 12,  0, tzinfo=timezone.utc)
AII_TCB1     = datetime(2026, 4,  7,  0,  3, tzinfo=timezone.utc)
AII_SPLASH   = datetime(2026, 4, 10,  0,  7, tzinfo=timezone.utc)

# ── Apollo 13 timeline ────────────────────────────────────────
AP13_LAUNCH   = datetime(1970, 4, 11, 19, 13, tzinfo=timezone.utc)
AP13_TLI      = datetime(1970, 4, 11, 22, 53, tzinfo=timezone.utc)
AP13_ACCIDENT = datetime(1970, 4, 13, 23,  8, tzinfo=timezone.utc)
AP13_FLYBY    = datetime(1970, 4, 15,  0,  0, tzinfo=timezone.utc)
AP13_MAX_DIST = datetime(1970, 4, 15,  0, 21, tzinfo=timezone.utc)
AP13_SPLASH   = datetime(1970, 4, 17, 18,  7, tzinfo=timezone.utc)

def met_hours(event, launch):
    """Mission elapsed time in hours."""
    return (event - launch).total_seconds() / 3600

# ── Key mission parameters ────────────────────────────────────
AII_MAX_KM    = 406_771
AII_PERIGEE   = 185
AII_CLOSE_KM  = 6_540
AII_DURATION  = met_hours(AII_SPLASH,  AII_LAUNCH)

AP13_MAX_KM   = 400_171
AP13_CLOSE_KM = 252
AP13_DURATION = met_hours(AP13_SPLASH, AP13_LAUNCH)

# ── Return correction burn (Day 7) ────────────────────────────
TCB1_DURATION_S = 15
TCB1_DV_FPS     = 1.6
TCB1_DV_MS      = TCB1_DV_FPS * 0.3048
TCB1_DV_KMS     = TCB1_DV_MS / 1000

# ── Reentry parameters ────────────────────────────────────────
REENTRY_V_MPH = 25_000
REENTRY_V_MS  = REENTRY_V_MPH * 1.60934 * 1000 / 3600
SPLASH_V_MPH  = 17
SPLASH_V_MS   = SPLASH_V_MPH * 0.44704
HEAT_SHIELD_C = 2_760

fig, axes = plt.subplots(
    1, 3, figsize=(18, 8),
    gridspec_kw={'width_ratios': [1.2, 1.2, 0.8]}
)
fig.patch.set_facecolor('#0D1117')

# ── shared geometry ───────────────────────────────────────────
# Normalised units: Earth-Moon = 1
# Earth at origin, Moon at (1, 0)
MOON_X  = 1.0
MOON_Y  = 0.0
EARTH_X = 0.0
EARTH_Y = 0.0

def free_return_arc(
        max_dist_norm, close_norm,
        n_pts=500, y_offset=0.0,
        outbound_spread=0.18):
    """
    Generate a figure-8 free-return arc
    in normalised Earth-Moon units.
    max_dist_norm : max distance / D_moon
    close_norm    : closest Moon / D_moon
    y_offset      : vertical shift
    """
    t = np.linspace(0, 2*np.pi, n_pts)

    # outbound leg — Earth to Moon
    # parametric arc approaching Moon
    # from below (typical free-return geometry)
    t_out = np.linspace(0, np.pi, n_pts//2)

    # outbound: rises from Earth, arcs to Moon
    x_out = (MOON_X * np.sin(t_out/2)**0.7 +
             outbound_spread *
             np.sin(t_out) * 0.5)
    y_out = (outbound_spread *
             np.sin(t_out) + y_offset)

    # lunar flyby arc — loop around Moon
    # radius = closest approach
    t_fly = np.linspace(
        -np.pi * 0.6,
         np.pi * 0.6, n_pts//4)
    r_fly  = close_norm + \
             0.02 * (1 - np.cos(t_fly))
    x_fly  = MOON_X + \
             r_fly * np.cos(t_fly + np.pi)
    y_fly  = r_fly * np.sin(t_fly + np.pi) + \
             y_offset

    # return leg — Moon back to Earth
    # mirror of outbound with slight shift
    x_ret = x_out[::-1] * 0.98
    y_ret = -y_out[::-1] * 0.95

    return (np.concatenate([x_out, x_fly, x_ret]),
            np.concatenate([y_out, y_fly, y_ret]))

# ── normalise ─────────────────────────────────────────────────
D = D_moon  # km

a2_max_n   = AII_MAX_KM   / D
a2_close_n = AII_CLOSE_KM / D
ap_max_n   = AP13_MAX_KM  / D
ap_close_n = AP13_CLOSE_KM / D

# ════════════════════════════════════════
# PANEL 1: Artemis II trajectory
# ════════════════════════════════════════
ax1 = axes[0]
ax1.set_facecolor('#060F1A')
ax1.set_aspect('equal')
ax1.set_xlim(-0.15, 1.25)
ax1.set_ylim(-0.35, 0.35)
ax1.axis('off')
ax1.set_title('Artemis II\nfree-return trajectory',
              color='#10B981', fontsize=11,
              fontweight='bold', pad=8)

# stars
np.random.seed(1)
ax1.scatter(
    np.random.uniform(-0.15, 1.25, 80),
    np.random.uniform(-0.35, 0.35, 80),
    s=0.2, color='white', alpha=0.4)

# Earth
ax1.add_patch(Circle(
    (EARTH_X, EARTH_Y), 0.05,
    color='#1B4FD8', zorder=5))
ax1.add_patch(Circle(
    (EARTH_X, EARTH_Y), 0.05,
    color='none', ec='#3B82F6',
    lw=0.8, alpha=0.4, zorder=6))
ax1.text(EARTH_X, -0.09, 'Earth',
         color='white', ha='center',
         fontsize=8, fontweight='bold')

# Moon
ax1.add_patch(Circle(
    (MOON_X, MOON_Y), 0.018,
    color='#6B7280', zorder=5))
ax1.text(MOON_X, -0.06, 'Moon',
         color='#94A3B8', ha='center',
         fontsize=8)

# trajectory
x_a2, y_a2 = free_return_arc(
    a2_max_n, a2_close_n,
    outbound_spread=0.18)

# split into outbound and return
mid = len(x_a2) // 2
ax1.plot(x_a2[:mid], y_a2[:mid],
         color='#10B981', lw=2.5,
         zorder=4, label='Outbound')
ax1.plot(x_a2[mid:], y_a2[mid:],
         color='#3B82F6', lw=2.5,
         ls='--', zorder=4,
         label='Return')

# direction arrows
for frac, col in [(0.25, '#10B981'),
                   (0.75, '#3B82F6')]:
    idx = int(frac * len(x_a2))
    if idx < len(x_a2) - 1:
        ax1.annotate('',
                     xy=(x_a2[idx+3], y_a2[idx+3]),
                     xytext=(x_a2[idx], y_a2[idx]),
                     arrowprops=dict(
                         arrowstyle='->',
                         color=col, lw=1.5))

# max distance annotation
max_idx = np.argmax(
    np.sqrt((x_a2-MOON_X)**2 +
            y_a2**2))
ax1.plot(x_a2[max_idx],
         y_a2[max_idx],
         'o', color='#F59E0B',
         ms=7, zorder=7,
         markeredgecolor='#0D1117',
         markeredgewidth=0.8)
ax1.text(x_a2[max_idx] + 0.02,
         y_a2[max_idx] + 0.05,
         f'Max: {AII_MAX_KM:,} km',
         color='#F59E0B', fontsize=7.5,
         fontweight='bold')

# closest approach
ax1.plot(x_a2[len(x_a2)//4],
         y_a2[len(x_a2)//4],
         's', color='#EC4899',
         ms=6, zorder=7,
         markeredgecolor='#0D1117',
         markeredgewidth=0.8)
ax1.text(MOON_X - 0.12, 0.07,
         f'Closest:\n{AII_CLOSE_KM:,} km',
         color='#EC4899', fontsize=7,
         linespacing=1.4)

# splashdown
ax1.plot(0.04, -0.02, 'v',
         color='#10B981', ms=8,
         zorder=7)
ax1.text(0.10, -0.04,
         'Splashdown\nApr 10',
         color='#10B981', fontsize=7,
         linespacing=1.3)

ax1.legend(facecolor='#1E293B',
           edgecolor='#334155',
           labelcolor='white',
           fontsize=8, loc='lower right')

# ════════════════════════════════════════
# PANEL 2: Apollo 13 trajectory
# ════════════════════════════════════════
ax2 = axes[1]
ax2.set_facecolor('#060F1A')
ax2.set_aspect('equal')
ax2.set_xlim(-0.15, 1.25)
ax2.set_ylim(-0.35, 0.35)
ax2.axis('off')
ax2.set_title('Apollo 13\nfree-return trajectory',
              color='#EF4444', fontsize=11,
              fontweight='bold', pad=8)

np.random.seed(2)
ax2.scatter(
    np.random.uniform(-0.15, 1.25, 80),
    np.random.uniform(-0.35, 0.35, 80),
    s=0.2, color='white', alpha=0.4)

# Earth
ax2.add_patch(Circle(
    (EARTH_X, EARTH_Y), 0.05,
    color='#1B4FD8', zorder=5))
ax2.add_patch(Circle(
    (EARTH_X, EARTH_Y), 0.05,
    color='none', ec='#3B82F6',
    lw=0.8, alpha=0.4, zorder=6))
ax2.text(EARTH_X, -0.09, 'Earth',
         color='white', ha='center',
         fontsize=8, fontweight='bold')

# Moon
ax2.add_patch(Circle(
    (MOON_X, MOON_Y), 0.018,
    color='#6B7280', zorder=5))
ax2.text(MOON_X, -0.06, 'Moon',
         color='#94A3B8', ha='center',
         fontsize=8)

# Apollo 13 trajectory —
# much tighter Moon flyby
x_ap, y_ap = free_return_arc(
    ap_max_n, ap_close_n,
    outbound_spread=0.20)

# planned trajectory (aborted)
x_pl = np.linspace(0, MOON_X, 100)
y_pl = 0.06 * np.sin(
    np.pi * x_pl / MOON_X)
ax2.plot(x_pl, y_pl,
         color='#475569', lw=1.2,
         ls=':', alpha=0.5,
         label='Planned (aborted)')

# actual emergency arc
mid = len(x_ap) // 2
ax2.plot(x_ap[:mid], y_ap[:mid],
         color='#EF4444', lw=2.5,
         zorder=4, label='Emergency return')
ax2.plot(x_ap[mid:], y_ap[mid:],
         color='#F59E0B', lw=2.5,
         ls='--', zorder=4,
         label='Return coast')

# direction arrows
for frac, col in [(0.25, '#EF4444'),
                   (0.75, '#F59E0B')]:
    idx = int(frac * len(x_ap))
    if idx < len(x_ap) - 1:
        ax2.annotate('',
                     xy=(x_ap[idx+3], y_ap[idx+3]),
                     xytext=(x_ap[idx], y_ap[idx]),
                     arrowprops=dict(
                         arrowstyle='->',
                         color=col, lw=1.5))

# accident marker
acc_frac = met_hours(
    AP13_ACCIDENT, AP13_LAUNCH) / \
    AP13_DURATION
acc_idx  = int(acc_frac * len(x_ap) * 0.45)
ax2.plot(x_ap[acc_idx], y_ap[acc_idx],
         'X', color='#EF4444', ms=12,
         zorder=8,
         markeredgecolor='white',
         markeredgewidth=0.8)
ax2.text(x_ap[acc_idx] - 0.05,
         y_ap[acc_idx] + 0.07,
         'O₂ explosion\nT+55.9h',
         color='#EF4444', fontsize=7.5,
         linespacing=1.4,
         ha='center')

# close flyby annotation
ax2.text(MOON_X - 0.18, 0.10,
         f'Closest:\n{AP13_CLOSE_KM} km\n'
         f'(26× closer\nthan AII)',
         color='#EC4899', fontsize=7,
         linespacing=1.4)

# max distance
ax2.plot(x_ap[len(x_ap)//2 + 30],
         y_ap[len(x_ap)//2 + 30],
         'o', color='#F59E0B',
         ms=7, zorder=7,
         markeredgecolor='#0D1117',
         markeredgewidth=0.8)
ax2.text(1.08, 0.06,
         f'Max:\n{AP13_MAX_KM:,} km',
         color='#F59E0B', fontsize=7,
         linespacing=1.4)

ax2.legend(facecolor='#1E293B',
           edgecolor='#334155',
           labelcolor='white',
           fontsize=8, loc='lower right')

# ════════════════════════════════════════
# PANEL 3: side-by-side key numbers
# ════════════════════════════════════════
ax3 = axes[2]
ax3.set_facecolor('#0D1117')
ax3.axis('off')
ax3.set_title('Same physics\nDifferent story',
              color='white', fontsize=11,
              fontweight='bold', pad=8)

comparison_rows = [
    ('Year',
     '1970', '2026',
     '#94A3B8'),
    ('Max distance',
     f'{AP13_MAX_KM:,} km',
     f'{AII_MAX_KM:,} km',
     '#F59E0B'),
    ('Moon closest',
     f'{AP13_CLOSE_KM} km',
     f'{AII_CLOSE_KM:,} km',
     '#EC4899'),
    ('Free-return',
     'Emergency',
     'By design',
     '#10B981'),
    ('TCB Δv',
     '860 m/s',
     f'{TCB1_DV_MS:.2f} m/s',
     '#3B82F6'),
    ('Duration',
     f'{AP13_DURATION:.0f}h',
     f'{AII_DURATION:.0f}h',
     '#94A3B8'),
    ('Crew',
     'Lovell, Swigert\nHaise',
     'Wiseman, Glover\nKoch, Hansen',
     '#475569'),
    ('Outcome',
     'Safe return\n(no landing)',
     'Safe return\n(test flight)',
     '#10B981'),
]

# header
ax3.text(0.05, 0.96,
         'Parameter',
         transform=ax3.transAxes,
         color='#64748B', fontsize=8,
         fontweight='bold')
ax3.text(0.40, 0.96,
         'Apollo 13',
         transform=ax3.transAxes,
         color='#EF4444', fontsize=8,
         fontweight='bold')
ax3.text(0.72, 0.96,
         'Artemis II',
         transform=ax3.transAxes,
         color='#10B981', fontsize=8,
         fontweight='bold')

ax3.plot([0.03, 0.97], [0.93, 0.93],
         transform=ax3.transAxes,
         color='#334155', lw=0.8)

row_h = 0.093
for j, (param, ap13_v,
         a2_v, col) in \
        enumerate(comparison_rows):
    y = 0.88 - j * row_h

    ax3.text(0.05, y, param,
             transform=ax3.transAxes,
             color='#64748B',
             fontsize=7.5,
             va='top',
             linespacing=1.3)
    ax3.text(0.40, y, ap13_v,
             transform=ax3.transAxes,
             color='#EF4444',
             fontsize=7.5,
             va='top',
             linespacing=1.3)
    ax3.text(0.72, y, a2_v,
             transform=ax3.transAxes,
             color='#10B981',
             fontsize=7.5,
             va='top',
             linespacing=1.3)

    if j < len(comparison_rows) - 1:
        ax3.plot([0.03, 0.97],
                 [y - row_h * 0.82,
                  y - row_h * 0.82],
                 transform=ax3.transAxes,
                 color='#1E293B',
                 lw=0.5)

# bottom insight box
ax3.add_patch(FancyBboxPatch(
    (0.03, 0.02), 0.94, 0.10,
    boxstyle='round,pad=0.02',
    facecolor='#0F172A',
    edgecolor='#334155',
    transform=ax3.transAxes,
    zorder=2))
ax3.text(0.50, 0.07,
         'Same free-return arc.\n'
         '56 years apart.',
         transform=ax3.transAxes,
         color='#64748B', fontsize=8,
         ha='center', va='center',
         style='italic',
         linespacing=1.5)

plt.suptitle(
    'Free-Return Trajectory — '
    'Artemis II vs Apollo 13\n'
    'Same orbital mechanics  ·  '
    'Emergency in 1970  ·  '
    'Design choice in 2026',
    color='white', fontsize=12,
    fontweight='bold', y=1.01)

plt.tight_layout()
plt.savefig(
    'artemis_trajectory_comparison.png',
    dpi=120, facecolor='#0D1117',
    bbox_inches='tight')
plt.show()
print("Saved: artemis_trajectory_comparison.png")

# ============================================================
# Cell 3 — Return coast physics
# Velocity, acceleration, signal delay on the way home
# ============================================================
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.gridspec import GridSpec

fig = plt.figure(figsize=(16, 10))
fig.patch.set_facecolor('#0D1117')
gs  = GridSpec(2, 3, figure=fig,
               hspace=0.42, wspace=0.35)

ax_vel   = fig.add_subplot(gs[0, :2])  # velocity
ax_acc   = fig.add_subplot(gs[1, :2])  # acceleration
ax_comp  = fig.add_subplot(gs[:, 2])   # context panel

# ── return coast time array ───────────────────────────────────
# From max distance to splashdown
t_max_met  = met_hours(AII_MAX_DIST, AII_LAUNCH)
t_splash_met = AII_DURATION

# time from max distance (hours)
t_return   = np.linspace(0,
    t_splash_met - t_max_met, 2000)

# distance from Earth during return
# using gravitational free-fall model
# r(t) from energy conservation
# at max dist: KE ≈ 0, PE = -GM/r_max
r_max_m    = AII_MAX_KM * 1000  # m
r_earth_m  = R_earth * 1000     # m

# numerical integration of equation of motion
# dr/dt = v, dv/dt = -GM/r²
dt_s       = (t_return[1] - t_return[0]) * 3600
r_arr      = np.zeros(len(t_return))
v_arr      = np.zeros(len(t_return))
a_arr      = np.zeros(len(t_return))

# initial conditions at max distance
r_arr[0]   = r_max_m
# small initial velocity toward Earth
# (from trajectory correction burns)
v_arr[0]   = -TCB1_DV_MS * 5  # m/s inward

for i in range(1, len(t_return)):
    r      = r_arr[i-1]
    v      = v_arr[i-1]
    # gravitational acceleration
    a      = -GM_earth / r**2
    # Moon's gravity (opposing, approximate)
    r_moon_m = (D_moon - r/1000) * 1000
    if r_moon_m > 0:
        a += GM_moon / r_moon_m**2 * 0.3
    v_new  = v + a * dt_s
    r_new  = r + v_new * dt_s
    # stop at atmosphere
    if r_new < r_earth_m + 100_000:
        r_arr[i:] = r_earth_m + 80_000
        v_arr[i:] = v_new
        a_arr[i:] = 0
        break
    r_arr[i] = r_new
    v_arr[i] = v_new
    a_arr[i] = a

# convert
r_km   = r_arr / 1000
v_kms  = np.abs(v_arr) / 1000    # km/s
v_kmh  = v_kms * 3600            # km/h
a_ms2  = np.abs(a_arr)           # m/s²
a_g    = a_ms2 / 9.81            # in g

# signal delay
sig_delay = r_km / C_KMS

# ── TOP: velocity ─────────────────────────────────────────────
ax_vel.set_facecolor('#0D1117')
ax_vel.set_title(
    'Orion return coast — velocity profile '
    '(max distance → splashdown)',
    color='white', fontsize=11, pad=10)
ax_vel.set_ylabel('Velocity (km/s)',
                  color='#94A3B8', fontsize=9)
ax_vel.tick_params(
    colors='#94A3B8', labelsize=8)
for sp in ['bottom', 'left']:
    ax_vel.spines[sp].set_color('#334155')
for sp in ['top', 'right']:
    ax_vel.spines[sp].set_visible(False)
ax_vel.grid(color='#1E293B',
            lw=0.6, zorder=0)

ax_vel.plot(t_return, v_kms,
            color='#10B981', lw=2.5,
            zorder=5)
ax_vel.fill_between(
    t_return, v_kms, 0,
    color='#10B981', alpha=0.08)

# phase zones
ax_vel.axvspan(0, 20,
               color='#F59E0B', alpha=0.05)
ax_vel.axvspan(20, 60,
               color='#3B82F6', alpha=0.05)
ax_vel.axvspan(60, t_return[-1],
               color='#EF4444', alpha=0.05)

ax_vel.text(10, v_kms.max() * 0.85,
            'Leaving\nMoon SOI',
            color='#F59E0B', fontsize=8,
            ha='center', style='italic',
            linespacing=1.4)
ax_vel.text(40, v_kms.max() * 0.85,
            'Deep space\ncoast',
            color='#3B82F6', fontsize=8,
            ha='center', style='italic',
            linespacing=1.4)
ax_vel.text(t_return[-1] * 0.85,
            v_kms.max() * 0.85,
            'Earth\napproach',
            color='#EF4444', fontsize=8,
            ha='center', style='italic',
            linespacing=1.4)

# key velocity references
refs = [
    (0.489 / 1000, '#475569',
     'TCB-1 initial\n(0.489 m/s)'),
    (1.0, '#475569',
     '1 km/s'),
    (REENTRY_V_MS / 1000, '#EF4444',
     f'Entry: '
     f'{REENTRY_V_MS/1000:.2f} km/s'),
]
for val, col, label in refs:
    ax_vel.axhline(val, color=col,
                   lw=0.8, ls=':',
                   alpha=0.6)
    ax_vel.text(2, val * 1.05, label,
               color=col, fontsize=7.5)

# Apollo 13 PC-2 comparison arrow
ax_vel.annotate(
    'Apollo 13 PC-2\nrequired 860 m/s',
    xy=(5, 0.86),
    xytext=(25, 3.5),
    color='#EF4444', fontsize=8,
    linespacing=1.4,
    arrowprops=dict(
        arrowstyle='->',
        color='#EF4444', lw=1.0))

ax_vel.set_xlim(0, t_return[-1])
ax_vel.set_xticklabels([])

# secondary axis — km/h
ax_vel2 = ax_vel.twinx()
ax_vel2.set_facecolor('#0D1117')
ax_vel2.set_ylabel('Velocity (km/h)',
                   color='#64748B',
                   fontsize=8)
ax_vel2.tick_params(
    colors='#64748B', labelsize=7)
ax_vel2.spines['right']\
       .set_color('#334155')
ax_vel2.spines['top']\
       .set_visible(False)
# sync with left axis
ax_vel2.set_ylim(
    ax_vel.get_ylim()[0] * 3600,
    ax_vel.get_ylim()[1] * 3600)

# ── BOTTOM: acceleration ──────────────────────────────────────
ax_acc.set_facecolor('#0D1117')
ax_acc.set_title(
    'Gravitational acceleration — '
    'Earth pulling Orion home',
    color='white', fontsize=10, pad=8)
ax_acc.set_xlabel(
    'Hours from maximum distance',
    color='#94A3B8', fontsize=9)
ax_acc.set_ylabel(
    'Acceleration (m/s²)',
    color='#94A3B8', fontsize=9)
ax_acc.tick_params(
    colors='#94A3B8', labelsize=8)
for sp in ['bottom', 'left']:
    ax_acc.spines[sp]\
          .set_color('#334155')
for sp in ['top', 'right']:
    ax_acc.spines[sp]\
          .set_visible(False)
ax_acc.grid(color='#1E293B',
            lw=0.6, zorder=0)

ax_acc.plot(t_return, a_ms2,
            color='#F59E0B', lw=2.0,
            zorder=5)
ax_acc.fill_between(
    t_return, a_ms2, 0,
    color='#F59E0B', alpha=0.08)

# phase zones
ax_acc.axvspan(0, 20,
               color='#F59E0B', alpha=0.05)
ax_acc.axvspan(20, 60,
               color='#3B82F6', alpha=0.05)
ax_acc.axvspan(60, t_return[-1],
               color='#EF4444', alpha=0.05)

# reference lines
ax_acc.axhline(9.81, color='#EF4444',
               lw=0.8, ls=':',
               alpha=0.6)
ax_acc.text(2, 9.81 * 1.03,
            'Earth surface 1g',
            color='#EF4444', fontsize=7.5)

# ISS acceleration reference
iss_r   = (R_earth + 408) * 1000
iss_acc = GM_earth / iss_r**2
ax_acc.axhline(iss_acc, color='#10B981',
               lw=0.8, ls=':',
               alpha=0.6)
ax_acc.text(2, iss_acc * 1.05,
            f'ISS altitude: '
            f'{iss_acc:.3f} m/s²',
            color='#10B981', fontsize=7.5)

ax_acc.set_xlim(0, t_return[-1])

# secondary axis — in g
ax_acc2 = ax_acc.twinx()
ax_acc2.set_facecolor('#0D1117')
ax_acc2.set_ylabel('Acceleration (g)',
                   color='#64748B',
                   fontsize=8)
ax_acc2.tick_params(
    colors='#64748B', labelsize=7)
ax_acc2.spines['right']\
       .set_color('#334155')
ax_acc2.spines['top']\
       .set_visible(False)
ax_acc2.set_ylim(
    ax_acc.get_ylim()[0] / 9.81,
    ax_acc.get_ylim()[1] / 9.81)

# ── RIGHT: context panel ──────────────────────────────────────
ax_comp.set_facecolor('#0D1117')
ax_comp.axis('off')
ax_comp.set_title(
    'Return coast\ncontext',
    color='white', fontsize=10, pad=8)

# signal delay subplot inside panel
ax_sig = fig.add_axes([
    0.675, 0.55, 0.29, 0.32
])
ax_sig.set_facecolor('#0D1117')
ax_sig.tick_params(
    colors='#475569', labelsize=7)
for sp in ['bottom', 'left']:
    ax_sig.spines[sp]\
          .set_color('#334155')
for sp in ['top', 'right']:
    ax_sig.spines[sp].set_visible(False)
ax_sig.grid(color='#1E293B',
            lw=0.5, zorder=0)
ax_sig.set_title(
    'Signal delay (one-way)',
    color='white', fontsize=8, pad=4)

ax_sig.plot(t_return, sig_delay,
            color='#3B82F6', lw=2.0,
            zorder=4)
ax_sig.fill_between(
    t_return, sig_delay, 0,
    color='#3B82F6', alpha=0.08)
ax_sig.set_xlabel(
    'Hours from max dist',
    color='#475569', fontsize=6.5)
ax_sig.set_ylabel(
    'Delay (s)', color='#475569',
    fontsize=6.5)
ax_sig.set_xlim(0, t_return[-1])

# context facts
facts = [
    ('Free-fall',
     'No engine burns needed\n'
     'gravity does all the work',
     '#10B981'),
    ('TCB-1 burn',
     '15 seconds  ·  1.6 ft/s\n'
     'changes destiny by 100s km',
     '#F59E0B'),
    ('Entry velocity',
     f'{REENTRY_V_MPH:,} mph\n'
     f'30× speed of sound',
     '#EF4444'),
    ('Deceleration',
     f'{REENTRY_V_MPH//SPLASH_V_MPH:,}×\n'
     'in 13 minutes',
     '#EC4899'),
    ('Heat shield peak',
     f'{HEAT_SHIELD_C:,}°C\n'
     'half the Sun surface temp',
     '#F59E0B'),
]

y_start = 0.48
for j, (title, desc, col) in \
        enumerate(facts):
    y = y_start - j * 0.10
    ax_comp.plot(
        0.05, y, 'o', color=col,
        ms=6, zorder=3,
        transform=ax_comp.transAxes)
    ax_comp.text(
        0.12, y + 0.012, title,
        transform=ax_comp.transAxes,
        color=col, fontsize=8,
        fontweight='bold', va='center')
    ax_comp.text(
        0.12, y - 0.018, desc,
        transform=ax_comp.transAxes,
        color='#475569', fontsize=7.5,
        va='center', linespacing=1.3)
    if j < len(facts) - 1:
        ax_comp.plot(
            [0.05, 0.95],
            [y - 0.047, y - 0.047],
            transform=ax_comp.transAxes,
            color='#1E293B', lw=0.6)

plt.suptitle(
    'Artemis II Return Coast — '
    'Gravity Doing All the Work\n'
    'Physics of a free-return '
    'trajectory from lunar distance',
    color='white', fontsize=11,
    fontweight='bold', y=1.01)

plt.tight_layout()
plt.savefig(
    'artemis_return_physics.png',
    dpi=120, facecolor='#0D1117',
    bbox_inches='tight')
plt.show()
print("Saved: artemis_return_physics.png")

# ============================================================
# Cell 4 — Reentry profile
# 25,000 mph to 17 mph in 13 minutes
# Lofted entry sequence · heat shield · parachutes
# ============================================================
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.patches import FancyBboxPatch, FancyArrowPatch
from matplotlib.gridspec import GridSpec

fig = plt.figure(figsize=(16, 10))
fig.patch.set_facecolor('#0D1117')
gs  = GridSpec(2, 3, figure=fig,
               hspace=0.45, wspace=0.38)

ax_traj  = fig.add_subplot(gs[:, :2])   # main reentry diagram
ax_vel   = fig.add_subplot(gs[0, 2])    # velocity profile
ax_temp  = fig.add_subplot(gs[1, 2])    # temperature profile

# ── reentry sequence timeline ─────────────────────────────────
# Source: NASA Flight Director Rick Henfling briefing
# April 8, 2026

# All times in minutes from entry interface (EI)
# EI = entry interface = 120 km altitude
events = [
    # (t_min, alt_km, v_mph, temp_C, label, color)
    ( 0.0,  120.0,  25_000,     0,
      'Entry interface\n(EI)\n120 km altitude',
      '#EF4444'),
    ( 1.5,   80.0,  24_200,   500,
      'Peak heating\nbegins',
      '#F59E0B'),
    ( 3.0,   60.0,  22_000, 2_760,
      'Peak heat\n2,760°C\nheat shield',
      '#EF4444'),
    ( 4.5,   55.0,  18_000, 2_400,
      'Max deceleration\n~11g',
      '#EC4899'),
    ( 6.0,   45.0,  14_000, 1_200,
      'Skip manoeuvre\n(lofted entry)',
      '#3B82F6'),
    ( 8.0,   35.0,   8_000,   400,
      'Plasma blackout\nends',
      '#475569'),
    ( 9.5,   25.0,   3_000,    80,
      'Drogue chutes\ndeploy',
      '#10B981'),
    (10.5,   15.0,     800,    40,
      'Main chutes\ndeploy (3)',
      '#10B981'),
    (13.0,    0.0,      17,    25,
      'Splashdown\nPacific Ocean',
      '#3B82F6'),
]

t_arr    = np.array([e[0] for e in events])
alt_arr  = np.array([e[1] for e in events])
v_arr    = np.array([e[2] for e in events])
temp_arr = np.array([e[3] for e in events])
labels   = [e[4] for e in events]
cols     = [e[5] for e in events]

# smooth interpolation
t_fine   = np.linspace(0, 13, 500)
alt_fine = np.interp(t_fine, t_arr, alt_arr)
v_fine   = np.interp(t_fine, t_arr, v_arr)
temp_fine= np.interp(t_fine, t_arr, temp_arr)

# ── MAIN: reentry diagram ─────────────────────────────────────
ax_traj.set_facecolor('#060F1A')
ax_traj.set_title(
    'Orion lofted reentry sequence — '
    'April 10, 2026',
    color='white', fontsize=12, pad=10)
ax_traj.set_xlabel(
    'Minutes from entry interface',
    color='#94A3B8', fontsize=9)
ax_traj.set_ylabel(
    'Altitude (km)',
    color='#94A3B8', fontsize=9)
ax_traj.tick_params(
    colors='#94A3B8', labelsize=8)
for sp in ['bottom', 'left']:
    ax_traj.spines[sp]\
           .set_color('#334155')
for sp in ['top', 'right']:
    ax_traj.spines[sp]\
           .set_visible(False)
ax_traj.grid(color='#1E293B',
             lw=0.6, zorder=0)

# atmosphere layers
atm_layers = [
    (0,   12,  '#0F2137',
     'Troposphere (0–12 km)'),
    (12,  50,  '#0A1A2E',
     'Stratosphere (12–50 km)'),
    (50,  80,  '#071422',
     'Mesosphere (50–80 km)'),
    (80,  120, '#050F1A',
     'Thermosphere (80–120 km)'),
]
for y0, y1, col, label in atm_layers:
    ax_traj.axhspan(y0, y1,
                    color=col, alpha=0.8,
                    zorder=1)
    ax_traj.text(0.2, (y0+y1)/2,
                 label, color='#1E3A5C',
                 fontsize=7, va='center',
                 style='italic')

# lofted entry path — colour by temperature
from matplotlib.collections import LineCollection
points = np.array(
    [t_fine, alt_fine]).T\
    .reshape(-1, 1, 2)
segments = np.concatenate(
    [points[:-1], points[1:]], axis=1)

# normalise temperature for colormap
temp_norm = temp_fine / temp_fine.max()
lc = LineCollection(
    segments,
    cmap='plasma',
    norm=plt.Normalize(0, 1),
    linewidth=3.5, zorder=5)
lc.set_array(temp_norm[:-1])
ax_traj.add_collection(lc)

# colorbar
cbar = plt.colorbar(
    lc, ax=ax_traj,
    shrink=0.6, pad=0.01)
cbar.set_label(
    'Heat shield temperature',
    color='white', fontsize=8)
cbar.ax.tick_params(
    colors='#94A3B8', labelsize=7)
cbar.set_ticks([0, 0.5, 1.0])
cbar.set_ticklabels(
    ['0°C', '~1,380°C', '2,760°C'])

# event markers
for t, alt, label, col in zip(
        t_arr, alt_arr, labels, cols):
    ax_traj.plot(t, alt, 'o',
                 color=col, ms=10,
                 zorder=7,
                 markeredgecolor='#0D1117',
                 markeredgewidth=1.0)

    # alternate labels above/below
    y_off = 6 if alt < 60 else -10
    ha    = 'left' if t < 7 else 'right'
    ax_traj.annotate(
        label,
        xy=(t, alt),
        xytext=(t + 0.3,
                alt + y_off),
        color=col, fontsize=7,
        linespacing=1.4,
        arrowprops=dict(
            arrowstyle='->',
            color=col, lw=0.7,
            alpha=0.7))

# skip manoeuvre annotation
ax_traj.annotate(
    'Lofted entry:\nOrion skips off\nupper atmosphere\nto control heating',
    xy=(6.0, 45.0),
    xytext=(7.5, 75.0),
    color='#3B82F6', fontsize=8,
    linespacing=1.5,
    arrowprops=dict(
        arrowstyle='->',
        color='#3B82F6', lw=1.0))

# plasma blackout zone
ax_traj.axvspan(3.0, 8.0,
                color='#EF4444',
                alpha=0.06, zorder=2)
ax_traj.text(5.5, 90,
             'PLASMA\nBLACKOUT\n(comms lost)',
             color='#EF4444',
             fontsize=8, ha='center',
             linespacing=1.4,
             fontweight='bold')

# parachute deploy arrow
ax_traj.annotate(
    '',
    xy=(10.5, 15),
    xytext=(10.5, 30),
    arrowprops=dict(
        arrowstyle='->',
        color='#10B981', lw=2.0))
ax_traj.text(10.7, 22,
             '🪂 3 main\nchutes',
             color='#10B981',
             fontsize=8,
             linespacing=1.4)

# Earth surface
ax_traj.axhline(0, color='#1B4FD8',
                lw=2.0, alpha=0.8)
ax_traj.fill_between(
    t_fine, -5, 0,
    color='#1B4FD8', alpha=0.3)
ax_traj.text(6.5, -3,
             'Pacific Ocean',
             color='#3B82F6',
             fontsize=8, ha='center')

ax_traj.set_xlim(0, 13.5)
ax_traj.set_ylim(-5, 130)

# ── TOP RIGHT: velocity ───────────────────────────────────────
ax_vel.set_facecolor('#0D1117')
ax_vel.set_title('Velocity during reentry',
                 color='white',
                 fontsize=9, pad=6)
ax_vel.set_xlabel(
    'Minutes from EI',
    color='#94A3B8', fontsize=8)
ax_vel.set_ylabel('Velocity (mph)',
                  color='#94A3B8',
                  fontsize=8)
ax_vel.tick_params(
    colors='#94A3B8', labelsize=7)
for sp in ['bottom', 'left']:
    ax_vel.spines[sp]\
          .set_color('#334155')
for sp in ['top', 'right']:
    ax_vel.spines[sp]\
          .set_visible(False)
ax_vel.grid(color='#1E293B',
            lw=0.5, zorder=0)
ax_vel.set_yscale('log')

ax_vel.plot(t_fine, v_fine,
            color='#EF4444',
            lw=2.0, zorder=4)
ax_vel.fill_between(
    t_fine, v_fine, v_fine.min(),
    color='#EF4444', alpha=0.08)

# reference lines
refs_v = [
    (25_000, 'Entry: 25,000 mph',
     '#EF4444'),
    (767,    'Speed of sound',
     '#475569'),
    (17,     'Splashdown: 17 mph',
     '#10B981'),
]
for val, label, col in refs_v:
    ax_vel.axhline(
        val, color=col,
        lw=0.8, ls=':', alpha=0.7)
    ax_vel.text(0.2, val * 1.15,
                label, color=col,
                fontsize=6.5)

# event dots
for t, v, col in zip(
        t_arr, v_arr, cols):
    ax_vel.plot(t, v, 'o',
                color=col, ms=5,
                zorder=5,
                markeredgecolor='#0D1117',
                markeredgewidth=0.6)

ax_vel.set_xlim(0, 13.5)
ax_vel.set_ylim(10, 30_000)

# deceleration factor
ax_vel.text(
    6.5, 5000,
    f'{REENTRY_V_MPH // SPLASH_V_MPH:,}×\ndeceleration',
    color='#EC4899', fontsize=8,
    ha='center', fontweight='bold',
    linespacing=1.4)

# ── BOTTOM RIGHT: temperature ─────────────────────────────────
ax_temp.set_facecolor('#0D1117')
ax_temp.set_title(
    'Heat shield temperature',
    color='white', fontsize=9, pad=6)
ax_temp.set_xlabel(
    'Minutes from EI',
    color='#94A3B8', fontsize=8)
ax_temp.set_ylabel('Temperature (°C)',
                   color='#94A3B8',
                   fontsize=8)
ax_temp.tick_params(
    colors='#94A3B8', labelsize=7)
for sp in ['bottom', 'left']:
    ax_temp.spines[sp]\
           .set_color('#334155')
for sp in ['top', 'right']:
    ax_temp.spines[sp]\
           .set_visible(False)
ax_temp.grid(color='#1E293B',
             lw=0.5, zorder=0)

ax_temp.plot(t_fine, temp_fine,
             color='#F59E0B',
             lw=2.0, zorder=4)
ax_temp.fill_between(
    t_fine, temp_fine, 0,
    color='#F59E0B', alpha=0.10)

# peak annotation
peak_idx = np.argmax(temp_fine)
ax_temp.plot(
    t_fine[peak_idx],
    temp_fine[peak_idx],
    'o', color='#EF4444', ms=8,
    zorder=6,
    markeredgecolor='#0D1117',
    markeredgewidth=0.8)
ax_temp.annotate(
    f'Peak: {HEAT_SHIELD_C:,}°C\n'
    f'≈ half Sun surface',
    xy=(t_fine[peak_idx],
        temp_fine[peak_idx]),
    xytext=(5, 2400),
    color='#EF4444', fontsize=7.5,
    linespacing=1.4,
    arrowprops=dict(
        arrowstyle='->',
        color='#EF4444', lw=0.8))

# reference lines
refs_t = [
    (HEAT_SHIELD_C,
     f'Peak: {HEAT_SHIELD_C:,}°C',
     '#EF4444'),
    (1_535, 'Iron melts\n(1,535°C)',
     '#F59E0B'),
    (660,   'Aluminium melts\n(660°C)',
     '#F59E0B'),
    (100,   'Water boils\n(100°C)',
     '#3B82F6'),
]
for val, label, col in refs_t:
    if val <= HEAT_SHIELD_C:
        ax_temp.axhline(
            val, color=col, lw=0.7,
            ls=':', alpha=0.6)
        ax_temp.text(
            8.5, val + 40, label,
            color=col, fontsize=6.5,
            linespacing=1.3)

ax_temp.set_xlim(0, 13.5)
ax_temp.set_ylim(-100, 3_100)

plt.suptitle(
    'Orion Reentry — '
    '13 Minutes from 25,000 mph to Splashdown\n'
    'Source: NASA Flight Director Rick Henfling  ·  '
    'Artemis II mission briefing  ·  April 8, 2026',
    color='white', fontsize=11,
    fontweight='bold', y=1.01)

plt.tight_layout()
plt.savefig(
    'artemis_reentry_profile.png',
    dpi=120, facecolor='#0D1117',
    bbox_inches='tight')
plt.show()
print("Saved: artemis_reentry_profile.png")

# ============================================================
# Cell 5 — Day 8 Summary Dashboard
# The Long Way Home
# Code Beyond the Earth | April 8, 2026
# ============================================================
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from matplotlib.patches import FancyBboxPatch
from datetime import datetime, timezone

now_utc = datetime.now(timezone.utc)

fig = plt.figure(figsize=(20, 12))
fig.patch.set_facecolor('#0D1117')
ax  = fig.add_axes([0, 0, 1, 1])
ax.set_xlim(0, 20)
ax.set_ylim(0, 12)
ax.axis('off')
ax.set_facecolor('#0D1117')

# ── helpers ───────────────────────────────────────────────────
def card(x, y, w, h,
         fc='#1E293B', ec='#334155',
         lw=0.8):
    ax.add_patch(FancyBboxPatch(
        (x, y), w, h,
        boxstyle='round,pad=0.08',
        facecolor=fc, edgecolor=ec,
        linewidth=lw, zorder=2))

def txt(x, y, s, **kw):
    kw.setdefault('color', 'white')
    kw.setdefault('fontsize', 10)
    kw.setdefault('zorder', 4)
    kw.setdefault('va', 'center')
    ax.text(x, y, s, **kw)

def hln(x0, x1, y,
        col='#1E293B', lw=0.7):
    ax.plot([x0, x1], [y, y],
            color=col, lw=lw,
            zorder=3)

# ════════════════════════════════════════════════════════════
# HEADER
# ════════════════════════════════════════════════════════════
card(0.25, 10.7, 19.5, 1.1,
     fc='#0F172A', ec='#1E3A5C')
txt(10.0, 11.35,
    'DAY 8 — THE LONG WAY HOME: '
    'RETURN TRAJECTORY & APOLLO 13 COMPARISON',
    fontsize=15, fontweight='bold',
    ha='center')
txt(10.0, 10.97,
    f'Code Beyond the Earth  ·  '
    f'Artemis II  ·  April 8, 2026  ·  '
    f'Splashdown: Apr 10, 00:07 UTC  ·  '
    f'Generated {now_utc.strftime("%H:%M UTC")}',
    fontsize=9, ha='center',
    color='#475569')

# ════════════════════════════════════════════════════════════
# ROW 1 — metric cards
# ════════════════════════════════════════════════════════════
metrics = [
    ('TCB-1 burn',
     '15 s',       '1.6 ft/s  ·  0.49 m/s',
     '#F59E0B'),
    ('Return duration',
     f'{AII_DURATION - met_hours(AII_MAX_DIST,AII_LAUNCH):.0f}h',
     'max dist → splashdown',
     '#10B981'),
    ('Entry velocity',
     '25,000',     'mph  (30× sound)',
     '#EF4444'),
    ('Reentry time',
     '13',          'minutes EI → splash',
     '#EC4899'),
    ('Heat shield peak',
     '2,760',      '°C  (½ Sun surface)',
     '#F59E0B'),
]
cw = 3.6
for i, (label, val, unit, col) in \
        enumerate(metrics):
    bx = 0.25 + i * (cw + 0.25)
    card(bx, 9.25, cw, 1.25,
         fc='#0F172A', ec=col)
    txt(bx + cw/2, 10.15, label,
        fontsize=8.5, color='#64748B',
        ha='center')
    txt(bx + cw/2, 9.78, val,
        fontsize=18, fontweight='bold',
        color=col, ha='center')
    txt(bx + cw/2, 9.42, unit,
        fontsize=8, color='#475569',
        ha='center')

# ════════════════════════════════════════════════════════════
# ROW 2 — three content cards
# ════════════════════════════════════════════════════════════
CW   = 6.2
CGAP = 0.25
CY0  = 5.05
CH   = 4.0
CY1  = CY0 + CH
c1x  = 0.25
c2x  = c1x + CW + CGAP
c3x  = c2x + CW + CGAP

card(c1x, CY0, CW, CH)
card(c2x, CY0, CW, CH)
card(c3x, CY0, CW, CH)

# ── CARD 1: mini trajectory plots ────────────────────────────
txt(c1x + CW/2, CY1 - 0.3,
    'Return trajectory profile',
    fontsize=9.5, fontweight='bold',
    ha='center')

ax_mini = fig.add_axes([
    (c1x + 0.25) / 20,
    (CY0 + 0.85) / 12,
    (CW - 0.5)   / 20,
    (CH - 1.5)   / 12
])
ax_mini.set_facecolor('#0D1117')
ax_mini.tick_params(
    colors='#475569', labelsize=6.5)
for sp in ['bottom', 'left']:
    ax_mini.spines[sp]\
           .set_color('#334155')
for sp in ['top', 'right']:
    ax_mini.spines[sp]\
           .set_visible(False)
ax_mini.grid(color='#1E293B',
             lw=0.5, zorder=0)

# Artemis II
ax_mini.plot(t_a2, d_a2,
             color='#10B981', lw=2.0,
             zorder=4,
             label='Artemis II')

# Apollo 13 — align by MET for comparison
ax_mini.plot(t_ap13, d_ap13,
             color='#EF4444', lw=1.5,
             ls='--', zorder=3,
             alpha=0.7,
             label='Apollo 13')

# accident marker
ap13_acc_met = met_hours(
    AP13_ACCIDENT, AP13_LAUNCH)
ap13_acc_d   = float(np.interp(
    ap13_acc_met, t_ap13, d_ap13))
ax_mini.plot(
    ap13_acc_met, ap13_acc_d,
    'X', color='#EF4444', ms=8,
    zorder=6,
    markeredgecolor='white',
    markeredgewidth=0.8)
ax_mini.text(
    ap13_acc_met + 2,
    ap13_acc_d + 15_000,
    'O₂\nexplosion',
    color='#EF4444', fontsize=5.5,
    linespacing=1.3)

ax_mini.set_xlabel(
    'MET (hours)', color='#475569',
    fontsize=6)
ax_mini.set_ylabel(
    'km', color='#475569',
    fontsize=6)
ax_mini.legend(
    facecolor='#1E293B',
    edgecolor='#334155',
    labelcolor='white', fontsize=6,
    loc='upper right')
ax_mini.yaxis.set_major_formatter(
    plt.FuncFormatter(
        lambda x, _:
        f'{x/1000:.0f}k'))

card(c1x + 0.2, CY0 + 0.18,
     CW - 0.4, 0.55,
     fc='#0F172A', ec='#334155')
txt(c1x + CW/2, CY0 + 0.46,
    'Same free-return arc  ·  '
    '56 years apart  ·  '
    'Same physics',
    fontsize=8, color='#64748B',
    ha='center')

# ── CARD 2: Apollo 13 vs Artemis II ──────────────────────────
txt(c2x + CW/2, CY1 - 0.3,
    'Apollo 13 vs Artemis II',
    fontsize=9.5, fontweight='bold',
    ha='center')

# column headers
txt(c2x + 0.25, CY1 - 0.68,
    'Parameter',
    fontsize=8, color='#64748B',
    ha='left', fontweight='bold')
txt(c2x + 2.55, CY1 - 0.68,
    'Apollo 13',
    fontsize=8, color='#EF4444',
    ha='center', fontweight='bold')
txt(c2x + 4.35, CY1 - 0.68,
    'Artemis II',
    fontsize=8, color='#10B981',
    ha='center', fontweight='bold')

hln(c2x + 0.2, c2x + CW - 0.2,
    CY1 - 0.82, col='#334155')

rows = [
    ('Year',
     '1970', '2026'),
    ('Max distance',
     f'{AP13_MAX_KM/1000:.0f}k km',
     f'{AII_MAX_KM/1000:.0f}k km'),
    ('Moon closest',
     f'{AP13_CLOSE_KM} km',
     f'{AII_CLOSE_KM:,} km'),
    ('Free-return',
     'Emergency',
     'By design'),
    ('TCB Δv needed',
     '860 m/s',
     '0.49 m/s'),
    ('Duration',
     f'{AP13_DURATION:.0f}h',
     f'{AII_DURATION:.0f}h'),
    ('Crew size',
     '3', '4'),
    ('Outcome',
     'Safe — no landing',
     'Safe — test flight ✓'),
]
row_h = 0.52
for j, (param, ap_v, a2_v) in \
        enumerate(rows):
    ry = CY1 - 1.05 - j * row_h

    txt(c2x + 0.25, ry, param,
        fontsize=8, color='#64748B',
        ha='left')
    txt(c2x + 2.55, ry, ap_v,
        fontsize=8, color='#EF4444',
        ha='center', fontweight='bold')
    txt(c2x + 4.35, ry, a2_v,
        fontsize=8, color='#10B981',
        ha='center', fontweight='bold')

    if j < len(rows) - 1:
        hln(c2x + 0.2,
            c2x + CW - 0.2,
            ry - 0.28,
            col='#1E293B')

card(c2x + 0.2, CY0 + 0.18,
     CW - 0.4, 0.75,
     fc='#0F172A', ec='#334155')
txt(c2x + CW/2, CY0 + 0.56,
    'TCB Δv: Apollo 13 needed 860 m/s\n'
    'Artemis II needed 0.49 m/s — 1,755× less.',
    fontsize=8.5, ha='center',
    color='#64748B', linespacing=1.5)

# ── CARD 3: reentry sequence ──────────────────────────────────
txt(c3x + CW/2, CY1 - 0.3,
    'Reentry sequence — April 10',
    fontsize=9.5, fontweight='bold',
    ha='center')

reentry_events = [
    ('7:33 PM EDT',
     'Service module separation',
     '#475569'),
    ('7:37 PM EDT',
     'Final trajectory burn',
     '#F59E0B'),
    ('7:54 PM EDT',
     'Entry interface  ·  120 km',
     '#EF4444'),
    ('7:57 PM EDT',
     'Peak heating  ·  2,760°C',
     '#EF4444'),
    ('8:02 PM EDT',
     'Plasma blackout begins',
     '#EF4444'),
    ('8:02 PM EDT',
     'Drogue chutes deploy',
     '#10B981'),
    ('8:04 PM EDT',
     'Main chutes deploy (3)',
     '#10B981'),
    ('8:07 PM EDT',
     'Splashdown — Pacific Ocean  ✓',
     '#3B82F6'),
]
for j, (time_s, label, col) in \
        enumerate(reentry_events):
    ry = CY1 - 0.90 - j * 0.43

    ax.plot(c3x + 0.35, ry, 'o',
            color=col, ms=7, zorder=5,
            markeredgecolor='#0D1117',
            markeredgewidth=0.8)

    if j < len(reentry_events) - 1:
        ax.plot([c3x + 0.35,
                 c3x + 0.35],
                [ry - 0.06,
                 ry - 0.37],
                color='#334155',
                lw=0.8, zorder=3)

    txt(c3x + 0.55, ry + 0.04,
        time_s,
        fontsize=7.5, color=col,
        fontweight='bold', ha='left')
    txt(c3x + 0.55, ry - 0.12,
        label,
        fontsize=7.5, color='#475569',
        ha='left')

card(c3x + 0.2, CY0 + 0.18,
     CW - 0.4, 0.75,
     fc='#0F172A', ec='#334155')
txt(c3x + CW/2, CY0 + 0.56,
    '"13 minutes of things that\n'
    ' have to go right."\n'
    '— Flight Director Jeff Radigan',
    fontsize=8.5, ha='center',
    color='#64748B', linespacing=1.5,
    style='italic')

# ════════════════════════════════════════════════════════════
# ROW 3 — full mission timeline strip
# ════════════════════════════════════════════════════════════
card(0.25, 0.85, 19.5, 4.0)
txt(10.0, 4.62,
    'Artemis II — complete mission timeline',
    fontsize=10, fontweight='bold',
    ha='center')

full_events = [
    (AII_LAUNCH,   'Launch\nApr 1',
     '#3B82F6', 3.4),
    (AII_TLI,      'TLI burn\nApr 2',
     '#F59E0B', 0.6),
    (AII_SOI_IN,   'SOI entry\nApr 6\n04:41',
     '#F59E0B', 3.4),
    (AII_FLYBY,    'Flyby\nApr 6\n23:02',
     '#EC4899', 0.6),
    (AII_MAX_DIST, 'Max dist\n406,771 km',
     '#10B981', 3.4),
    (AII_SOI_OUT,  'SOI exit\nApr 7',
     '#F59E0B', 0.6),
    (AII_TCB1,     'TCB-1\n15s burn',
     '#F59E0B', 3.4),
    (AII_SPLASH,   'Splashdown\nApr 10\n00:07',
     '#3B82F6', 0.6),
]

n_ev  = len(full_events)
AX0   = 0.9
AXW   = 18.2
AXY   = 2.55

ax.plot([AX0, AX0 + AXW],
        [AXY, AXY],
        color='#334155', lw=1.5,
        zorder=3)

t_start = full_events[0][0]
t_end   = full_events[-1][0]
t_span  = (t_end - t_start)\
          .total_seconds()

for evt_dt, label, col, lbl_y in \
        full_events:
    frac = (evt_dt - t_start)\
           .total_seconds() / t_span
    tx   = AX0 + frac * AXW

    ax.plot(tx, AXY, 'o',
            color=col, ms=11,
            zorder=5,
            markeredgecolor='#0D1117',
            markeredgewidth=1.0)

    # connector
    y1 = lbl_y + 0.3 \
         if lbl_y > AXY \
         else lbl_y + 0.3
    ax.plot([tx, tx],
            [AXY + 0.1
             if lbl_y > AXY
             else AXY - 0.1,
             y1],
            color=col, lw=0.8,
            alpha=0.5, zorder=3)

    txt(tx, lbl_y, label,
        fontsize=7.5, ha='center',
        color=col, linespacing=1.4,
        fontweight='bold')

# mission duration label
txt(10.0, AXY - 0.45,
    f'Total mission: '
    f'{AII_DURATION:.1f}h = '
    f'{AII_DURATION/24:.2f} days  ·  '
    f'~695,081 miles travelled',
    fontsize=8, ha='center',
    color='#475569')

# ════════════════════════════════════════════════════════════
# FOOTER
# ════════════════════════════════════════════════════════════
card(0.25, 0.12, 19.5, 0.62,
     fc='#0F172A', ec='#1E293B')
txt(10.0, 0.44,
    f'Code Beyond the Earth  ·  '
    f'codebeyondtheearth.substack.com  ·  '
    f'Generated '
    f'{now_utc.strftime("%B %d, %Y  %H:%M UTC")}'
    f'  ·  Sources: NASA Artemis II  ·  '
    f'Flight Director briefing Apr 8, 2026  ·  '
    f'Apollo 13 mission records',
    fontsize=8, ha='center',
    color='#475569')

plt.savefig(
    'artemis_day8_summary.png',
    dpi=150, facecolor='#0D1117',
    bbox_inches='tight')
plt.show()

print("=" * 60)
print("   DAY 8 COMPLETE — THE LONG WAY HOME")
print("=" * 60)
print()
print("  Cells completed:")
print("    Cell 1  Constants + mission timelines")
print("    Cell 2  Free-return trajectory comparison")
print("    Cell 3  Return coast physics")
print("    Cell 4  Reentry profile")
print("    Cell 5  This summary dashboard")
print()
print("  Key numbers:")
print(f"    TCB-1 burn       : 15s  "
      f"·  {TCB1_DV_MS:.3f} m/s")
print(f"    Apollo 13 TCB    : 860 m/s  "
      f"({860/TCB1_DV_MS:.0f}× more)")
print(f"    Entry velocity   : "
      f"{REENTRY_V_MPH:,} mph")
print(f"    Reentry duration : 13 minutes")
print(f"    Heat shield peak : "
      f"{HEAT_SHIELD_C:,}°C")
print(f"    Mission duration : "
      f"{AII_DURATION:.1f}h")
print()
print("  Saved files:")
print("    artemis_trajectory_comparison.png")
print("    artemis_return_physics.png")
print("    artemis_reentry_profile.png")
print("    artemis_day8_summary.png")
print("=" * 60)