# -*- coding: utf-8 -*-
"""the_longest_journey.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/110C8IxwBRTT0-Wny6ZnYhhPrB6q34es5
"""

# ============================================================
# CELL 1 — Constants & Historical Dataset
# Day 7 — The Longest Journey
# Code Beyond the Earth | April 7, 2026
# ============================================================
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation
import matplotlib.patches as mpatches
from matplotlib.patches import FancyBboxPatch
from datetime import datetime, timezone, timedelta
from IPython.display import HTML

# ── Physical constants ────────────────────────────────────────
C_KMS = 299_792.458   # speed of light km/s

def signal_delay(dist_km):
    return dist_km / C_KMS

# ── Mission data — explicit columns, no ambiguity ─────────────
# All columns named separately to avoid index confusion

M_YEARS = np.array([
    1961, 1961, 1963,
    1965, 1966,
    1968, 1969, 1969, 1969, 1970,
    1971, 1971, 1972, 1972,
    1981, 1990, 1995, 1998,
    2021, 2021,
    2026
])

M_NAMES = [
    'Freedom 7 (Shepard)',
    'Friendship 7 (Glenn)',
    'Vostok 6 (Tereshkova)',
    'Gemini 4 (White)',
    'Gemini 11 (Conrad/Gordon)',
    'Apollo 8',
    'Apollo 10',
    'Apollo 11',
    'Apollo 12',
    'Apollo 13',
    'Apollo 14',
    'Apollo 15',
    'Apollo 16',
    'Apollo 17',
    'STS-1 (Columbia)',
    'STS-31 (Hubble)',
    'STS-71 (Mir)',
    'ISS Expedition 1',
    'Inspiration4',
    'Axiom-1',
    'Artemis II',
]

M_DISTS = np.array([
    187, 262, 233,
    282, 1_374,
    376_589, 408_950, 384_400, 384_400, 400_171,
    384_400, 384_400, 384_400, 384_400,
    278, 612, 390, 408,
    590, 420,
    406_771,
])

M_PROGRAMS = [
    'Mercury', 'Mercury', 'Vostok',
    'Gemini', 'Gemini',
    'Apollo', 'Apollo', 'Apollo', 'Apollo', 'Apollo',
    'Apollo', 'Apollo', 'Apollo', 'Apollo',
    'Shuttle', 'Shuttle', 'Shuttle', 'ISS',
    'Commercial', 'Commercial',
    'Artemis',
]

M_COLORS = [
    '#475569', '#475569', '#DC2626',
    '#3B82F6', '#3B82F6',
    '#F59E0B', '#F59E0B', '#F59E0B', '#F59E0B', '#EF4444',
    '#F59E0B', '#F59E0B', '#F59E0B', '#F59E0B',
    '#6B7280', '#6B7280', '#6B7280', '#10B981',
    '#8B5CF6', '#8B5CF6',
    '#10B981',
]

M_NOTES = [
    'First American in space — suborbital',
    'First American orbital flight',
    'First woman in space',
    'First American spacewalk',
    'Highest Earth orbit — 1,374 km',
    'First humans to leave Earth orbit',
    'Dress rehearsal — 14km from Moon',
    'First Moon landing',
    'Second Moon landing',
    'Record holder 1970–2026 — emergency return',
    'Third Moon landing',
    'First lunar rover',
    'Highlands landing',
    'Last humans on the Moon until 2026',
    'First Space Shuttle flight',
    'Hubble deployment — highest Shuttle orbit',
    'First Shuttle-Mir docking',
    'First ISS crew',
    'Highest crewed Dragon orbit',
    'First private ISS mission',
    'NEW RECORD — 406,771 km — April 6, 2026',
]

# ── Key constants ─────────────────────────────────────────────
APOLLO_13_KM  = 400_171
ARTEMIS_II_KM = 406_771
MARGIN_KM     = ARTEMIS_II_KM - APOLLO_13_KM
RECORD_GAP    = 2026 - 1970

# ── Validate — no color should be a program name ──────────────
print("=" * 58)
print("   DAY 7 — THE LONGEST JOURNEY")
print("=" * 58)
print()
print("  Validating dataset...")
for i, (nm, col) in enumerate(
        zip(M_NAMES, M_COLORS)):
    if not col.startswith('#'):
        print(f"  ERROR row {i}: {nm} → color='{col}'")
print("  Validation passed ✓")
print()
print(f"  Missions in dataset : {len(M_NAMES)}")
print(f"  Year range          : "
      f"{M_YEARS.min()}–{M_YEARS.max()}")
print(f"  Distance range      : "
      f"{M_DISTS.min():,}–{M_DISTS.max():,} km")
print()
print(f"  Apollo 13 record    : {APOLLO_13_KM:,} km (1970)")
print(f"  Artemis II record   : {ARTEMIS_II_KM:,} km (2026)")
print(f"  New margin          : +{MARGIN_KM:,} km")
print(f"  Gap                 : {RECORD_GAP} years")
print()
print(f"  Signal delays:")
print(f"    ISS (408 km)      : "
      f"{signal_delay(408)*1000:.2f} ms")
print(f"    Apollo 13 record  : "
      f"{signal_delay(APOLLO_13_KM):.3f} s")
print(f"    Artemis II max    : "
      f"{signal_delay(ARTEMIS_II_KM):.3f} s")
print("=" * 58)

# ============================================================
# CELL 2 — Static Distance Comparison Chart (v2)
# Clean labels · inset zoom · Apollo 10 note · fixed LEO panel
# ============================================================

fig, (ax_main, ax_leo) = plt.subplots(
    1, 2, figsize=(18, 11),
    gridspec_kw={'width_ratios': [2.2, 1]}
)
fig.patch.set_facecolor('#0D1117')

# ── sort by distance ──────────────────────────────────────────
sort_idx = np.argsort(M_DISTS)
s_names  = [M_NAMES[i]    for i in sort_idx]
s_dists  = M_DISTS[sort_idx]
s_colors = [M_COLORS[i]   for i in sort_idx]

# ════════════════════════════════════════════════════════════
# LEFT: main log-scale chart
# ════════════════════════════════════════════════════════════
ax_main.set_facecolor('#0D1117')
ax_main.set_title(
    'Maximum distance from Earth — all crewed missions',
    color='white', fontsize=12, pad=12)
ax_main.set_xlabel(
    'Max distance from Earth (km, log scale)',
    color='#94A3B8', fontsize=9)
ax_main.tick_params(
    colors='#94A3B8', labelsize=8)
for sp in ['bottom', 'left']:
    ax_main.spines[sp].set_color('#334155')
for sp in ['top', 'right']:
    ax_main.spines[sp].set_visible(False)
ax_main.grid(axis='x', color='#1E293B',
             lw=0.6, zorder=0)
ax_main.set_xscale('log')

y_pos = np.arange(len(s_names))
ax_main.barh(y_pos, s_dists,
             color=s_colors,
             alpha=0.85, height=0.65,
             zorder=3)

ax_main.set_yticks(y_pos)
ax_main.set_yticklabels(
    s_names, fontsize=7.5,
    color='#94A3B8')
ax_main.set_xlim(100, 1_200_000)
ax_main.set_ylim(-0.5, len(s_names) - 0.3)

# ── zone shading ──────────────────────────────────────────────
ax_main.axvspan(100, 2_000,
                color='#3B82F6',
                alpha=0.04, zorder=1)
ax_main.axvspan(350_000, 450_000,
                color='#F59E0B',
                alpha=0.04, zorder=1)
ax_main.text(150, -0.3,
             'LEO', color='#3B82F6',
             fontsize=7.5, alpha=0.6,
             style='italic', va='bottom')
ax_main.text(
    355_000, 1.5,
    'Lunar\nzone',
    color='#F59E0B',
    fontsize=7.5, alpha=0.6,
    style='italic',
    linespacing=1.3)

# ── selective value labels ────────────────────────────────────
# only label missions that are clearly
# distinct — avoid the crowded Apollo cluster
label_always = {
    'Gemini 11 (Conrad/Gordon)',
    'STS-31 (Hubble)',
    'Freedom 7 (Shepard)',
}
label_lunar = {
    'Apollo 8',
    'Apollo 13',
    'Apollo 10',
    'Artemis II',
}

for i, (nm, dist, col) in enumerate(
        zip(s_names, s_dists, s_colors)):

    if nm in label_always:
        lbl = (f'{dist:,} km'
               if dist < 1000
               else f'{dist/1000:.1f}k km')
        ax_main.text(
            dist * 1.15, i, lbl,
            color=col, fontsize=8,
            va='center',
            fontweight='bold')

    elif nm in label_lunar:
        lbl = f'{dist/1000:.0f}k km'
        # stagger: Apollo 10 above,
        # Apollo 13 below, etc
        y_off = {
            'Apollo 10':  0.45,
            'Artemis II': 0.0,
            'Apollo 13': -0.45,
            'Apollo 8':   0.0,
        }.get(nm, 0)
        ax_main.text(
            dist * 1.15,
            i + y_off, lbl,
            color=col, fontsize=8,
            va='center',
            fontweight='bold')

    else:
        # small grey label for others
        lbl = (f'{dist:,}'
               if dist < 1000
               else f'{dist/1000:.0f}k')
        ax_main.text(
            dist * 1.08, i, lbl,
            color='#475569',
            fontsize=7, va='center')

# ── record lines ──────────────────────────────────────────────
# Apollo 13
ax_main.axvline(
    APOLLO_13_KM,
    color='#EF4444', lw=1.2,
    ls='--', alpha=0.6, zorder=4)
ax_main.text(
    APOLLO_13_KM * 0.72,
    len(s_names) * 0.96,
    'Apollo 13 record\n400,171 km',
    color='#EF4444', fontsize=7.5,
    va='top', ha='right',
    linespacing=1.4)

# Artemis II
ax_main.axvline(
    ARTEMIS_II_KM,
    color='#10B981', lw=1.8,
    alpha=0.8, zorder=4)
ax_main.text(
    ARTEMIS_II_KM * 1.05,
    len(s_names) - 1.5,
    'Artemis II\nNEW RECORD\n406,771 km',
    color='#10B981', fontsize=8,
    va='center', fontweight='bold',
    linespacing=1.4)

# ── Apollo 10 note ────────────────────────────────────────────
# Apollo 10 went to 408,950 km —
# actually FARTHER than Artemis II —
# because the free-return arc after
# the near-Moon pass swung out further.
# Apollo 13 (400,171 km) holds the record
# because that mission's emergency
# return arc swung less far out.
# Artemis II (406,771 km) beats Apollo 13
# but not Apollo 10.

# find Apollo 10 y position
ap10_idx = next(
    i for i, n in enumerate(s_names)
    if 'Apollo 10' in n)

ax_main.annotate(
    '* Apollo 10 (408,950 km)\n'
    '  went further than Artemis II\n'
    '  but Apollo 13 holds the record\n'
    '  (different trajectory type)',
    xy=(408_950, ap10_idx),
    xytext=(1_800, ap10_idx - 3.5),
    color='#94A3B8', fontsize=7,
    linespacing=1.4,
    arrowprops=dict(
        arrowstyle='->',
        color='#94A3B8', lw=0.8),
    bbox=dict(
        boxstyle='round,pad=0.3',
        facecolor='#0F172A',
        edgecolor='#334155',
        alpha=0.9))

# ── legend ────────────────────────────────────────────────────
legend_patches = [
    mpatches.Patch(
        color='#475569',
        label='Mercury / Vostok'),
    mpatches.Patch(
        color='#3B82F6',
        label='Gemini'),
    mpatches.Patch(
        color='#F59E0B',
        label='Apollo'),
    mpatches.Patch(
        color='#EF4444',
        label='Apollo 13 (record holder)'),
    mpatches.Patch(
        color='#6B7280',
        label='Shuttle / ISS'),
    mpatches.Patch(
        color='#8B5CF6',
        label='Commercial'),
    mpatches.Patch(
        color='#10B981',
        label='Artemis II (new record)'),
]
ax_main.legend(
    handles=legend_patches,
    facecolor='#1E293B',
    edgecolor='#334155',
    labelcolor='white', fontsize=8,
    loc='lower right')

# ════════════════════════════════════════
# INSET: linear zoom on top 3
# ════════════════════════════════════════
ax_inset = fig.add_axes(
    [0.07, 0.72, 0.16, 0.18])
ax_inset.set_facecolor('#0F172A')
for sp in ax_inset.spines.values():
    sp.set_color('#334155')
ax_inset.tick_params(
    colors='#475569', labelsize=6)
ax_inset.grid(axis='x',
              color='#1E293B',
              lw=0.5, zorder=0)

top3_data = [
    ('Apollo 13\n(record 1970)',
     400_171, '#EF4444'),
    ('Artemis II\n(new record)',
     406_771, '#10B981'),
    ('Apollo 10\n(1969)',
     408_950, '#F59E0B'),
]
t3_names  = [d[0] for d in top3_data]
t3_dists  = [d[1] for d in top3_data]
t3_colors = [d[2] for d in top3_data]

ax_inset.barh(
    [0, 1, 2], t3_dists,
    color=t3_colors,
    alpha=0.85, height=0.55,
    zorder=3)
ax_inset.set_xlim(396_000, 412_000)
ax_inset.set_yticks([0, 1, 2])
ax_inset.set_yticklabels(
    t3_names, fontsize=5.5,
    color='white',
    linespacing=1.2)
ax_inset.set_title(
    'Top 3 — linear scale',
    color='white', fontsize=6.5,
    pad=4)
ax_inset.xaxis.set_major_formatter(
    plt.FuncFormatter(
        lambda x, _:
        f'{x/1000:.0f}k'))

# value labels on inset
for i, (dist, col) in enumerate(
        zip(t3_dists, t3_colors)):
    ax_inset.text(
        dist + 200, i,
        f'{dist:,}',
        color=col, fontsize=5.5,
        va='center',
        fontweight='bold')

# border around inset
for sp in ax_inset.spines.values():
    sp.set_visible(True)
    sp.set_color('#334155')

# ════════════════════════════════════════
# RIGHT: LEO panel — exclude Gemini 11
# it was a high-orbit experiment,
# not representative LEO
# ════════════════════════════════════════
ax_leo.set_facecolor('#0D1117')
ax_leo.set_title(
    'LEO missions (≤ 700 km)\n'
    'Shuttle · ISS · Commercial era',
    color='white', fontsize=10, pad=8)
ax_leo.set_xlabel(
    'Distance (km)',
    color='#94A3B8', fontsize=9)
ax_leo.tick_params(
    colors='#94A3B8', labelsize=8)
for sp in ['bottom', 'left']:
    ax_leo.spines[sp]\
          .set_color('#334155')
for sp in ['top', 'right']:
    ax_leo.spines[sp]\
          .set_visible(False)
ax_leo.grid(axis='x',
            color='#1E293B',
            lw=0.6, zorder=0)

# filter: LEO only, exclude Gemini 11
leo_mask = np.array([
    d <= 700 for d in s_dists])
leo_names  = [n for n, m in
              zip(s_names, leo_mask)
              if m]
leo_dists  = s_dists[leo_mask]
leo_colors = [c for c, m in
              zip(s_colors, leo_mask)
              if m]

y_leo = np.arange(len(leo_names))
ax_leo.barh(
    y_leo, leo_dists,
    color=leo_colors,
    alpha=0.85, height=0.65,
    zorder=3)

for i, (dist, col) in enumerate(
        zip(leo_dists, leo_colors)):
    ax_leo.text(
        dist + 8, i,
        f'{dist:.0f} km',
        color=col, fontsize=8,
        va='center',
        fontweight='bold')

ax_leo.set_yticks(y_leo)
ax_leo.set_yticklabels(
    leo_names, fontsize=8.5,
    color='#94A3B8')

# ISS reference line
ax_leo.axvline(
    408, color='#10B981',
    lw=1.0, ls=':', alpha=0.6)
ax_leo.text(
    415, 3.5,
    'ISS ~408 km',
    color='#10B981', fontsize=7.5,
    va='center')

ax_leo.set_xlim(0, 750)

# Gemini 11 footnote
ax_leo.text(
    10, -0.8,
    '* Gemini 11 (1,374 km) excluded —\n'
    '  high-orbit experiment, not LEO',
    color='#334155', fontsize=7,
    style='italic', linespacing=1.4)

# ── suptitle ──────────────────────────────────────────────────
plt.suptitle(
    'Human Spaceflight — '
    'Distance from Earth\n'
    '1961 to 2026  ·  '
    'Sources: NASA, ESA, Roscosmos',
    color='white', fontsize=12,
    fontweight='bold', y=1.01)

plt.tight_layout()
plt.savefig(
    'artemis_distance_comparison.png',
    dpi=120, facecolor='#0D1117',
    bbox_inches='tight')
plt.show()
print("Saved: artemis_distance_comparison.png")

# ============================================================
# CELL 3 — Animated Historical Timeline
# ============================================================
fig, (ax_anim, ax_info) = plt.subplots(
    1, 2, figsize=(15, 8),
    gridspec_kw={'width_ratios': [1.6, 1]}
)
fig.patch.set_facecolor('#0D1117')

# ── LEFT: animated scatter ────────────────────────────────────
ax_anim.set_facecolor('#0D1117')
ax_anim.set_title(
    'Human spaceflight — distance record progression\n'
    '1961 to 2026',
    color='white', fontsize=11, pad=10)
ax_anim.set_xlabel('Year',
                   color='#94A3B8', fontsize=9)
ax_anim.set_ylabel(
    'Max distance from Earth (km)',
    color='#94A3B8', fontsize=9)
ax_anim.tick_params(colors='#94A3B8', labelsize=8)
for sp in ['bottom', 'left']:
    ax_anim.spines[sp].set_color('#334155')
for sp in ['top', 'right']:
    ax_anim.spines[sp].set_visible(False)
ax_anim.grid(color='#1E293B', lw=0.6, zorder=0)
ax_anim.set_yscale('log')
ax_anim.set_xlim(1959, 2028)
ax_anim.set_ylim(100, 600_000)

# zone bands
ax_anim.axhspan(100, 2000,
                color='#3B82F6', alpha=0.05)
ax_anim.axhspan(350_000, 450_000,
                color='#F59E0B', alpha=0.05)
ax_anim.text(1960.5, 400, 'LEO',
             color='#3B82F6', fontsize=8,
             alpha=0.6, style='italic')
ax_anim.text(1960.5, 380_000, 'Lunar distance',
             color='#F59E0B', fontsize=8,
             alpha=0.6, style='italic')

# Apollo 13 record reference line
ax_anim.axhline(APOLLO_13_KM,
                color='#EF4444', lw=1.0,
                ls='--', alpha=0.4)
ax_anim.text(1960.5, APOLLO_13_KM * 1.05,
             'Apollo 13 record (1970)',
             color='#EF4444', fontsize=7.5,
             alpha=0.6)

# dynamic elements
scatter_pts = ax_anim.scatter(
    [], [], s=60, c='white', zorder=6,
    edgecolors='#0D1117', linewidths=0.8)

record_line, = ax_anim.plot(
    [], [], color='#EF4444',
    lw=1.5, ls='--', alpha=0.6,
    zorder=4)

year_text = ax_anim.text(
    2020, 120, '',
    color='#1E293B', fontsize=32,
    fontweight='bold', ha='center',
    zorder=3)

new_record_text = ax_anim.text(
    1993, 200_000, '',
    color='#10B981', fontsize=12,
    fontweight='bold', ha='center',
    zorder=7)

# ── RIGHT: info panel ─────────────────────────────────────────
ax_info.set_facecolor('#0D1117')
ax_info.axis('off')
ax_info.set_title('Current mission',
                  color='white',
                  fontsize=10, pad=8)

info_name  = ax_info.text(
    0.5, 0.88, '',
    transform=ax_info.transAxes,
    color='white', fontsize=11,
    fontweight='bold', ha='center')

info_year  = ax_info.text(
    0.5, 0.78, '',
    transform=ax_info.transAxes,
    color='#94A3B8', fontsize=9,
    ha='center')

info_dist  = ax_info.text(
    0.5, 0.65, '',
    transform=ax_info.transAxes,
    color='#F59E0B', fontsize=15,
    fontweight='bold', ha='center')

ax_info.text(
    0.5, 0.57, 'km from Earth',
    transform=ax_info.transAxes,
    color='#475569', fontsize=8,
    ha='center')

info_prog  = ax_info.text(
    0.5, 0.48, '',
    transform=ax_info.transAxes,
    color='#64748B', fontsize=8,
    ha='center')

info_note  = ax_info.text(
    0.5, 0.36, '',
    transform=ax_info.transAxes,
    color='#64748B', fontsize=8,
    ha='center', linespacing=1.5)

info_delay = ax_info.text(
    0.5, 0.24, '',
    transform=ax_info.transAxes,
    color='#3B82F6', fontsize=8,
    ha='center')

ax_info.add_patch(FancyBboxPatch(
    (0.05, 0.05), 0.9, 0.12,
    boxstyle='round,pad=0.02',
    facecolor='#0F172A',
    edgecolor='#334155',
    transform=ax_info.transAxes,
    zorder=2))

record_holder_txt = ax_info.text(
    0.5, 0.11, 'Record: —',
    transform=ax_info.transAxes,
    color='#EF4444', fontsize=7.5,
    ha='center', fontweight='bold',
    linespacing=1.4)

# ── sort by year for animation ────────────────────────────────
sort_yr   = np.argsort(M_YEARS)
a_years   = M_YEARS[sort_yr]
a_names   = [M_NAMES[i]    for i in sort_yr]
a_dists   = M_DISTS[sort_yr]
a_colors  = [M_COLORS[i]   for i in sort_yr]
a_notes   = [M_NOTES[i]    for i in sort_yr]
a_programs= [M_PROGRAMS[i] for i in sort_yr]

N = len(a_years)

# running record
run_rec  = []
run_name = []
cur      = 0
cur_nm   = '—'
for d, nm in zip(a_dists, a_names):
    if d > cur:
        cur    = d
        cur_nm = nm
    run_rec.append(cur)
    run_name.append(cur_nm)

# accumulated lists for scatter
xs, ys, cs, ss = [], [], [], []

def init():
    scatter_pts.set_offsets(
        np.empty((0, 2)))
    scatter_pts.set_array(
        np.array([]))
    record_line.set_data([], [])
    year_text.set_text('')
    new_record_text.set_text('')
    info_name.set_text('')
    info_year.set_text('')
    info_dist.set_text('')
    info_prog.set_text('')
    info_note.set_text('')
    info_delay.set_text('')
    record_holder_txt.set_text(
        'Record: —')
    return (scatter_pts, record_line,
            year_text, new_record_text,
            info_name, info_year,
            info_dist, info_prog,
            info_note, info_delay,
            record_holder_txt)

def update(frame):
    idx = min(frame, N - 1)
    yr  = a_years[idx]
    nm  = a_names[idx]
    dst = a_dists[idx]
    col = a_colors[idx]
    nt  = a_notes[idx]
    prg = a_programs[idx]
    rec = run_rec[idx]
    rnm = run_name[idx]

    xs.append(yr)
    ys.append(dst)
    cs.append(col)
    ss.append(max(30, np.log10(dst) * 22))

    offsets = np.column_stack([xs, ys])
    scatter_pts.set_offsets(offsets)
    scatter_pts.set_sizes(ss)
    scatter_pts.set_color(cs)

    # record line — horizontal step
    if idx > 0:
        rx = [a_years[0]]
        ry = [run_rec[0]]
        for k in range(1, idx + 1):
            rx.append(a_years[k])
            ry.append(run_rec[k-1])
            rx.append(a_years[k])
            ry.append(run_rec[k])
        rx.append(2027)
        ry.append(run_rec[idx])
        record_line.set_data(rx, ry)

    year_text.set_text(str(yr))

    # new record flash
    is_new = (idx > 0 and
              dst > run_rec[idx - 1])
    new_record_text.set_text(
        '★ NEW RECORD ★' if is_new else '')
    new_record_text.set_color(col)

    # info panel
    info_name.set_text(nm)
    info_name.set_color(col)
    info_year.set_text(str(yr))
    info_dist.set_text(f'{dst:,}')
    info_dist.set_color(col)
    info_prog.set_text(f'Program: {prg}')
    # wrap note
    words = nt.split()
    lines, line = [], []
    for w in words:
        line.append(w)
        if len(' '.join(line)) > 28:
            lines.append(' '.join(line[:-1]))
            line = [w]
    lines.append(' '.join(line))
    info_note.set_text('\n'.join(lines))

    delay_s = signal_delay(dst)
    delay_str = (f'{delay_s*1000:.1f} ms'
                 if delay_s < 0.01
                 else f'{delay_s:.3f} s')
    info_delay.set_text(
        f'Signal delay: {delay_str}')

    record_holder_txt.set_text(
        f'Record: {rec:,} km\n{rnm}')

    return (scatter_pts, record_line,
            year_text, new_record_text,
            info_name, info_year,
            info_dist, info_prog,
            info_note, info_delay,
            record_holder_txt)

N_FRAMES = N + 5
anim3 = animation.FuncAnimation(
    fig, update, frames=N_FRAMES,
    init_func=init,
    interval=600, blit=True)

plt.tight_layout()
anim3.save(
    'artemis_distance_timeline.gif',
    writer='pillow', fps=2, dpi=100,
    savefig_kwargs={'facecolor': '#0D1117'})
print("Saved: artemis_distance_timeline.gif")
HTML(anim3.to_jshtml())

# ============================================================
# CELL 4 — The 54-Year Gap Visualisation
# ============================================================
fig, (ax_top, ax_bot) = plt.subplots(
    2, 1, figsize=(14, 10),
    gridspec_kw={'height_ratios': [1.6, 1]}
)
fig.patch.set_facecolor('#0D1117')

for ax in [ax_top, ax_bot]:
    ax.set_facecolor('#0D1117')
    ax.tick_params(colors='#94A3B8',
                   labelsize=8)
    for sp in ['bottom', 'left']:
        ax.spines[sp].set_color('#334155')
    for sp in ['top', 'right']:
        ax.spines[sp].set_visible(False)
    ax.grid(color='#1E293B',
            lw=0.6, zorder=0)

# ── TOP: full timeline ────────────────────────────────────────
ax_top.set_title(
    'Human spaceflight distance — '
    'the 54-year record gap',
    color='white', fontsize=12, pad=10)
ax_top.set_ylabel(
    'Max distance from Earth (km)',
    color='#94A3B8', fontsize=9)
ax_top.set_yscale('log')

# era shading
ax_top.axvspan(1961, 1973,
               color='#F59E0B', alpha=0.05)
ax_top.axvspan(1973, 2026,
               color='#334155', alpha=0.08)
ax_top.axvspan(2026, 2028,
               color='#10B981', alpha=0.05)

ax_top.text(1967, 430_000, 'Apollo era',
            color='#F59E0B', fontsize=8.5,
            style='italic', alpha=0.8)
ax_top.text(1998, 430_000,
            '54 YEARS — HUMANS NEVER LEFT LEO',
            color='#475569', fontsize=8.5,
            style='italic', ha='center',
            alpha=0.8)
ax_top.text(2026.5, 430_000, 'Artemis',
            color='#10B981', fontsize=8.5,
            style='italic', alpha=0.8)

# scatter all missions
for yr, dist, col in zip(
        M_YEARS, M_DISTS, M_COLORS):
    ax_top.scatter(
        yr, dist, color=col,
        s=max(30, np.log10(dist) * 18),
        zorder=5, alpha=0.9,
        edgecolors='#0D1117',
        linewidths=0.8)

# running record step line
rec_yrs, rec_dsts = [], []
cur = 0
for yr, dist in sorted(
        zip(M_YEARS, M_DISTS)):
    if dist > cur:
        cur = dist
        rec_yrs.append(yr)
        rec_dsts.append(dist)

# build step line
rx, ry = [], []
for i in range(len(rec_yrs)):
    rx.append(rec_yrs[i])
    ry.append(rec_dsts[i])
    if i < len(rec_yrs) - 1:
        rx.append(rec_yrs[i+1])
        ry.append(rec_dsts[i])
rx.append(2027)
ry.append(rec_dsts[-1])

ax_top.plot(rx, ry, color='#EF4444',
            lw=1.5, ls='--', alpha=0.6,
            zorder=4,
            label='Distance record')

# annotations
annotations = [
    (1968, 376_589,
     'Apollo 8\nFirst beyond LEO',
     '#F59E0B', -4, 1.5),
    (1970, 400_171,
     'Apollo 13\nRecord 1970',
     '#EF4444', 1, 0.4),
    (1966, 1_374,
     'Gemini 11\n1,374 km',
     '#3B82F6', 1, 0.1),
    (2026, 406_771,
     'Artemis II\nNEW RECORD',
     '#10B981', -5, 1.5),
]
for yr, dist, label, col, dx, dy in \
        annotations:
    ax_top.annotate(
        label,
        xy=(yr, dist),
        xytext=(yr + dx, dist * dy
                if dy > 0 else dist + 5000),
        color=col, fontsize=8,
        linespacing=1.4,
        arrowprops=dict(
            arrowstyle='->',
            color=col, lw=0.8))

# 54-year bracket
ax_top.annotate('',
    xy=(2026, APOLLO_13_KM * 0.5),
    xytext=(1970, APOLLO_13_KM * 0.5),
    arrowprops=dict(
        arrowstyle='<->',
        color='#475569', lw=1.5))
ax_top.text(1998, APOLLO_13_KM * 0.38,
            '54 years',
            color='#475569', fontsize=11,
            ha='center', fontweight='bold')

ax_top.set_xlim(1959, 2028)
ax_top.set_ylim(100, 600_000)
ax_top.legend(facecolor='#1E293B',
              edgecolor='#334155',
              labelcolor='white',
              fontsize=8, loc='lower right')
ax_top.set_xticklabels([])

# ── BOTTOM: LEO detail ────────────────────────────────────────
ax_bot.set_title(
    'LEO missions during the gap — '
    'humanity never exceeded 612 km (1973–2026)',
    color='white', fontsize=10, pad=8)
ax_bot.set_xlabel('Year',
                  color='#94A3B8',
                  fontsize=9)
ax_bot.set_ylabel('Max distance (km)',
                  color='#94A3B8',
                  fontsize=9)

leo_gap  = (M_YEARS >= 1973) & \
           (M_DISTS  < 2000)
for yr, dist, col in zip(
        M_YEARS[leo_gap],
        M_DISTS[leo_gap],
        [M_COLORS[i] for i in
         range(len(M_COLORS))
         if leo_gap[i]]):
    ax_bot.scatter(yr, dist,
                   color=col, s=45,
                   alpha=0.85, zorder=4,
                   edgecolors='#0D1117',
                   linewidths=0.8)

ax_bot.axhline(612, color='#6B7280',
               lw=1.0, ls=':',
               alpha=0.6)
ax_bot.text(1974, 640,
            'Max LEO altitude '
            '(STS-31, 612 km)',
            color='#6B7280', fontsize=7.5)
ax_bot.axhline(408, color='#10B981',
               lw=1.0, ls=':',
               alpha=0.5)
ax_bot.text(1974, 370,
            'ISS altitude ~408 km',
            color='#10B981', fontsize=7.5)

ax_bot.text(1998, 720,
            'Shuttle · Mir · ISS — '
            'extraordinary achievements, '
            'all within 612 km of Earth',
            color='#475569', fontsize=8,
            ha='center', style='italic')

ax_bot.set_xlim(1972, 2028)
ax_bot.set_ylim(0, 800)

plt.suptitle(
    'The 54-Year Gap — '
    'Apollo 13 (1970) to Artemis II (2026)\n'
    'Sources: NASA  ·  ESA  ·  Roscosmos',
    color='white', fontsize=11,
    fontweight='bold', y=1.01)

plt.tight_layout()
plt.savefig('artemis_54year_gap.png',
            dpi=120, facecolor='#0D1117')
plt.show()
print("Saved: artemis_54year_gap.png")

# ============================================================
# CELL 5 — Artemis II Distance Profile + Record Moment
# ============================================================
from datetime import datetime, timezone

LAUNCH_UTC = datetime(
    2026, 4, 1, 22, 35,
    tzinfo=timezone.utc)

t_hours = np.linspace(0, 240, 5000)

def orion_dist_km(t):
    """Distance from Earth surface [km]."""
    d = np.zeros_like(t)
    for i, ti in enumerate(t):
        if ti < 25.6:
            d[i] = 185
        elif ti < 114:
            frac  = (ti - 25.6) / \
                    (114 - 25.6)
            ease  = 3*frac**2 - 2*frac**3
            d[i]  = 185 + \
                    (384_400 - 185) * ease
        elif ti < 120:
            frac  = (ti - 114) / 6
            d[i]  = 384_400 - \
                    (384_400 - 6_540) * \
                    np.sin(frac * np.pi)
        elif ti < 132:
            frac  = (ti - 120) / 12
            d[i]  = 6_540 + \
                    (406_771 - 6_540) * frac
        elif ti < 228:
            frac  = (ti - 132) / 96
            d[i]  = 406_771 * \
                    (1 - frac**1.5)
        else:
            frac  = (ti - 228) / 12
            d[i]  = max(
                406_771 * 0.01 *
                (1 - frac), 185)
    return d

dist_km = orion_dist_km(t_hours)

# key MET times
def utc_to_met(dt):
    return (dt - LAUNCH_UTC)\
           .total_seconds() / 3600

MET_RECORD   = utc_to_met(datetime(
    2026, 4, 6, 17, 57,
    tzinfo=timezone.utc))
MET_MAX      = utc_to_met(datetime(
    2026, 4, 6, 23, 7,
    tzinfo=timezone.utc))
MET_BLACKOUT = utc_to_met(datetime(
    2026, 4, 6, 22, 44,
    tzinfo=timezone.utc))

# ── Figure ────────────────────────────────────────────────────
fig, (ax_dist, ax_comp) = plt.subplots(
    1, 2, figsize=(16, 8),
    gridspec_kw={'width_ratios': [1.6, 1]}
)
fig.patch.set_facecolor('#0D1117')

for ax in [ax_dist, ax_comp]:
    ax.set_facecolor('#0D1117')
    ax.tick_params(colors='#94A3B8',
                   labelsize=8)
    for sp in ['bottom', 'left']:
        ax.spines[sp].set_color('#334155')
    for sp in ['top', 'right']:
        ax.spines[sp].set_visible(False)
    ax.grid(color='#1E293B',
            lw=0.6, zorder=0)

# ── LEFT: distance profile ────────────────────────────────────
ax_dist.set_title(
    'Artemis II — distance from Earth\n'
    'Full mission with record moment',
    color='white', fontsize=11, pad=10)
ax_dist.set_xlabel(
    'Mission elapsed time (hours)',
    color='#94A3B8', fontsize=9)
ax_dist.set_ylabel(
    'Distance from Earth (km)',
    color='#94A3B8', fontsize=9)

phases = [
    (0,    25.6, '#3B82F6', 'Earth orbit'),
    (25.6, 114,  '#F59E0B', 'Outbound'),
    (114,  132,  '#EC4899', 'Flyby'),
    (132,  228,  '#10B981', 'Return'),
    (228,  240,  '#3B82F6', 'Reentry'),
]
for t0, t1, col, label in phases:
    ax_dist.axvspan(t0, t1,
                    alpha=0.06, color=col)
    ax_dist.text((t0+t1)/2, 425_000,
                 label, color=col,
                 fontsize=7.5, ha='center',
                 style='italic', alpha=0.7)

ax_dist.plot(t_hours, dist_km,
             color='#3B82F6', lw=2.5,
             zorder=5)
ax_dist.fill_between(
    t_hours, dist_km, 0,
    color='#3B82F6', alpha=0.06)

# record lines
ax_dist.axhline(APOLLO_13_KM,
                color='#EF4444',
                lw=1.2, ls='--',
                alpha=0.7)
ax_dist.text(2, APOLLO_13_KM * 1.03,
             f'Apollo 13 record  '
             f'{APOLLO_13_KM:,} km',
             color='#EF4444', fontsize=7.5)

ax_dist.axhline(ARTEMIS_II_KM,
                color='#10B981',
                lw=1.2, ls='--',
                alpha=0.7)
ax_dist.text(2, ARTEMIS_II_KM * 1.03,
             f'Artemis II max  '
             f'{ARTEMIS_II_KM:,} km',
             color='#10B981',
             fontsize=7.5,
             fontweight='bold')

# record moment star
ax_dist.axvline(MET_RECORD,
                color='#EF4444',
                lw=1.5, ls=':',
                alpha=0.8)
ax_dist.plot(MET_RECORD, APOLLO_13_KM,
             '*', color='#EF4444',
             ms=14, zorder=7,
             markeredgecolor='#0D1117',
             markeredgewidth=0.8)
ax_dist.text(MET_RECORD + 1,
             APOLLO_13_KM - 30_000,
             f'Record broken\n'
             f'T+{MET_RECORD:.0f}h\n'
             f'1:57 PM EDT',
             color='#EF4444',
             fontsize=7.5,
             linespacing=1.4)

# max distance
ax_dist.axvline(MET_MAX, color='#10B981',
                lw=1.5, ls=':',
                alpha=0.8)
ax_dist.plot(MET_MAX, ARTEMIS_II_KM,
             'o', color='#10B981',
             ms=10, zorder=7,
             markeredgecolor='#0D1117',
             markeredgewidth=0.8)
ax_dist.text(MET_MAX + 1,
             ARTEMIS_II_KM + 8_000,
             f'Max distance\n'
             f'T+{MET_MAX:.0f}h\n'
             f'7:07 PM EDT',
             color='#10B981',
             fontsize=7.5,
             linespacing=1.4)

# blackout zone
ax_dist.axvspan(MET_BLACKOUT,
                MET_BLACKOUT + 0.67,
                color='#EF4444',
                alpha=0.15)
ax_dist.text(MET_BLACKOUT + 0.33,
             40_000,
             'Blackout\n~40min',
             color='#EF4444',
             fontsize=7, ha='center',
             linespacing=1.3)

ax_dist.set_xlim(0, 240)
ax_dist.set_ylim(0, 450_000)
ax_dist.yaxis.set_major_formatter(
    plt.FuncFormatter(
        lambda x, _:
        f'{x/1000:.0f}k'))

# ── RIGHT: mission comparison bars ───────────────────────────
ax_comp.set_title(
    'Artemis II vs key missions',
    color='white', fontsize=10, pad=8)
ax_comp.set_xlabel('Distance (km)',
                   color='#94A3B8',
                   fontsize=9)

comp_data = [
    ('ISS orbit',         408,
     '#10B981'),
    ('Gemini 11',         1_374,
     '#3B82F6'),
    ('Apollo 8',          376_589,
     '#F59E0B'),
    ('Apollo 11',         384_400,
     '#F59E0B'),
    ('Apollo 13 record',  400_171,
     '#EF4444'),
    ('Apollo 10',         408_950,
     '#F59E0B'),
    ('Artemis II',        406_771,
     '#10B981'),
]
c_names = [c[0] for c in comp_data]
c_dists = [c[1] for c in comp_data]
c_cols  = [c[2] for c in comp_data]

y_c = np.arange(len(c_names))
ax_comp.barh(y_c, c_dists,
             color=c_cols,
             alpha=0.85, height=0.6,
             zorder=3)

for i, (dist, col) in enumerate(
        zip(c_dists, c_cols)):
    lbl = (f'{dist:,} km'
           if dist >= 1000
           else f'{dist} km')
    ax_comp.text(dist + 3000, i, lbl,
                 color=col, fontsize=8,
                 va='center',
                 fontweight='bold')

ax_comp.set_yticks(y_c)
ax_comp.set_yticklabels(
    c_names, fontsize=8.5,
    color='#94A3B8')
ax_comp.set_xlim(0, 500_000)
ax_comp.xaxis.set_major_formatter(
    plt.FuncFormatter(
        lambda x, _:
        f'{x/1000:.0f}k'))

plt.suptitle(
    'Artemis II — Distance Record Profile\n'
    'First humans beyond LEO since 1972  ·  '
    'Record held by Apollo 13 for 54 years',
    color='white', fontsize=11,
    fontweight='bold', y=1.01)

plt.tight_layout()
plt.savefig('artemis_distance_profile.png',
            dpi=120, facecolor='#0D1117')
plt.show()
print("Saved: artemis_distance_profile.png")

# ============================================================
# CELL 6 — Day 7 Summary Dashboard
# ============================================================
now_utc = datetime.now(timezone.utc)

fig = plt.figure(figsize=(20, 12))
fig.patch.set_facecolor('#0D1117')
ax  = fig.add_axes([0, 0, 1, 1])
ax.set_xlim(0, 20)
ax.set_ylim(0, 12)
ax.axis('off')
ax.set_facecolor('#0D1117')

def card(x, y, w, h,
         fc='#1E293B', ec='#334155',
         lw=0.8):
    ax.add_patch(FancyBboxPatch(
        (x, y), w, h,
        boxstyle='round,pad=0.08',
        facecolor=fc, edgecolor=ec,
        linewidth=lw, zorder=2))

def txt(x, y, s, **kw):
    kw.setdefault('color', 'white')
    kw.setdefault('fontsize', 10)
    kw.setdefault('zorder', 4)
    kw.setdefault('va', 'center')
    ax.text(x, y, s, **kw)

def hln(x0, x1, y,
        col='#1E293B', lw=0.7):
    ax.plot([x0, x1], [y, y],
            color=col, lw=lw, zorder=3)

# ── HEADER ────────────────────────────────────────────────────
card(0.25, 10.7, 19.5, 1.1,
     fc='#0F172A', ec='#1E3A5C')
txt(10.0, 11.35,
    'DAY 7 — THE LONGEST JOURNEY: '
    'HUMAN SPACEFLIGHT DISTANCE RECORD',
    fontsize=15, fontweight='bold',
    ha='center')
txt(10.0, 10.97,
    f'Code Beyond the Earth  ·  '
    f'April 7, 2026  ·  '
    f'Artemis II return coast  ·  '
    f'{now_utc.strftime("%H:%M UTC")}',
    fontsize=9, ha='center',
    color='#475569')

# ── ROW 1 — metrics ───────────────────────────────────────────
metrics = [
    ('Artemis II max',
     '406,771', 'km from Earth',
     '#10B981'),
    ('Previous record',
     '400,171', 'km  Apollo 13 (1970)',
     '#EF4444'),
    ('New margin',
     f'+{MARGIN_KM:,}', 'km beyond Apollo 13',
     '#F59E0B'),
    ('Record held for',
     str(RECORD_GAP), 'years  (1970–2026)',
     '#EC4899'),
    ('Signal delay at max',
     '1.357', 'seconds one-way',
     '#3B82F6'),
]
cw = 3.6
for i, (label, val, unit, col) in \
        enumerate(metrics):
    bx = 0.25 + i * (cw + 0.25)
    card(bx, 9.25, cw, 1.25,
         fc='#0F172A', ec=col)
    txt(bx + cw/2, 10.15, label,
        fontsize=8.5, color='#64748B',
        ha='center')
    txt(bx + cw/2, 9.78, val,
        fontsize=16, fontweight='bold',
        color=col, ha='center')
    txt(bx + cw/2, 9.42, unit,
        fontsize=8, color='#475569',
        ha='center')

# ── ROW 2 ─────────────────────────────────────────────────────
CW   = 6.2
CGAP = 0.25
CY0  = 5.05
CH   = 4.0
CY1  = CY0 + CH
c1x  = 0.25
c2x  = c1x + CW + CGAP
c3x  = c2x + CW + CGAP

card(c1x, CY0, CW, CH)
card(c2x, CY0, CW, CH)
card(c3x, CY0, CW, CH)

# ── CARD 1: mini distance profile ────────────────────────────
txt(c1x + CW/2, CY1 - 0.3,
    'Artemis II distance profile',
    fontsize=9.5, fontweight='bold',
    ha='center')

ax_m = fig.add_axes([
    (c1x + 0.25) / 20,
    (CY0 + 0.85) / 12,
    (CW - 0.5)  / 20,
    (CH - 1.5)  / 12
])
ax_m.set_facecolor('#0D1117')
ax_m.tick_params(colors='#475569',
                 labelsize=6.5)
for sp in ['bottom', 'left']:
    ax_m.spines[sp].set_color('#334155')
for sp in ['top', 'right']:
    ax_m.spines[sp].set_visible(False)
ax_m.grid(color='#1E293B',
          lw=0.5, zorder=0)

ax_m.plot(t_hours, dist_km,
          color='#3B82F6', lw=2.0,
          zorder=4)
ax_m.axhline(APOLLO_13_KM,
             color='#EF4444', lw=1.0,
             ls='--', alpha=0.7)
ax_m.axhline(ARTEMIS_II_KM,
             color='#10B981', lw=1.0,
             ls='--', alpha=0.7)
ax_m.plot(MET_RECORD, APOLLO_13_KM,
          '*', color='#EF4444',
          ms=10, zorder=6)
ax_m.plot(MET_MAX, ARTEMIS_II_KM,
          'o', color='#10B981',
          ms=8, zorder=6)
ax_m.set_xlim(0, 240)
ax_m.set_ylim(0, 450_000)
ax_m.yaxis.set_major_formatter(
    plt.FuncFormatter(
        lambda x, _: f'{x/1000:.0f}k'))
ax_m.set_xlabel('Hours',
                color='#475569',
                fontsize=6)
ax_m.set_ylabel('km', color='#475569',
                fontsize=6)

card(c1x + 0.2, CY0 + 0.18,
     CW - 0.4, 0.55,
     fc='#0F172A', ec='#334155')
txt(c1x + CW/2, CY0 + 0.46,
    f'★ = record broken  '
    f'●  = mission max  '
    f'gap = +{MARGIN_KM:,} km',
    fontsize=7.5, color='#64748B',
    ha='center')

# ── CARD 2: record holders timeline ──────────────────────────
txt(c2x + CW/2, CY1 - 0.3,
    'Distance record — all holders',
    fontsize=9.5, fontweight='bold',
    ha='center')

holders = [
    ('1961', 'Vostok 1 (Gagarin)',
     '315 km',
     'First human in space',
     '#DC2626'),
    ('1966', 'Gemini 11',
     '1,374 km',
     'Highest Earth orbit',
     '#3B82F6'),
    ('1968', 'Apollo 8',
     '376,589 km',
     'First beyond Earth orbit',
     '#F59E0B'),
    ('1970', 'Apollo 13',
     '400,171 km',
     'Held record 54 years',
     '#EF4444'),
    ('2026', 'Artemis II',
     '406,771 km',
     'Current record  ✓',
     '#10B981'),
]
for j, (yr, nm, dist,
        note, col) in enumerate(holders):
    ry = CY1 - 0.88 - j * 0.60

    ax.plot(c2x + 0.35, ry, 'o',
            color=col, ms=8, zorder=5,
            markeredgecolor='#0D1117',
            markeredgewidth=0.8)

    if j < len(holders) - 1:
        ax.plot([c2x + 0.35,
                 c2x + 0.35],
                [ry - 0.08,
                 ry - 0.52],
                color='#334155',
                lw=0.8, zorder=3)

    txt(c2x + 0.55, ry + 0.06,
        f'{yr}  {nm}',
        fontsize=8.5, color=col,
        fontweight='bold', ha='left')
    txt(c2x + 0.55, ry - 0.15,
        f'{dist}  ·  {note}',
        fontsize=7.5, color='#475569',
        ha='left')

card(c2x + 0.2, CY0 + 0.18,
     CW - 0.4, 0.75,
     fc='#0F172A', ec='#334155')
txt(c2x + CW/2, CY0 + 0.56,
    'Five records in 65 years.\n'
    'Four in a single decade (1961–1970).',
    fontsize=8.5, ha='center',
    color='#64748B', linespacing=1.5)

# ── CARD 3: crew quotes ───────────────────────────────────────
txt(c3x + CW/2, CY1 - 0.3,
    'The human moment',
    fontsize=9.5, fontweight='bold',
    ha='center')

quotes = [
    ('Jeremy Hansen  (record moment)',
     '"It is blowing my mind what you\n'
     ' can see with the naked eye from\n'
     ' the Moon right now."',
     '#3B82F6'),
    ('Victor Glover  (solar eclipse)',
     '"It just looks unreal. You can see\n'
     ' the surface against the Earthshine.\n'
     ' The strangest looking thing."',
     '#F59E0B'),
    ('Jeremy Hansen  (crater naming)',
     '"We lost a loved one. Her name was\n'
     ' Carroll... It\'s a bright spot\n'
     ' on the moon."',
     '#EC4899'),
]
for j, (person, quote, col) in \
        enumerate(quotes):
    ry = CY1 - 1.0 - j * 1.05
    txt(c3x + 0.3, ry, person,
        fontsize=8, color=col,
        fontweight='bold', ha='left')
    txt(c3x + 0.3, ry - 0.48,
        quote, fontsize=7.5,
        color='#94A3B8', ha='left',
        linespacing=1.4, style='italic')
    if j < len(quotes) - 1:
        hln(c3x + 0.2,
            c3x + CW - 0.2,
            ry - 0.85,
            col='#1E293B')

# ── ROW 3: distance strip ─────────────────────────────────────
card(0.25, 0.85, 19.5, 4.0)
txt(10.0, 4.62,
    'All crewed missions — '
    'max distance from Earth (log scale)',
    fontsize=10, fontweight='bold',
    ha='center')

ax_strip = fig.add_axes([
    0.04, 0.09, 0.92, 0.255
])
ax_strip.set_facecolor('#0D1117')
ax_strip.tick_params(
    colors='#475569', labelsize=7.5)
for sp in ['bottom', 'left']:
    ax_strip.spines[sp]\
            .set_color('#334155')
for sp in ['top', 'right']:
    ax_strip.spines[sp]\
            .set_visible(False)
ax_strip.grid(axis='x',
              color='#1E293B',
              lw=0.5, zorder=0)
ax_strip.set_xscale('log')

ax_strip.scatter(
    M_DISTS, M_YEARS,
    c=M_COLORS,
    s=[max(30, np.log10(d) * 15)
       for d in M_DISTS],
    zorder=5, alpha=0.9,
    edgecolors='#0D1117',
    linewidths=0.8)

# annotate 4 key ones
key_ann = [
    (1_374,      1966,
     'Gemini 11', '#3B82F6',  0, -1.8),
    (376_589,    1968,
     'Apollo 8',  '#F59E0B',  0,  1.8),
    (APOLLO_13_KM, 1970,
     'Apollo 13', '#EF4444',  0, -1.8),
    (ARTEMIS_II_KM, 2026,
     'Artemis II ✓', '#10B981', 0, 1.8),
]
for dist, yr, label, col, dx, dy in \
        key_ann:
    ax_strip.annotate(
        label,
        xy=(dist, yr),
        xytext=(dist, yr + dy),
        color=col, fontsize=8,
        ha='center',
        arrowprops=dict(
            arrowstyle='->',
            color=col, lw=0.8))

ax_strip.axvline(APOLLO_13_KM,
                 color='#EF4444',
                 lw=1.0, ls='--',
                 alpha=0.5)
ax_strip.axvline(ARTEMIS_II_KM,
                 color='#10B981',
                 lw=1.5, alpha=0.7)

ax_strip.set_xlim(100, 500_000)
ax_strip.set_ylim(1958, 2028)
ax_strip.set_xlabel(
    'Max distance from Earth (km)',
    color='#475569', fontsize=8)
ax_strip.set_ylabel(
    'Year', color='#475569',
    fontsize=8)

# ── FOOTER ────────────────────────────────────────────────────
card(0.25, 0.12, 19.5, 0.62,
     fc='#0F172A', ec='#1E293B')
txt(10.0, 0.44,
    f'Code Beyond the Earth  ·  '
    f'codebeyondtheearth.substack.com  ·  '
    f'Generated '
    f'{now_utc.strftime("%B %d, %Y  %H:%M UTC")}'
    f'  ·  Sources: NASA  ·  ESA  ·  '
    f'Roscosmos  ·  '
    f'Artemis II Flight Day 6 blog',
    fontsize=8, ha='center',
    color='#475569')

plt.savefig('artemis_day7_summary.png',
            dpi=150, facecolor='#0D1117',
            bbox_inches='tight')
plt.show()

print("=" * 58)
print("   DAY 7 COMPLETE — THE LONGEST JOURNEY")
print("=" * 58)
print(f"  Artemis II max  : {ARTEMIS_II_KM:,} km")
print(f"  Apollo 13 record: {APOLLO_13_KM:,} km")
print(f"  New margin      : +{MARGIN_KM:,} km")
print(f"  Record gap      : {RECORD_GAP} years")
print()
print("  Saved files:")
print("    artemis_distance_comparison.png")
print("    artemis_distance_timeline.gif")
print("    artemis_54year_gap.png")
print("    artemis_distance_profile.png")
print("    artemis_day7_summary.png")
print("=" * 58)