# -*- coding: utf-8 -*-
"""Trans-Lunar-Injection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pyfVzG_p8K2pzuOZhNTGy5DzigpPwi5n
"""

# ============================================================
# Artemis II — Trans-Lunar Injection (TLI) Analysis
# Vis-viva equation + Δv estimation
# Code Beyond the Earth | Day 2
# ============================================================

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as patches
from matplotlib.patches import Arc, FancyArrowPatch
import matplotlib.patheffects as pe
import matplotlib.animation as animation
from IPython.display import HTML
import matplotlib.gridspec as gridspec
from matplotlib.patches import FancyBboxPatch
from datetime import datetime

# --- Constants ---
GM = 3.986004418e14      # Earth's gravitational parameter [m³/s²]
R_earth = 6_371_000      # Earth's mean radius [m]

# --- Artemis II mission parameters ---
h_parking  = 185_000     # Parking orbit altitude [m]  (approx. Artemis II)
h_moon     = 384_400_000 # Mean Earth–Moon distance [m]

# --- Derived radii (from Earth's center) ---
r_parking = R_earth + h_parking
r_moon    = h_moon          # already center-to-center approx.

print(f"Parking orbit radius : {r_parking/1e6:.4f} × 10⁶ m")
print(f"Moon distance        : {r_moon/1e6:.1f} × 10⁶ m")

# ============================================================
# Cell 2 — Vis-viva: velocities & Δv
# ============================================================

# --- 1. Circular velocity in parking orbit ---
v_circular = np.sqrt(GM / r_parking)

# --- 2. Transfer ellipse semi-major axis ---
# Perigee = parking orbit, Apogee = Moon distance
a_transfer = (r_parking + r_moon) / 2

# --- 3. TLI velocity (vis-viva at perigee of transfer ellipse) ---
v_tli = np.sqrt(GM * (2/r_parking - 1/a_transfer))

# --- 4. Δv required ---
delta_v = v_tli - v_circular

# --- Print results ---
print("=" * 45)
print("       ARTEMIS II — TLI Δv BUDGET")
print("=" * 45)
print(f"  Parking orbit velocity  : {v_circular:.2f} m/s")
print(f"  TLI injection velocity  : {v_tli:.2f} m/s")
print(f"  Transfer orbit a        : {a_transfer/1e6:.2f} × 10⁶ m")
print(f"  Δv required             : {delta_v:.2f} m/s")
print(f"  Δv in km/s              : {delta_v/1000:.4f} km/s")
print("=" * 45)

# ============================================================
# Cell 3 — Validation against real NASA Artemis I telemetry
# Source: NASA Artemis I Mission Report + HORIZONS ephemeris
# ============================================================

# --- Real Artemis I TLI data (NASA published) ---
# TLI burn occurred ~1h 28m after launch
# ICPS burn duration: ~18 minutes

real_v_before_tli = 7_722.0    # m/s  velocity just before TLI burn
real_v_after_tli  = 10_870.0   # m/s  velocity just after TLI burn
real_delta_v      = real_v_after_tli - real_v_before_tli  # actual Δv delivered

# --- Our analytical results (from Cell 2) ---
analytical_delta_v = delta_v   # 3136.94 m/s

# --- Comparison ---
error_ms  = analytical_delta_v - real_delta_v
error_pct = (error_ms / real_delta_v) * 100

print("=" * 50)
print("   ANALYTICAL vs REAL ARTEMIS I TELEMETRY")
print("=" * 50)
print(f"  Real v before TLI  : {real_v_before_tli:.1f} m/s")
print(f"  Real v after TLI   : {real_v_after_tli:.1f} m/s")
print(f"  Real Δv delivered  : {real_delta_v:.1f} m/s")
print(f"  Our analytical Δv  : {analytical_delta_v:.2f} m/s")
print("-" * 50)
print(f"  Difference         : {error_ms:+.2f} m/s")
print(f"  Error              : {error_pct:+.2f}%")
print("=" * 50)

# --- Why the difference? ---
print("\n Sources of difference:")
print("  • Gravity losses during the ~18 min burn (not instantaneous)")
print("  • Real parking orbit altitude slightly different")
print("  • Trajectory optimized for free-return, not pure Hohmann")
print("  • Atmospheric drag residuals from ascent")

# ============================================================
# Cell 3 — Real Artemis II TLI Telemetry (LIVE - April 2, 2026)
# TLI burn scheduled: 8:12 p.m. EDT tonight - 3:12 AM Istanbul time
# Source: NASA Artemis blog + post-burn press conference
# ============================================================

# --- PLACEHOLDER: Update these after NASA confirms burn data ---
# Check: https://www.nasa.gov/blogs/missions/artemis-ii/
# Expected post-burn press conference tonight after 8:12 PM EDT

real_v_before_tli_AII = None   # m/s — velocity just before burn
real_v_after_tli_AII  = None   # m/s — velocity just after burn
burn_duration_AII     = 5*60 + 51  # seconds — 5 min 51 sec confirmed

# --- Known pre-burn orbital parameters (from NASA live updates) ---
# Orion is in a high Earth orbit after perigee + apogee raise burns
# Apogee raised to 43,730 miles = 70,363 km
apogee_km  = 70_363   # km (from Space.com live update)
perigee_km = None     # TBD from NASA (will be ~185-200 km range)

print("=" * 52)
print("   ARTEMIS II — TLI BURN STATUS")
print("=" * 52)
print(f"  Scheduled burn time : 8:12 PM EDT, April 2")
print(f"  Burn duration       : {burn_duration_AII} seconds")
print(f"  Current apogee      : {apogee_km:,} km")
print(f"  Status              : ⏳ AWAITING GO/NO-GO DECISION")
print("=" * 52)
print()
print("Watch live:")
print("  NASA+   : https://plus.nasa.gov")
print("  YouTube : https://youtube.com/@NASA")
print("  Blog    : https://nasa.gov/blogs/missions/artemis-ii")

# ============================================================
# Cell 4 — Visualization: Orbital diagram + Δv budget
# ============================================================

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 7))
fig.patch.set_facecolor('#0D1117')

# ── LEFT: Orbital diagram ──────────────────────────────────
ax1.set_facecolor('#0D1117')
ax1.set_xlim(-2.5, 6)
ax1.set_ylim(-4, 4)
ax1.set_aspect('equal')
ax1.axis('off')
ax1.set_title('Orbital geometry (not to scale)',
              color='#94A3B8', fontsize=11, pad=12)

# Earth
earth = plt.Circle((0, 0), 0.5, color='#1B4FD8', zorder=5)
ax1.add_patch(earth)
ax1.text(0, 0, 'Earth', color='white', ha='center',
         va='center', fontsize=9, fontweight='bold', zorder=6)

# Parking orbit
parking = plt.Circle((0, 0), 1.0, color='none',
                      ec='#94A3B8', lw=1.2, ls='--', zorder=4)
ax1.add_patch(parking)
ax1.text(-1.2, 0.8, 'Parking orbit\nh = 185 km\nv = 7,797 m/s',
         color='#94A3B8', fontsize=8.5, ha='center')

# Transfer ellipse (partial arc)
theta = np.linspace(0, np.pi * 0.75, 200)
a, b = 3.5, 1.8
x_ell = a * np.cos(theta) - 2.5
y_ell = b * np.sin(theta)
ax1.plot(x_ell, y_ell, color='#F59E0B', lw=2,
         ls='--', alpha=0.9, zorder=3)

# Arrow at end of arc
ax1.annotate('', xy=(x_ell[-1], y_ell[-1]),
             xytext=(x_ell[-10], y_ell[-10]),
             arrowprops=dict(arrowstyle='->', color='#F59E0B', lw=2))

# Moon label
ax1.text(3.3, 2.6, '→ Moon\n384,400 km', color='#F59E0B',
         fontsize=8.5, ha='left')

# TLI burn point
ax1.plot(1.0, 0, 'o', color='#F59E0B', ms=8, zorder=7)
ax1.annotate('TLI burn\n+3,137 m/s',
             xy=(1.0, 0), xytext=(1.8, -1.4),
             color='#F59E0B', fontsize=8.5,
             arrowprops=dict(arrowstyle='->', color='#F59E0B', lw=1))

# Spacecraft
ax1.plot(0, 1.0, 's', color='#10B981', ms=7, zorder=7)
ax1.text(0.15, 1.1, 'Orion', color='#10B981', fontsize=8.5)

# ── RIGHT: Velocity bar chart ──────────────────────────────
ax2.set_facecolor('#0D1117')
ax2.set_title('Velocity budget', color='#94A3B8',
              fontsize=11, pad=12)

labels  = ['v circular\n(LEO)', 'v TLI\n(after burn)', 'Δv\n(burn)']
values  = [v_circular, v_tli, delta_v]
colors  = ['#3B82F6', '#F59E0B', '#10B981']

bars = ax2.bar(labels, values, color=colors,
               alpha=0.85, width=0.5, zorder=3)

# Value labels on bars
for bar, val in zip(bars, values):
    ax2.text(bar.get_x() + bar.get_width()/2,
             bar.get_height() + 80,
             f'{val:,.0f} m/s',
             ha='center', va='bottom',
             color='white', fontsize=10, fontweight='bold')

# Δv annotation arrow
ax2.annotate('', xy=(2, delta_v), xytext=(1, v_tli),
             arrowprops=dict(arrowstyle='<->', color='#10B981',
                             lw=1.5, ls='dotted'))

ax2.set_facecolor('#0D1117')
ax2.tick_params(colors='#94A3B8')
ax2.spines['bottom'].set_color('#334155')
ax2.spines['left'].set_color('#334155')
ax2.spines['top'].set_visible(False)
ax2.spines['right'].set_visible(False)
ax2.set_ylabel('Velocity (m/s)', color='#94A3B8', fontsize=10)
ax2.yaxis.label.set_color('#94A3B8')
ax2.grid(axis='y', color='#1E293B', lw=0.8, zorder=0)

# Validation strip at bottom
fig.text(0.5, 0.01,
         f'Artemis I validation → Analytical: {delta_v:.2f} m/s  |  '
         f'Real telemetry: 3,148 m/s  |  Error: −0.35%  |  Difference: −11 m/s',
         ha='center', color='#64748B', fontsize=9)

plt.suptitle('Artemis II — Trans-Lunar Injection (TLI)',
             color='white', fontsize=14, fontweight='bold', y=1.01)
plt.tight_layout()
plt.savefig('artemis_tli.png', dpi=150, bbox_inches='tight',
            facecolor='#0D1117')
plt.show()
print("Plot saved as artemis_tli.png")

# ============================================================
# Cell 5 — Animated TLI burn
# Orion: parking orbit → TLI burn → transfer arc
# ============================================================

fig, ax = plt.subplots(figsize=(8, 8))
fig.patch.set_facecolor('#0D1117')
ax.set_facecolor('#0D1117')
ax.set_xlim(-2.8, 5.5)
ax.set_ylim(-3.5, 3.5)
ax.set_aspect('equal')
ax.axis('off')

# --- Static background elements ---

# Stars
np.random.seed(42)
sx = np.random.uniform(-2.8, 5.5, 120)
sy = np.random.uniform(-3.5, 3.5, 120)
ax.scatter(sx, sy, s=0.4, color='white', alpha=0.5, zorder=0)

# Earth
earth = plt.Circle((0, 0), 0.52, color='#1B4FD8', zorder=5)
ax.add_patch(earth)
# Earth atmosphere glow ring
atmo = plt.Circle((0, 0), 0.58, color='none',
                  ec='#3B82F6', lw=1.5, alpha=0.3, zorder=4)
ax.add_patch(atmo)
ax.text(0, 0, 'Earth', color='white', ha='center',
        va='center', fontsize=9, fontweight='bold', zorder=6)

# Parking orbit path
parking_circle = plt.Circle((0, 0), 1.1, color='none',
                             ec='#334155', lw=1.0, ls='--', zorder=2)
ax.add_patch(parking_circle)

# Transfer ellipse path (pre-drawn, faint)
theta_ell = np.linspace(0, np.pi * 0.85, 300)
a_ell, b_ell, cx_ell = 3.3, 1.5, -2.2
x_ell = cx_ell + a_ell * np.cos(theta_ell)
y_ell = b_ell * np.sin(theta_ell)
ax.plot(x_ell, y_ell, color='#F59E0B', lw=1.0,
        ls='--', alpha=0.2, zorder=2)

# Moon indicator
ax.text(4.8, 2.2, '☽ Moon', color='#94A3B8',
        fontsize=9, ha='right', alpha=0.7)
ax.annotate('', xy=(4.9, 1.9), xytext=(4.4, 1.9),
            arrowprops=dict(arrowstyle='->', color='#94A3B8',
                            lw=1, alpha=0.5))

# TLI burn marker (static dot at perigee)
ax.plot(1.1, 0, 'o', color='#F59E0B', ms=5,
        alpha=0.4, zorder=3)

# --- Phase parameters ---
N_orbit   = 60    # frames: Orion orbiting
N_burn    = 25    # frames: burn transition
N_escape  = 80    # frames: escape arc
N_total   = N_orbit + N_burn + N_escape

# Parking orbit angles
orbit_angles = np.linspace(0, 2.5 * np.pi, N_orbit)

# Escape arc subset
escape_idx = np.linspace(0, len(x_ell)-1, N_escape).astype(int)
x_escape = x_ell[escape_idx]
y_escape = y_ell[escape_idx]

# --- Dynamic elements ---
spacecraft, = ax.plot([], [], 's', color='#10B981',
                      ms=7, zorder=10)
trail,      = ax.plot([], [], '-', color='#10B981',
                      lw=1.2, alpha=0.5, zorder=9)
engine_glow,= ax.plot([], [], 'o', color='#F59E0B',
                      ms=0, zorder=8, alpha=0.8)

phase_text  = ax.text(-2.5, 3.1, '', color='#94A3B8',
                      fontsize=9, zorder=11)
vel_text    = ax.text(-2.5, 2.7, '', color='white',
                      fontsize=10, fontweight='bold', zorder=11)
dv_bar_bg   = ax.barh([-3.1], [3.137], left=0, height=0.25,
                      color='#1E293B', zorder=3)[0]
dv_bar      = ax.barh([-3.1], [0], left=0, height=0.25,
                      color='#10B981', zorder=4)[0]
ax.text(0, -3.22, 'Δv', color='#94A3B8', fontsize=8,
        ha='center', va='top')
ax.text(3.137, -3.22, '3,137 m/s', color='#94A3B8',
        fontsize=8, ha='right', va='top')

ax.set_title('Artemis II — Trans-Lunar Injection',
             color='white', fontsize=12, pad=10)

trail_x, trail_y = [], []

def init():
    spacecraft.set_data([], [])
    trail.set_data([], [])
    engine_glow.set_markersize(0)
    phase_text.set_text('')
    vel_text.set_text('')
    dv_bar.set_width(0)
    trail_x.clear()
    trail_y.clear()
    return spacecraft, trail, engine_glow, phase_text, vel_text, dv_bar

def update(frame):
    trail_x.clear()
    trail_y.clear()

    if frame < N_orbit:
        # Phase 1: parking orbit
        angle = orbit_angles[frame]
        x = 1.1 * np.cos(angle)
        y = 1.1 * np.sin(angle)
        # trail: last 20 frames
        start = max(0, frame - 20)
        for f in range(start, frame + 1):
            a = orbit_angles[f]
            trail_x.append(1.1 * np.cos(a))
            trail_y.append(1.1 * np.sin(a))

        spacecraft.set_data([x], [y])
        spacecraft.set_color('#10B981')
        trail.set_color('#10B981')
        engine_glow.set_markersize(0)
        phase_text.set_text('Phase 1: parking orbit')
        vel_text.set_text('v = 7,797 m/s')
        dv_bar.set_width(0)

    elif frame < N_orbit + N_burn:
        # Phase 2: burn!
        t = (frame - N_orbit) / N_burn
        x = 1.1
        y = (1 - t) * 0.0
        # interpolate velocity display
        v_current = v_circular + t * delta_v
        dv_current = t * delta_v

        spacecraft.set_data([x], [y])
        spacecraft.set_color('#F59E0B')
        trail.set_data([], [])
        # engine glow pulses
        glow_size = 12 + 8 * np.sin(frame * 0.8)
        engine_glow.set_data([x - 0.15], [y])
        engine_glow.set_markersize(glow_size)
        phase_text.set_text('Phase 2: TLI BURN FIRING')
        phase_text.set_color('#F59E0B')
        vel_text.set_text(f'v = {v_current:,.0f} m/s')
        dv_bar.set_width(dv_current)

    else:
        # Phase 3: escape arc
        i = frame - N_orbit - N_burn
        x = x_escape[i]
        y = y_escape[i]
        # trail: last 15 frames of escape
        start = max(0, i - 15)
        for j in range(start, i + 1):
            trail_x.append(x_escape[j])
            trail_y.append(y_escape[j])

        spacecraft.set_data([x], [y])
        spacecraft.set_color('#F59E0B')
        trail.set_color('#F59E0B')
        engine_glow.set_markersize(0)
        phase_text.set_text('Phase 3: trans-lunar trajectory')
        phase_text.set_color('#94A3B8')
        vel_text.set_text(f'v = {v_tli:,.0f} m/s  →  Moon')
        dv_bar.set_width(delta_v)

    trail.set_data(trail_x, trail_y)
    return spacecraft, trail, engine_glow, phase_text, vel_text, dv_bar

anim = animation.FuncAnimation(
    fig, update, frames=N_total,
    init_func=init, interval=60,
    blit=True
)

# Save as GIF (for blog embedding)
anim.save('artemis_tli.gif', writer='pillow', fps=24,
          dpi=120, savefig_kwargs={'facecolor': '#0D1117'})
print("GIF saved as artemis_tli.gif")

# Display in Colab
HTML(anim.to_jshtml())

# ============================================================
# Cell 6 — Velocity vector animation
# Shows v vector growing during TLI burn
# ============================================================
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation
from IPython.display import HTML

fig, (ax_orb, ax_vel) = plt.subplots(1, 2, figsize=(14, 7))
fig.patch.set_facecolor('#0D1117')

# ── LEFT: orbital view with live vector ───────────────────
ax_orb.set_facecolor('#0D1117')
ax_orb.set_xlim(-2.2, 2.2)
ax_orb.set_ylim(-2.2, 2.2)
ax_orb.set_aspect('equal')
ax_orb.axis('off')
ax_orb.set_title('Velocity vector in orbit',
                 color='white', fontsize=11, pad=10)

# Stars
np.random.seed(7)
ax_orb.scatter(np.random.uniform(-2.2, 2.2, 80),
               np.random.uniform(-2.2, 2.2, 80),
               s=0.3, color='white', alpha=0.4, zorder=0)

# Earth
earth = plt.Circle((0,0), 0.42, color='#1B4FD8', zorder=5)
ax_orb.add_patch(earth)
ax_orb.text(0, 0, 'Earth', color='white', ha='center',
            va='center', fontsize=8, fontweight='bold', zorder=6)

# Parking orbit
ax_orb.add_patch(plt.Circle((0,0), 1.0, color='none',
                 ec='#334155', lw=1.0, ls='--', zorder=2))

# Transfer arc (faint)
theta_e = np.linspace(0, np.pi*0.9, 200)
a_e, b_e, cx_e = 1.8, 0.9, -0.8
x_e = cx_e + a_e * np.cos(theta_e)
y_e = b_e * np.sin(theta_e)
ax_orb.plot(x_e, y_e, color='#F59E0B', lw=0.8,
            ls='--', alpha=0.15, zorder=2)

# Spacecraft dot
sc_dot, = ax_orb.plot([], [], 'o', color='#10B981',
                      ms=8, zorder=10)

# Velocity vector arrow (quiver)
quiv = ax_orb.quiver([], [], [], [],
                     angles='xy', scale_units='xy', scale=1,
                     color='#F59E0B', width=0.012,
                     headwidth=4, headlength=5, zorder=11)

# Tangent label
vec_label = ax_orb.text(0, 0, '', color='#F59E0B',
                        fontsize=8, zorder=12)

# Δv component arrow (shown during burn only)
dv_quiv = ax_orb.quiver([], [], [], [],
                        angles='xy', scale_units='xy', scale=1,
                        color='#10B981', width=0.010,
                        headwidth=4, headlength=5,
                        alpha=0, zorder=11)
dv_label = ax_orb.text(0, 0, '', color='#10B981', fontsize=8)

# ── RIGHT: velocity magnitude time series ─────────────────
ax_vel.set_facecolor('#0D1117')
ax_vel.set_xlim(0, 165)
ax_vel.set_ylim(7000, 11500)
ax_vel.set_xlabel('Frame', color='#94A3B8', fontsize=9)
ax_vel.set_ylabel('Velocity (m/s)', color='#94A3B8', fontsize=9)
ax_vel.set_title('Velocity magnitude over time',
                 color='white', fontsize=11, pad=10)
ax_vel.tick_params(colors='#94A3B8', labelsize=8)
ax_vel.spines['bottom'].set_color('#334155')
ax_vel.spines['left'].set_color('#334155')
ax_vel.spines['top'].set_visible(False)
ax_vel.spines['right'].set_visible(False)
ax_vel.grid(color='#1E293B', lw=0.6, zorder=0)

# Reference lines
ax_vel.axhline(v_circular, color='#3B82F6', lw=1.0,
               ls=':', alpha=0.6)
ax_vel.text(5, v_circular + 60, 'v circular',
            color='#3B82F6', fontsize=8)
ax_vel.axhline(v_tli, color='#F59E0B', lw=1.0,
               ls=':', alpha=0.6)
ax_vel.text(5, v_tli + 60, 'v TLI',
            color='#F59E0B', fontsize=8)

# Burn window shading
ax_vel.axvspan(60, 85, alpha=0.08, color='#F59E0B')
ax_vel.text(62, 11300, 'TLI burn', color='#F59E0B', fontsize=8)

# Live velocity line
vel_line, = ax_vel.plot([], [], color='#10B981',
                        lw=2.0, zorder=5)
vel_dot,  = ax_vel.plot([], [], 'o', color='#10B981',
                        ms=6, zorder=6)

# Readout box
readout = ax_vel.text(0.97, 0.05, '', transform=ax_vel.transAxes,
                      color='white', fontsize=11, fontweight='bold',
                      ha='right', va='bottom',
                      bbox=dict(boxstyle='round,pad=0.4',
                                facecolor='#1E293B',
                                edgecolor='#334155'))

# Phase label (left panel)
phase_lbl = ax_orb.text(-2.1, 2.0, '', color='#94A3B8', fontsize=9)

# ── Animation parameters ───────────────────────────────────
N_orbit  = 60
N_burn   = 25
N_escape = 80
N_total  = N_orbit + N_burn + N_escape

orbit_angles = np.linspace(np.pi/2, np.pi/2 + 2.5*np.pi, N_orbit)
escape_idx   = np.linspace(0, len(x_e)-1, N_escape).astype(int)
x_esc = x_e[escape_idx]
y_esc = y_e[escape_idx]

frames_all = []
vels_all   = []

def init():
    sc_dot.set_data([], [])
    vel_line.set_data([], [])
    vel_dot.set_data([], [])
    readout.set_text('')
    phase_lbl.set_text('')
    return sc_dot, vel_line, vel_dot, readout, phase_lbl

def update(frame):

    # ── position & velocity magnitude ──
    if frame < N_orbit:
        angle = orbit_angles[frame]
        x = np.cos(angle)
        y = np.sin(angle)
        # tangent direction (perpendicular to radius, prograde)
        vx_dir = -np.sin(angle)
        vy_dir =  np.cos(angle)
        v_mag  = v_circular
        vec_scale = 0.45
        phase = 'Phase 1: parking orbit'
        sc_dot.set_color('#10B981')
        dv_quiv.set_alpha(0)
        dv_label.set_text('')

    elif frame < N_orbit + N_burn:
        t = (frame - N_orbit) / N_burn
        # TLI burn at perigee (angle = 0, rightmost point)
        angle = 0.0
        x, y = 1.0, 0.0
        # prograde direction at perigee is +y
        vx_dir, vy_dir = 0.0, 1.0
        v_mag  = v_circular + t * delta_v
        vec_scale = 0.45 + 0.35 * t
        phase = 'Phase 2: TLI BURN FIRING'
        sc_dot.set_color('#F59E0B')

        # show Δv component arrow
        dv_scale = 0.35 * t
        dv_quiv.set_offsets([[x, y]])
        dv_quiv.set_UVC([vx_dir * dv_scale],
                        [vy_dir * dv_scale])
        dv_quiv.set_alpha(0.9)
        dv_label.set_position((x + 0.08,
                               y + vy_dir * dv_scale + 0.08))
        dv_label.set_text(f'+{t*delta_v:,.0f} m/s')

    else:
        i = frame - N_orbit - N_burn
        x = x_esc[min(i, len(x_esc)-1)]
        y = y_esc[min(i, len(y_esc)-1)]
        # tangent along escape arc
        if i < len(x_esc) - 1:
            dx = x_esc[i+1] - x_esc[i]
            dy = y_esc[i+1] - y_esc[i]
            norm = np.sqrt(dx**2 + dy**2) + 1e-9
            vx_dir, vy_dir = dx/norm, dy/norm
        else:
            vx_dir, vy_dir = 1.0, 0.0
        v_mag  = v_tli
        vec_scale = 0.80
        phase = 'Phase 3: trans-lunar trajectory'
        sc_dot.set_color('#F59E0B')
        dv_quiv.set_alpha(0)
        dv_label.set_text('')

    # ── update orbital panel ──
    sc_dot.set_data([x], [y])
    quiv.set_offsets([[x, y]])
    quiv.set_UVC([vx_dir * vec_scale], [vy_dir * vec_scale])
    vec_label.set_position((x + vx_dir * vec_scale + 0.05,
                            y + vy_dir * vec_scale + 0.05))
    vec_label.set_text(f'{v_mag:,.0f} m/s')
    phase_lbl.set_text(phase)

    # ── update velocity time series ──
    frames_all.append(frame)
    vels_all.append(v_mag)
    vel_line.set_data(frames_all, vels_all)
    vel_dot.set_data([frame], [v_mag])
    readout.set_text(f'{v_mag:,.0f} m/s')

    return (sc_dot, vel_line, vel_dot, readout,
            phase_lbl, quiv, dv_quiv, dv_label, vec_label)

anim2 = animation.FuncAnimation(
    fig, update, frames=N_total,
    init_func=init, interval=60, blit=True
)

plt.tight_layout()

# Save GIF
anim2.save('artemis_velocity_vector.gif', writer='pillow',
           fps=24, dpi=120,
           savefig_kwargs={'facecolor': '#0D1117'})
print("GIF saved as artemis_velocity_vector.gif")

HTML(anim2.to_jshtml())

# ============================================================
# Cell 7 — Hohmann transfer vs real Artemis II trajectory
# ============================================================

fig, axes = plt.subplots(1, 3, figsize=(16, 6))
fig.patch.set_facecolor('#0D1117')

# ── shared constants ────────────────────────────────────────
R_earth  = 6_371_000
GM       = 3.986004418e14
r_LEO    = R_earth + 185_000
r_moon   = 384_400_000

# ── PANEL 1: Hohmann geometry ───────────────────────────────
ax1 = axes[0]
ax1.set_facecolor('#0D1117')
ax1.set_xlim(-2.8, 2.8)
ax1.set_ylim(-2.8, 2.8)
ax1.set_aspect('equal')
ax1.axis('off')
ax1.set_title('Ideal Hohmann transfer',
              color='white', fontsize=11, pad=10)

# stars
np.random.seed(3)
ax1.scatter(np.random.uniform(-2.8,2.8,80),
            np.random.uniform(-2.8,2.8,80),
            s=0.3, color='white', alpha=0.4, zorder=0)

# Earth
ax1.add_patch(plt.Circle((0,0), 0.38, color='#1B4FD8', zorder=5))
ax1.text(0, 0, 'Earth', color='white', ha='center',
         va='center', fontsize=7, fontweight='bold', zorder=6)

# LEO
ax1.add_patch(plt.Circle((0,0), 0.7, color='none',
              ec='#3B82F6', lw=1.2, ls='--', zorder=3))
ax1.text(0, 0.73, 'LEO', color='#3B82F6',
         fontsize=7, ha='center', va='bottom')

# Lunar orbit
ax1.add_patch(plt.Circle((0,0), 2.4, color='none',
              ec='#94A3B8', lw=1.0, ls=':', zorder=3))
ax1.text(0, 2.43, "Moon's orbit", color='#94A3B8',
         fontsize=7, ha='center', va='bottom')

# Hohmann ellipse (semi-major = (r_LEO+r_moon)/2, scaled)
theta_h = np.linspace(0, np.pi, 300)
a_h = (0.7 + 2.4) / 2   # scaled
b_h = np.sqrt(0.7 * 2.4) # geometric mean approximation
cx_h = 0
x_h = cx_h + a_h * np.cos(theta_h)
y_h = b_h * np.sin(theta_h)
ax1.plot(x_h, y_h, color='#F59E0B', lw=2.0, zorder=4)
ax1.plot(-x_h, -y_h, color='#F59E0B', lw=2.0,
         ls='--', alpha=0.2, zorder=3)

# burn points
ax1.plot(0.7, 0, 'o', color='#10B981', ms=7, zorder=7)
ax1.text(0.75, -0.15, 'TLI burn', color='#10B981', fontsize=7)
ax1.plot(-2.4, 0, 'o', color='#EC4899', ms=7, zorder=7)
ax1.text(-2.35, -0.18, 'LOI burn', color='#EC4899', fontsize=7)

# Moon
ax1.add_patch(plt.Circle((-2.4, 0), 0.18, color='#94A3B8', zorder=5))
ax1.text(-2.4, 0, 'Moon', color='white', ha='center',
         va='center', fontsize=7, fontweight='bold', zorder=6)

# ── PANEL 2: Free-return trajectory ─────────────────────────
ax2 = axes[1]
ax2.set_facecolor('#0D1117')
ax2.set_xlim(-3.2, 3.2)
ax2.set_ylim(-2.5, 3.5)
ax2.set_aspect('equal')
ax2.axis('off')
ax2.set_title('Artemis II — free-return trajectory',
              color='white', fontsize=11, pad=10)

np.random.seed(5)
ax2.scatter(np.random.uniform(-3.2,3.2,80),
            np.random.uniform(-2.5,3.5,80),
            s=0.3, color='white', alpha=0.4, zorder=0)

# Earth
ax2.add_patch(plt.Circle((0,0), 0.38, color='#1B4FD8', zorder=5))
ax2.text(0, 0, 'Earth', color='white', ha='center',
         va='center', fontsize=7, fontweight='bold', zorder=6)

# Moon position (upper right)
moon_x, moon_y = 2.0, 2.0
ax2.add_patch(plt.Circle((moon_x, moon_y), 0.18,
              color='#94A3B8', zorder=5))
ax2.text(moon_x, moon_y, 'Moon', color='white', ha='center',
         va='center', fontsize=7, fontweight='bold', zorder=6)

# Free-return trajectory — figure-8 like loop
t_fr = np.linspace(0, 2*np.pi, 400)
# outbound leg
t_out = np.linspace(0, np.pi*0.85, 200)
x_out = 0.7*np.cos(t_out - np.pi/2) + 1.3*t_out/np.pi
y_out = 1.4*np.sin(t_out) + 0.2*t_out/np.pi
ax2.plot(x_out, y_out, color='#F59E0B', lw=2.0,
         zorder=4, label='outbound')

# lunar flyby arc
t_fly = np.linspace(np.pi*0.85, np.pi*1.3, 80)
x_fly = x_out[-1] + 0.3*np.cos(t_fly*2)
y_fly = y_out[-1] + 0.3*np.sin(t_fly*1.5)
ax2.plot(x_fly, y_fly, color='#EC4899', lw=2.0,
         zorder=4, label='lunar flyby')

# return leg
t_ret = np.linspace(0, 1, 150)
x_ret = np.linspace(x_fly[-1], 0.5, 150)
y_ret = x_ret * np.sin(t_ret * np.pi) * 0.6 - 0.5*t_ret
ax2.plot(x_ret, y_ret, color='#3B82F6', lw=2.0,
         ls='--', zorder=4, label='return leg')

# Splashdown
ax2.plot(0.5, y_ret[-1], 'v', color='#3B82F6', ms=8, zorder=7)
ax2.text(0.55, y_ret[-1]-0.15, 'Splashdown',
         color='#3B82F6', fontsize=7)

# TLI point
ax2.plot(x_out[0], y_out[0], 'o', color='#10B981', ms=7, zorder=7)
ax2.text(x_out[0]+0.1, y_out[0]-0.2, 'TLI',
         color='#10B981', fontsize=7)

# Labels
ax2.text(-3.0, 3.2, 'Free-return = gravity brings\nOrion home if engine fails',
         color='#94A3B8', fontsize=7.5, style='italic')

# Legend
handles = [patches.Patch(color='#F59E0B', label='Outbound'),
           patches.Patch(color='#EC4899', label='Lunar flyby'),
           patches.Patch(color='#3B82F6', label='Return')]
ax2.legend(handles=handles, loc='lower right',
           facecolor='#1E293B', edgecolor='#334155',
           labelcolor='white', fontsize=7)

# ── PANEL 3: Δv cost comparison ─────────────────────────────
ax3 = axes[2]
ax3.set_facecolor('#0D1117')
ax3.set_title('Δv cost: Hohmann vs free-return',
              color='white', fontsize=11, pad=10)
ax3.tick_params(colors='#94A3B8', labelsize=8)
ax3.spines['bottom'].set_color('#334155')
ax3.spines['left'].set_color('#334155')
ax3.spines['top'].set_visible(False)
ax3.spines['right'].set_visible(False)
ax3.grid(axis='x', color='#1E293B', lw=0.6, zorder=0)
ax3.set_xlabel('Δv (m/s)', color='#94A3B8', fontsize=9)

# ── compute Hohmann TLI Δv ──────────────────────────────────
a_hohmann  = (r_LEO + r_moon) / 2
v_h_perigee = np.sqrt(GM * (2/r_LEO - 1/a_hohmann))
dv_hohmann  = v_h_perigee - v_circular

# Free-return Δv (Artemis, slightly higher due to trajectory shaping)
dv_artemis = delta_v   # 3136.94 m/s

# Penalty
dv_penalty = dv_artemis - dv_hohmann

categories = ['Hohmann TLI\n(ideal)', 'Artemis II TLI\n(free-return)']
base_vals  = [dv_hohmann, dv_hohmann]
extra_vals = [0, dv_penalty]
colors_b   = ['#3B82F6', '#3B82F6']
colors_e   = ['none', '#F59E0B']

bars1 = ax3.barh(categories, base_vals, color='#3B82F6',
                 alpha=0.85, height=0.4, zorder=3)
bars2 = ax3.barh(categories, extra_vals, left=base_vals,
                 color='#F59E0B', alpha=0.85, height=0.4, zorder=3)

# Value labels
for bar, val in zip(bars1, base_vals):
    ax3.text(val/2, bar.get_y() + bar.get_height()/2,
             f'{val:,.0f}', ha='center', va='center',
             color='white', fontsize=9, fontweight='bold')

if dv_penalty > 0:
    b = bars2[1]
    ax3.text(dv_hohmann + dv_penalty/2,
             b.get_y() + b.get_height()/2,
             f'+{dv_penalty:.0f}', ha='center', va='center',
             color='#0D1117', fontsize=8, fontweight='bold')

# Total labels
for i, (bv, ev) in enumerate(zip(base_vals, extra_vals)):
    ax3.text(bv + ev + 15, i, f'{bv+ev:,.1f} m/s',
             va='center', color='white', fontsize=9)

# Legend
p1 = patches.Patch(color='#3B82F6', label='Base Hohmann Δv')
p2 = patches.Patch(color='#F59E0B', label='Free-return penalty')
ax3.legend(handles=[p1, p2], facecolor='#1E293B',
           edgecolor='#334155', labelcolor='white', fontsize=8)

# Annotation
ax3.text(dv_hohmann * 0.3, -0.55,
         'Free-return constraint adds safety\nbut costs extra propellant',
         color='#94A3B8', fontsize=7.5, style='italic')

ax3.set_xlim(0, dv_artemis * 1.15)

plt.suptitle('Hohmann transfer vs Artemis II free-return trajectory',
             color='white', fontsize=13, fontweight='bold', y=1.01)
plt.tight_layout()
plt.savefig('artemis_hohmann_comparison.png', dpi=150,
            bbox_inches='tight', facecolor='#0D1117')
plt.show()

# Print summary
print("=" * 52)
print("   HOHMANN vs FREE-RETURN Δv COMPARISON")
print("=" * 52)
print(f"  Ideal Hohmann TLI Δv   : {dv_hohmann:,.2f} m/s")
print(f"  Artemis II TLI Δv      : {dv_artemis:,.2f} m/s")
print(f"  Free-return penalty    : {dv_penalty:+.2f} m/s")
print(f"  Safety cost            : {dv_penalty/dv_hohmann*100:.2f}%")
print("=" * 52)
print("  Free-return = if engine fails after TLI,")
print("  Moon's gravity loops Orion safely home.")
print("=" * 52)

# ============================================================
# Cell 8 — Tsiolkovsky rocket equation
# How much propellant did the ICPS burn for TLI?
# ============================================================
# ── ICPS real specs (NASA published) ────────────────────────
Isp_icps    = 451.0        # specific impulse [s] (RL-10C-2 engine)
g0          = 9.80665      # standard gravity [m/s²]
m_dry_icps  = 3_490        # ICPS dry mass [kg]
m_prop_icps = 27_220       # usable propellant loaded [kg]  (LH2+LOX)
m_orion     = 26_520       # Orion spacecraft + crew [kg]
m0          = m_dry_icps + m_prop_icps + m_orion  # total wet mass

# ── Rocket equation: solve for propellant burned ─────────────
# Δv = Isp * g0 * ln(m0 / mf)
# → mf = m0 / exp(Δv / (Isp * g0))

v_exhaust   = Isp_icps * g0          # effective exhaust velocity
mass_ratio  = np.exp(delta_v / v_exhaust)
m_final     = m0 / mass_ratio
m_prop_used = m0 - m_final
m_prop_left = m_prop_icps - m_prop_used
prop_pct    = (m_prop_used / m_prop_icps) * 100

print("=" * 54)
print("   ICPS ROCKET EQUATION — TLI BURN")
print("=" * 54)
print(f"  Engine (RL-10C-2) Isp   : {Isp_icps} s")
print(f"  Exhaust velocity        : {v_exhaust:,.1f} m/s")
print(f"  Total wet mass (m0)     : {m0:,.0f} kg")
print(f"  Mass ratio (m0/mf)      : {mass_ratio:.4f}")
print(f"  Final mass (mf)         : {m_final:,.0f} kg")
print("-" * 54)
print(f"  Propellant burned       : {m_prop_used:,.0f} kg")
print(f"  Propellant remaining    : {m_prop_left:,.0f} kg")
print(f"  Burn fraction           : {prop_pct:.1f}% of tank")
print("-" * 54)
burn_time_est = m_prop_used / (22_000 / 451)   # thrust/ve ~ mdot
print(f"  Est. burn duration      : {burn_time_est:.0f} s  "
      f"({burn_time_est/60:.1f} min)")
print(f"  NASA confirmed duration : 351 s  (5 min 51 sec)")
print("=" * 54)

# ── Visualization ────────────────────────────────────────────
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 6))
fig.patch.set_facecolor('#0D1117')

# ── LEFT: mass breakdown stacked bar ────────────────────────
ax1.set_facecolor('#0D1117')
ax1.set_title('ICPS + Orion mass breakdown',
              color='white', fontsize=11, pad=10)
ax1.tick_params(colors='#94A3B8', labelsize=8)
ax1.spines['bottom'].set_color('#334155')
ax1.spines['left'].set_color('#334155')
ax1.spines['top'].set_visible(False)
ax1.spines['right'].set_visible(False)
ax1.set_ylabel('Mass (kg)', color='#94A3B8', fontsize=9)
ax1.grid(axis='y', color='#1E293B', lw=0.6, zorder=0)

states  = ['Before TLI\n(wet)', 'After TLI\n(dry-ish)']
orion   = [m_orion,     m_orion]
dry     = [m_dry_icps,  m_dry_icps]
burned  = [m_prop_used, 0]
leftover= [m_prop_left, m_prop_left]

x = np.arange(2)
w = 0.45

b1 = ax1.bar(x, orion, width=w, color='#3B82F6',
             alpha=0.85, label='Orion spacecraft', zorder=3)
b2 = ax1.bar(x, dry, width=w, bottom=orion,
             color='#94A3B8', alpha=0.85,
             label='ICPS dry mass', zorder=3)
b3 = ax1.bar(x, leftover, width=w,
             bottom=[m_orion+m_dry_icps]*2,
             color='#10B981', alpha=0.85,
             label=f'Propellant remaining', zorder=3)
b4 = ax1.bar(x[:1], [m_prop_used], width=w,
             bottom=[m_orion + m_dry_icps + m_prop_left],
             color='#F59E0B', alpha=0.85,
             label=f'Propellant burned ({prop_pct:.1f}%)', zorder=3)

# value labels inside bars
def label_bar(ax, bar, val, bottom=0):
    for b in bar:
        h = b.get_height()
        if h > 500:
            ax.text(b.get_x() + b.get_width()/2,
                    bottom + h/2,
                    f'{val:,.0f} kg',
                    ha='center', va='center',
                    color='white', fontsize=8, fontweight='bold')

label_bar(ax1, b1, m_orion)
label_bar(ax1, b2, m_dry_icps, m_orion)
label_bar(ax1, b3, m_prop_left, m_orion + m_dry_icps)
label_bar(ax1, [b4[0]], m_prop_used,
          m_orion + m_dry_icps + m_prop_left)

# total mass labels on top
for i, total in enumerate([m0, m_final]):
    ax1.text(i, total + 400, f'{total:,.0f} kg',
             ha='center', color='white',
             fontsize=9, fontweight='bold')

ax1.set_xticks(x)
ax1.set_xticklabels(states, color='#94A3B8')
ax1.legend(facecolor='#1E293B', edgecolor='#334155',
           labelcolor='white', fontsize=8, loc='upper right')

# ── RIGHT: Δv vs propellant curve (rocket eq.) ──────────────
ax2.set_facecolor('#0D1117')
ax2.set_title('Δv capability vs propellant burned',
              color='white', fontsize=11, pad=10)
ax2.tick_params(colors='#94A3B8', labelsize=8)
ax2.spines['bottom'].set_color('#334155')
ax2.spines['left'].set_color('#334155')
ax2.spines['top'].set_visible(False)
ax2.spines['right'].set_visible(False)
ax2.set_xlabel('Propellant burned (kg)', color='#94A3B8', fontsize=9)
ax2.set_ylabel('Δv achieved (m/s)',      color='#94A3B8', fontsize=9)
ax2.grid(color='#1E293B', lw=0.6, zorder=0)

# sweep propellant burned from 0 → full tank
mp_range = np.linspace(0, m_prop_icps, 500)
dv_range = v_exhaust * np.log(m0 / (m0 - mp_range))

ax2.plot(mp_range, dv_range, color='#3B82F6',
         lw=2.0, zorder=4, label='Rocket equation curve')

# mark our TLI point
ax2.axvline(m_prop_used, color='#F59E0B', lw=1.2,
            ls='--', alpha=0.7)
ax2.axhline(delta_v, color='#10B981', lw=1.2,
            ls='--', alpha=0.7)
ax2.plot(m_prop_used, delta_v, 'o', color='#F59E0B',
         ms=10, zorder=7, label='Artemis II TLI point')

ax2.text(m_prop_used + 200, delta_v + 60,
         f'({m_prop_used:,.0f} kg → {delta_v:,.0f} m/s)',
         color='#F59E0B', fontsize=8)

# escape velocity marker
dv_escape = v_exhaust * np.log(m0 / (m0 - m_prop_icps))
ax2.axhline(dv_escape * 0.85, color='#EC4899',
            lw=1.0, ls=':', alpha=0.5)
ax2.text(500, dv_escape * 0.85 + 60,
         'Full tank capacity', color='#EC4899', fontsize=8)

ax2.legend(facecolor='#1E293B', edgecolor='#334155',
           labelcolor='white', fontsize=8)

plt.suptitle("Tsiolkovsky rocket equation — ICPS TLI burn",
             color='white', fontsize=13, fontweight='bold', y=1.01)
plt.tight_layout()
plt.savefig('artemis_rocket_equation.png', dpi=150,
            bbox_inches='tight', facecolor='#0D1117')
plt.show()

# ============================================================
# Cell 9 — Specific orbital energy analysis (fixed)
# ε = v²/2 − GM/r
# ============================================================

# ── constants ────────────────────────────────────────────────
R_earth = 6_371_000
GM      = 3.986004418e14
r_LEO   = R_earth + 185_000
r_moon  = 384_400_000

def specific_energy(v, r):
    return (v**2 / 2) - (GM / r)

eps_LEO    = specific_energy(v_circular, r_LEO)
eps_TLI    = specific_energy(v_tli,      r_LEO)
v_esc_LEO  = np.sqrt(2 * GM / r_LEO)
eps_hyper  = specific_energy(v_esc_LEO * 1.05, r_LEO)

# ── timeline ─────────────────────────────────────────────────
N1, N2, N3 = 80, 40, 120
N_total    = N1 + N2 + N3

t1 = np.arange(N1)
e1 = np.full(N1, eps_LEO)

t2   = np.arange(N1, N1 + N2)
frac = np.linspace(0, 1, N2)
sig  = 1 / (1 + np.exp(-10 * (frac - 0.5)))
e2   = eps_LEO + (eps_TLI - eps_LEO) * sig

t3 = np.arange(N1 + N2, N_total)
e3 = np.full(N3, eps_TLI)

t_all = np.concatenate([t1, t2, t3])
e_MJ  = np.concatenate([e1, e2, e3]) / 1e6

# ── figure: explicit size, no gridspec ───────────────────────
fig = plt.figure(figsize=(15, 6))
fig.patch.set_facecolor('#0D1117')

ax_main  = fig.add_axes([0.05, 0.12, 0.55, 0.78])  # left wide panel
ax_gauge = fig.add_axes([0.65, 0.55, 0.32, 0.38])  # top right
ax_pie   = fig.add_axes([0.65, 0.08, 0.32, 0.38])  # bottom right

# ── MAIN: energy timeline ────────────────────────────────────
ax_main.set_facecolor('#0D1117')
ax_main.set_title('Specific orbital energy (ε) through TLI',
                  color='white', fontsize=12, pad=10)
ax_main.set_xlabel('Mission elapsed time (frames)',
                   color='#94A3B8', fontsize=9)
ax_main.set_ylabel('Specific orbital energy ε (MJ/kg)',
                   color='#94A3B8', fontsize=9)
ax_main.tick_params(colors='#94A3B8', labelsize=8)
for sp in ['bottom', 'left']:
    ax_main.spines[sp].set_color('#334155')
for sp in ['top', 'right']:
    ax_main.spines[sp].set_visible(False)
ax_main.grid(color='#1E293B', lw=0.6, zorder=0)

# phase shading
ax_main.axvspan(0,        N1,      alpha=0.06, color='#3B82F6')
ax_main.axvspan(N1,       N1+N2,   alpha=0.10, color='#F59E0B')
ax_main.axvspan(N1+N2,    N_total, alpha=0.06, color='#10B981')

# escape boundary
ax_main.axhline(0, color='#EC4899', lw=1.5, ls='--', alpha=0.8)
ax_main.text(2, 0.25, 'Escape boundary  (ε = 0)',
             color='#EC4899', fontsize=8, style='italic')

# energy curve + fills
ax_main.plot(t_all, e_MJ, color='#3B82F6', lw=2.5, zorder=5)
ax_main.fill_between(t_all, e_MJ, 0,
                     where=(e_MJ < 0),
                     color='#EF4444', alpha=0.10)
ax_main.fill_between(t_all, e_MJ, 0,
                     where=(e_MJ >= 0),
                     color='#10B981', alpha=0.10)

# key markers
ax_main.plot(0,       eps_LEO/1e6, 'o', color='#3B82F6', ms=9, zorder=7)
ax_main.plot(N1+N2,   eps_TLI/1e6, 'o', color='#F59E0B', ms=9, zorder=7)

ax_main.annotate(
    f'LEO  ε = {eps_LEO/1e6:.2f} MJ/kg',
    xy=(0, eps_LEO/1e6), xytext=(12, eps_LEO/1e6 - 4),
    color='#3B82F6', fontsize=8,
    arrowprops=dict(arrowstyle='->', color='#3B82F6', lw=1.2))

ax_main.annotate(
    f'Post-TLI  ε = {eps_TLI/1e6:.2f} MJ/kg',
    xy=(N1+N2, eps_TLI/1e6), xytext=(N1+N2+6, eps_TLI/1e6+1.5),
    color='#F59E0B', fontsize=8,
    arrowprops=dict(arrowstyle='->', color='#F59E0B', lw=1.2))

# phase labels
y_lbl = e_MJ.min() * 0.75
ax_main.text(N1/2,       y_lbl, 'Orbiting\nEarth',
             color='#3B82F6', fontsize=8, ha='center')
ax_main.text(N1+N2/2,    y_lbl*0.4, 'Burn!',
             color='#F59E0B', fontsize=9, ha='center', fontweight='bold')
ax_main.text(N1+N2+N3/2, eps_TLI/1e6*0.6, 'Coasting\nto Moon',
             color='#10B981', fontsize=8, ha='center')

# ── GAUGE: energy states ─────────────────────────────────────
ax_gauge.set_facecolor('#0D1117')
ax_gauge.set_title('Energy states', color='white', fontsize=9, pad=6)
ax_gauge.axis('off')

states = [
    ('LEO (parking)',    eps_LEO/1e6,   '#3B82F6'),
    ('Post-TLI',        eps_TLI/1e6,   '#F59E0B'),
    ('Escape boundary', 0.0,            '#EC4899'),
    ('Hyperbolic',      eps_hyper/1e6, '#10B981'),
]
e_min = eps_LEO/1e6 * 1.2
e_max = eps_hyper/1e6 * 1.1
y_positions = [0.78, 0.54, 0.30, 0.06]

for (label, val, color), yp in zip(states, y_positions):
    frac = np.clip((val - e_min) / (e_max - e_min), 0.03, 1.0)
    # track
    ax_gauge.barh(yp, 0.52, left=0.25, height=0.16,
                  color='#1E293B', zorder=2,
                  transform=ax_gauge.transAxes)
    # fill
    ax_gauge.barh(yp, 0.52*frac, left=0.25, height=0.16,
                  color=color, alpha=0.85, zorder=3,
                  transform=ax_gauge.transAxes)
    ax_gauge.text(0.23, yp, label, ha='right', va='center',
                  color='#94A3B8', fontsize=7.5,
                  transform=ax_gauge.transAxes)
    ax_gauge.text(0.79, yp, f'{val:.2f}',
                  ha='left', va='center', color='white',
                  fontsize=7.5, fontweight='bold',
                  transform=ax_gauge.transAxes)

# ── PIE: KE vs PE at TLI ─────────────────────────────────────
ax_pie.set_facecolor('#0D1117')
ax_pie.set_title('Energy components at TLI',
                 color='white', fontsize=9, pad=6)

KE = v_tli**2 / 2 / 1e6
PE = abs(GM / r_LEO  / 1e6)

wedges, _, autotexts = ax_pie.pie(
    [KE, PE],
    labels=['Kinetic', 'Potential\n(gravity well)'],
    autopct='%1.1f%%',
    colors=['#F59E0B', '#3B82F6'],
    startangle=90,
    wedgeprops=dict(edgecolor='#0D1117', linewidth=1.5),
    textprops=dict(color='#94A3B8', fontsize=8)
)
for at in autotexts:
    at.set_color('white')
    at.set_fontsize(9)
    at.set_fontweight('bold')

ax_pie.text(0, -1.5,
            f'KE={KE:.2f}  PE=−{PE:.2f}  ε={eps_TLI/1e6:.2f} MJ/kg',
            ha='center', color='#94A3B8', fontsize=7.5)

plt.suptitle('Specific orbital energy — bound orbit to lunar escape',
             color='white', fontsize=13, fontweight='bold',
             x=0.35, y=1.01)

plt.savefig('artemis_energy.png', dpi=120,
            facecolor='#0D1117')
plt.show()

print("=" * 54)
print("   SPECIFIC ORBITAL ENERGY SUMMARY")
print("=" * 54)
print(f"  ε at LEO      : {eps_LEO/1e6:.4f} MJ/kg  (bound)")
print(f"  ε post-TLI    : {eps_TLI/1e6:.4f} MJ/kg  (escaping)")
print(f"  Δε from burn  : {(eps_TLI-eps_LEO)/1e6:.4f} MJ/kg")
print(f"  Escape vel.   : {v_esc_LEO:.2f} m/s")
print(f"  TLI vel.      : {v_tli:.2f} m/s")
print(f"  Below escape  : {v_esc_LEO - v_tli:.2f} m/s")
print("=" * 54)
print("  Orion is below escape velocity → stays captured")
print("  in the Earth-Moon system, not lost to deep space.")
print("=" * 54)

# ============================================================
# Cell 10 — Free-return trajectory explainer
# Full Artemis II path: Earth → Moon flyby → return
# ============================================================

# ── physics helpers ──────────────────────────────────────────
GM_earth = 3.986004418e14
GM_moon  = 4.902800066e12
R_earth  = 6_371_000
R_moon   = 1_737_400
D_moon   = 384_400_000   # Earth-Moon distance

# ── build free-return trajectory (patched conic approx.) ────
# Outbound: half of transfer ellipse (Earth → Moon)
# Flyby:    hyperbolic arc around Moon
# Return:   mirror leg back to Earth

def transfer_ellipse(n=300):
    """Outbound leg — half ellipse from LEO to Moon distance."""
    a = (R_earth + 185_000 + D_moon) / 2
    e = 1 - (R_earth + 185_000) / a
    theta = np.linspace(0, np.pi, n)
    r = a * (1 - e**2) / (1 + e * np.cos(theta))
    # scale to plot units (D_moon = 1.0)
    scale = 1.0 / D_moon
    x = r * np.cos(theta) * scale
    y = r * np.sin(theta) * scale
    return x, y

def lunar_flyby(moon_x, moon_y, n=80):
    """Hyperbolic arc around the Moon."""
    angles = np.linspace(np.pi * 0.55, np.pi * 1.45, n)
    r_flyby = 0.06   # plot units
    x = moon_x + r_flyby * np.cos(angles)
    y = moon_y + r_flyby * np.sin(angles)
    return x, y

def return_leg(end_x, end_y, n=250):
    """Return arc — mirror of outbound, angled back to Earth."""
    t = np.linspace(0, 1, n)
    # cubic bezier control points for natural return curve
    p0 = np.array([end_x, end_y])
    p1 = np.array([end_x * 0.6, end_y * 1.3])
    p2 = np.array([-0.3, 0.4])
    p3 = np.array([0.0, 0.0])   # Earth
    x = ((1-t)**3*p0[0] + 3*(1-t)**2*t*p1[0] +
         3*(1-t)*t**2*p2[0] + t**3*p3[0])
    y = ((1-t)**3*p0[1] + 3*(1-t)**2*t*p1[1] +
         3*(1-t)*t**2*p2[1] + t**3*p3[1])
    return x, y

# build trajectory segments
x_out, y_out   = transfer_ellipse(300)
moon_x = x_out[-1]
moon_y = y_out[-1]
x_fly, y_fly   = lunar_flyby(moon_x, moon_y, 80)
x_ret, y_ret   = return_leg(x_fly[-1], y_fly[-1], 250)

# full path
x_full = np.concatenate([x_out, x_fly, x_ret])
y_full = np.concatenate([y_out, y_fly, y_ret])
N_full = len(x_full)

# day markers (approx. 10 days total)
N_out  = len(x_out)
N_fly  = len(x_fly)
N_ret  = len(x_ret)
day_indices = {
    'Day 1\nTLI burn':  5,
    'Day 4\nMoon arrival': N_out + N_fly//2,
    'Day 6\nFar side': N_out + N_fly - 5,
    'Day 10\nSplashdown': N_full - 5,
}

# ── static figure ────────────────────────────────────────────
fig, (ax_traj, ax_info) = plt.subplots(
    1, 2, figsize=(15, 8),
    gridspec_kw={'width_ratios': [1.6, 1]}
)
fig.patch.set_facecolor('#0D1117')

# ── LEFT: trajectory panel ───────────────────────────────────
ax_traj.set_facecolor('#0D1117')
ax_traj.set_xlim(-1.3, 1.3)
ax_traj.set_ylim(-0.8, 1.5)
ax_traj.set_aspect('equal')
ax_traj.axis('off')
ax_traj.set_title('Artemis II — free-return trajectory\n'
                  '(patched conic approximation)',
                  color='white', fontsize=11, pad=10)

# stars
np.random.seed(99)
ax_traj.scatter(
    np.random.uniform(-1.3, 1.3, 150),
    np.random.uniform(-0.8, 1.5, 150),
    s=0.3, color='white', alpha=0.5, zorder=0
)

# Earth
earth_c = plt.Circle((0,0), 0.055,
                      color='#1B4FD8', zorder=6)
ax_traj.add_patch(earth_c)
ax_traj.add_patch(plt.Circle((0,0), 0.062,
                  color='none', ec='#3B82F6',
                  lw=1.0, alpha=0.3, zorder=5))
ax_traj.text(0, -0.09, 'Earth', color='white',
             ha='center', fontsize=8, fontweight='bold')

# Moon
ax_traj.add_patch(plt.Circle((moon_x, moon_y), 0.045,
                  color='#6B7280', zorder=6))
ax_traj.text(moon_x, moon_y + 0.09, 'Moon',
             color='#94A3B8', ha='center', fontsize=8)

# full trajectory (faint background)
ax_traj.plot(x_out, y_out, color='#F59E0B',
             lw=1.0, alpha=0.15, zorder=2)
ax_traj.plot(x_fly, y_fly, color='#EC4899',
             lw=1.0, alpha=0.15, zorder=2)
ax_traj.plot(x_ret, y_ret, color='#3B82F6',
             lw=1.0, alpha=0.15, zorder=2)

# day markers
for label, idx in day_indices.items():
    idx = min(idx, N_full-1)
    ax_traj.plot(x_full[idx], y_full[idx], 'o',
                 color='white', ms=5, zorder=8, alpha=0.6)
    offset_x = 0.08 if x_full[idx] > 0 else -0.08
    ax_traj.text(x_full[idx] + offset_x,
                 y_full[idx],
                 label, color='#94A3B8',
                 fontsize=7, ha='center',
                 va='center', linespacing=1.4)

# splashdown marker
ax_traj.plot(x_ret[-1], y_ret[-1], 'v',
             color='#3B82F6', ms=9, zorder=9)
ax_traj.text(x_ret[-1], y_ret[-1] - 0.1,
             'Splashdown', color='#3B82F6',
             ha='center', fontsize=8)

# legend
handles = [
    patches.Patch(color='#F59E0B', label='Outbound (4 days)'),
    patches.Patch(color='#EC4899', label='Lunar flyby'),
    patches.Patch(color='#3B82F6', label='Return (4 days)'),
]
ax_traj.legend(handles=handles, loc='lower left',
               facecolor='#1E293B', edgecolor='#334155',
               labelcolor='white', fontsize=8)

# free-return annotation
ax_traj.text(-1.25, 1.42,
             'Free-return: if engine fails\nafter TLI, Moon gravity\n'
             'loops Orion safely home',
             color='#94A3B8', fontsize=7.5,
             style='italic', linespacing=1.5,
             bbox=dict(boxstyle='round,pad=0.4',
                       facecolor='#1E293B',
                       edgecolor='#334155'))

# animated elements
traj_line_out, = ax_traj.plot([], [], color='#F59E0B',
                               lw=2.0, zorder=4)
traj_line_fly, = ax_traj.plot([], [], color='#EC4899',
                               lw=2.0, zorder=4)
traj_line_ret, = ax_traj.plot([], [], color='#3B82F6',
                               lw=2.0, zorder=4, ls='--')
spacecraft,    = ax_traj.plot([], [], 's', color='white',
                               ms=7, zorder=10)
engine_dot,    = ax_traj.plot([], [], 'o', color='#F59E0B',
                               ms=0, zorder=9, alpha=0.8)

# ── RIGHT: info panel ────────────────────────────────────────
ax_info.set_facecolor('#0D1117')
ax_info.axis('off')
ax_info.set_title('Mission telemetry',
                  color='white', fontsize=11, pad=10)

# static info cards (text boxes)
info_items = [
    ('Mission',       'Artemis II',         'white'),
    ('Crew',          '4 astronauts',       '#94A3B8'),
    ('Duration',      '~10 days',           '#94A3B8'),
    ('Max distance',  '~400,000 km',        '#F59E0B'),
    ('TLI Δv',        f'{delta_v:,.0f} m/s','#10B981'),
    ('Trajectory',    'Free-return',        '#3B82F6'),
    ('Engine',        'OMS-E (6,000 lbf)',  '#94A3B8'),
    ('Splashdown',    'Pacific Ocean',      '#3B82F6'),
]

for i, (label, val, color) in enumerate(info_items):
    y_pos = 0.92 - i * 0.115
    ax_info.text(0.05, y_pos, label + ':',
                 transform=ax_info.transAxes,
                 color='#475569', fontsize=9, va='center')
    ax_info.text(0.42, y_pos, val,
                 transform=ax_info.transAxes,
                 color=color, fontsize=9,
                 fontweight='bold', va='center')
    # divider
    if i < len(info_items) - 1:
        ax_info.plot([0.03, 0.97],
                     [y_pos - 0.055, y_pos - 0.055],
                     color='#1E293B', lw=0.6,
                     transform=ax_info.transAxes,
                     zorder=1)

# live phase + distance display
phase_box = ax_info.text(
    0.5, 0.08,
    'Phase: pre-launch',
    transform=ax_info.transAxes,
    color='white', fontsize=9, ha='center',
    bbox=dict(boxstyle='round,pad=0.5',
              facecolor='#1E293B',
              edgecolor='#334155')
)
dist_box = ax_info.text(
    0.5, 0.02,
    'Distance from Earth: 0 km',
    transform=ax_info.transAxes,
    color='#94A3B8', fontsize=8, ha='center'
)

# progress bar background
ax_info.add_patch(patches.FancyBboxPatch(
    (0.05, 0.155), 0.90, 0.025,
    boxstyle='round,pad=0.01',
    facecolor='#1E293B', edgecolor='#334155',
    transform=ax_info.transAxes, zorder=2
))
progress_bar = ax_info.add_patch(patches.FancyBboxPatch(
    (0.05, 0.155), 0.0, 0.025,
    boxstyle='round,pad=0.01',
    facecolor='#F59E0B', edgecolor='none',
    transform=ax_info.transAxes, zorder=3
))
ax_info.text(0.5, 0.21, 'Mission progress',
             transform=ax_info.transAxes,
             color='#475569', fontsize=8, ha='center')

# ── animation ────────────────────────────────────────────────
STEP = 3   # skip frames for speed

def init():
    traj_line_out.set_data([], [])
    traj_line_fly.set_data([], [])
    traj_line_ret.set_data([], [])
    spacecraft.set_data([], [])
    engine_dot.set_markersize(0)
    phase_box.set_text('Phase: pre-launch')
    dist_box.set_text('Distance from Earth: 0 km')
    progress_bar.set_width(0)
    return (traj_line_out, traj_line_fly, traj_line_ret,
            spacecraft, engine_dot, phase_box,
            dist_box, progress_bar)

def update(frame):
    i = frame * STEP
    i = min(i, N_full - 1)

    # which segment?
    if i < N_out:
        # outbound
        traj_line_out.set_data(x_out[:i+1], y_out[:i+1])
        x, y = x_out[i], y_out[i]
        phase = 'Phase: outbound to Moon'
        sc_color = '#F59E0B'
        # engine glow only at start (TLI burn)
        glow = 10 * np.exp(-i/25) if i < 40 else 0
        engine_dot.set_data([x - 0.02], [y])
        engine_dot.set_markersize(glow)

    elif i < N_out + N_fly:
        # flyby
        j = i - N_out
        traj_line_out.set_data(x_out, y_out)
        traj_line_fly.set_data(x_fly[:j+1], y_fly[:j+1])
        x, y = x_fly[j], y_fly[j]
        phase = 'Phase: lunar flyby'
        sc_color = '#EC4899'
        engine_dot.set_markersize(0)

    else:
        # return
        j = i - N_out - N_fly
        traj_line_out.set_data(x_out, y_out)
        traj_line_fly.set_data(x_fly, y_fly)
        traj_line_ret.set_data(x_ret[:j+1], y_ret[:j+1])
        x, y = x_ret[j], y_ret[j]
        phase = 'Phase: return to Earth'
        sc_color = '#3B82F6'
        engine_dot.set_markersize(0)

    spacecraft.set_data([x], [y])
    spacecraft.set_color(sc_color)

    # distance from Earth (plot units → km)
    dist_km = np.sqrt(x**2 + y**2) * D_moon / 1000
    dist_box.set_text(f'Distance from Earth: {dist_km:,.0f} km')
    phase_box.set_text(phase)

    # progress bar
    prog = min(i / N_full * 0.90, 0.90)
    progress_bar.set_width(prog)

    return (traj_line_out, traj_line_fly, traj_line_ret,
            spacecraft, engine_dot, phase_box,
            dist_box, progress_bar)

N_frames = N_full // STEP + 1
anim10 = animation.FuncAnimation(
    fig, update, frames=N_frames,
    init_func=init, interval=40, blit=True
)

plt.tight_layout()
plt.savefig('artemis_free_return.png', dpi=120,
            facecolor='#0D1117')

anim10.save('artemis_free_return.gif', writer='pillow',
            fps=30, dpi=100,
            savefig_kwargs={'facecolor': '#0D1117'})
print("Saved: artemis_free_return.gif")

HTML(anim10.to_jshtml())

# ============================================================
# Cell 12 — Mission summary dashboard
# Pulls all results from Cells 1–11 into one visual
# ============================================================

fig = plt.figure(figsize=(16, 10))
fig.patch.set_facecolor('#0D1117')

# ── full-canvas axes ─────────────────────────────────────────
ax = fig.add_axes([0, 0, 1, 1])
ax.set_xlim(0, 16)
ax.set_ylim(0, 10)
ax.axis('off')
ax.set_facecolor('#0D1117')

# ── helper: rounded card ─────────────────────────────────────
def card(x, y, w, h, color='#1E293B', ec='#334155'):
    ax.add_patch(FancyBboxPatch(
        (x, y), w, h,
        boxstyle='round,pad=0.08',
        facecolor=color, edgecolor=ec,
        linewidth=0.8, zorder=2
    ))

def txt(x, y, s, **kw):
    kw.setdefault('color', 'white')
    kw.setdefault('fontsize', 10)
    kw.setdefault('zorder', 3)
    kw.setdefault('va', 'center')
    ax.text(x, y, s, **kw)

# ════════════════════════════════════════════════════════════
# HEADER
# ════════════════════════════════════════════════════════════
card(0.2, 8.8, 15.6, 1.0, color='#0F172A', ec='#1E3A5F')
txt(8.0, 9.38, 'ARTEMIS II — TRANS-LUNAR INJECTION ANALYSIS',
    fontsize=15, fontweight='bold', ha='center',
    color='white')
txt(8.0, 9.05,
    'Code Beyond the Earth  ·  Vis-viva equation  ·  '
    'Real NASA telemetry validation  ·  April 2, 2026',
    fontsize=9, ha='center', color='#64748B')

# ════════════════════════════════════════════════════════════
# ROW 1 — four key metric cards
# ════════════════════════════════════════════════════════════
metrics = [
    ('Parking orbit',  '185 km',          'h above Earth',    '#378ADD'),
    ('v circular',     f'{v_circular:,.0f} m/s', 'LEO speed', '#378ADD'),
    ('v TLI',          f'{v_tli:,.0f} m/s','after burn',       '#F59E0B'),
    ('Δv required',    f'{delta_v:,.0f} m/s','TLI burn',       '#10B981'),
]
for i, (label, val, sub, col) in enumerate(metrics):
    x0 = 0.2 + i * 3.95
    card(x0, 7.35, 3.7, 1.25, color='#0F172A', ec=col)
    txt(x0+1.85, 8.22, label, fontsize=9, color='#64748B', ha='center')
    txt(x0+1.85, 7.88, val,   fontsize=16, fontweight='bold',
        color=col, ha='center')
    txt(x0+1.85, 7.55, sub,   fontsize=8,  color='#475569', ha='center')

# ════════════════════════════════════════════════════════════
# ROW 2 LEFT — validation results
# ════════════════════════════════════════════════════════════
card(0.2, 4.7, 4.9, 2.45)
txt(2.65, 6.9, 'Artemis I validation', fontsize=10,
    fontweight='bold', ha='center', color='white')

val_rows = [
    ('Real Δv (telemetry)', '3,148 m/s',   '#94A3B8'),
    ('Our analytical Δv',  f'{delta_v:.2f} m/s', '#F59E0B'),
    ('Difference',         '−11 m/s',      '#94A3B8'),
    ('Error',              '−0.35%',        '#10B981'),
]
for j, (lbl, val, col) in enumerate(val_rows):
    y = 6.55 - j * 0.44
    txt(0.45, y, lbl, fontsize=9, color='#64748B', ha='left')
    txt(5.0,  y, val, fontsize=9, color=col,
        fontweight='bold', ha='right')
    if j < len(val_rows)-1:
        ax.plot([0.4, 5.05], [y-0.22, y-0.22],
                color='#1E293B', lw=0.6, zorder=3)

# big error callout
card(0.3, 4.78, 1.5, 0.9, color='#052e16', ec='#166534')
txt(1.05, 5.23, '−0.35%', fontsize=14, fontweight='bold',
    color='#4ade80', ha='center')
txt(1.05, 4.95, 'error', fontsize=8, color='#166534', ha='center')

# ════════════════════════════════════════════════════════════
# ROW 2 CENTRE — rocket equation results
# ════════════════════════════════════════════════════════════
card(5.3, 4.7, 4.9, 2.45)
txt(7.75, 6.9, 'Tsiolkovsky rocket equation',
    fontsize=10, fontweight='bold', ha='center')

# ICPS specs
Isp     = 451.0
g0      = 9.80665
m_dry   = 3_490
m_prop  = 27_220
m_orion = 26_520
m0      = m_dry + m_prop + m_orion
ve      = Isp * g0
mr      = np.exp(delta_v / ve)
mf      = m0 / mr
mp_used = m0 - mf
pct     = mp_used / m_prop * 100

rkt_rows = [
    ('ICPS Isp (RL-10C-2)', f'{Isp:.0f} s',          '#94A3B8'),
    ('Wet mass (m₀)',       f'{m0:,.0f} kg',           '#94A3B8'),
    ('Propellant burned',   f'{mp_used:,.0f} kg',      '#F59E0B'),
    ('Burn fraction',       f'{pct:.1f}% of tank',     '#10B981'),
]
for j, (lbl, val, col) in enumerate(rkt_rows):
    y = 6.55 - j * 0.44
    txt(5.5,  y, lbl, fontsize=9, color='#64748B', ha='left')
    txt(10.1, y, val, fontsize=9, color=col,
        fontweight='bold', ha='right')
    if j < len(rkt_rows)-1:
        ax.plot([5.45, 10.15], [y-0.22, y-0.22],
                color='#1E293B', lw=0.6, zorder=3)

# ════════════════════════════════════════════════════════════
# ROW 2 RIGHT — energy + free-return
# ════════════════════════════════════════════════════════════
card(10.4, 4.7, 5.4, 2.45)
txt(13.1, 6.9, 'Orbital energy + trajectory',
    fontsize=10, fontweight='bold', ha='center')

eps_LEO = (v_circular**2/2) - (3.986e14/(6371000+185000))
eps_TLI = (v_tli**2/2)      - (3.986e14/(6371000+185000))
v_esc   = np.sqrt(2*3.986e14/(6371000+185000))

en_rows = [
    ('ε at LEO',          f'{eps_LEO/1e6:.2f} MJ/kg', '#EF4444'),
    ('ε post-TLI',        f'{eps_TLI/1e6:.2f} MJ/kg', '#F59E0B'),
    ('v escape (LEO)',    f'{v_esc:,.0f} m/s',          '#94A3B8'),
    ('Below escape',      f'{v_esc-v_tli:.0f} m/s',    '#10B981'),
]
for j, (lbl, val, col) in enumerate(en_rows):
    y = 6.55 - j * 0.44
    txt(10.6,  y, lbl, fontsize=9, color='#64748B', ha='left')
    txt(15.7,  y, val, fontsize=9, color=col,
        fontweight='bold', ha='right')
    if j < len(en_rows)-1:
        ax.plot([10.55, 15.75], [y-0.22, y-0.22],
                color='#1E293B', lw=0.6, zorder=3)

# ════════════════════════════════════════════════════════════
# ROW 3 — mini velocity bar chart
# ════════════════════════════════════════════════════════════
card(0.2, 1.1, 7.5, 3.4)
txt(3.95, 4.28, 'Velocity budget', fontsize=10,
    fontweight='bold', ha='center')

bar_data = [
    ('v circular\n185 km LEO', v_circular, '#378ADD'),
    ('v TLI\npost-burn',       v_tli,      '#F59E0B'),
    ('v escape\nfrom LEO',     v_esc,      '#10B981'),
    ('Δv burn\nICPS',          delta_v,    '#EC4899'),
]
bar_max = v_esc * 1.08
bar_w   = 1.55
for i, (lbl, val, col) in enumerate(bar_data):
    bx = 0.45 + i * 1.82
    bh = val / bar_max * 2.4
    by = 1.3
    ax.add_patch(FancyBboxPatch(
        (bx, by), bar_w, bh,
        boxstyle='round,pad=0.04',
        facecolor=col, alpha=0.85,
        edgecolor='none', zorder=3
    ))
    txt(bx + bar_w/2, by + bh + 0.18,
        f'{val/1000:.2f}\nkm/s',
        fontsize=8, ha='center', color=col, fontweight='bold')
    txt(bx + bar_w/2, by - 0.25, lbl,
        fontsize=7.5, ha='center', color='#64748B')

# ════════════════════════════════════════════════════════════
# ROW 3 RIGHT — mission timeline
# ════════════════════════════════════════════════════════════
card(7.9, 1.1, 7.9, 3.4)
txt(11.85, 4.28, 'Artemis II mission timeline',
    fontsize=10, fontweight='bold', ha='center')

timeline = [
    ('Apr 1  T+00:00', 'Launch — KSC LC-39B',        '#378ADD'),
    ('Apr 1  T+00:08', 'SRB separation',              '#64748B'),
    ('Apr 1  T+00:12', 'Core stage separation',       '#64748B'),
    ('Apr 1  T+01:28', 'Parking orbit achieved',      '#10B981'),
    ('Apr 2  T+25:37', 'TLI burn — 5 min 51 sec',    '#F59E0B'),
    ('Apr 6         ', 'Lunar closest approach',      '#EC4899'),
    ('Apr 11        ', 'Splashdown — Pacific Ocean',  '#378ADD'),
]
for j, (time, event, col) in enumerate(timeline):
    y = 4.0 - j * 0.41
    # dot
    ax.plot(8.15, y, 'o', color=col, ms=5, zorder=4)
    # line
    if j < len(timeline)-1:
        ax.plot([8.15, 8.15], [y-0.41, y-0.06],
                color='#334155', lw=1.0, zorder=3)
    txt(8.35, y, time, fontsize=8, color='#64748B', ha='left')
    txt(10.6,  y, event, fontsize=8.5, color=col,
        fontweight='bold', ha='left')

# ════════════════════════════════════════════════════════════
# FOOTER
# ════════════════════════════════════════════════════════════
card(0.2, 0.15, 15.6, 0.75, color='#0F172A', ec='#1E293B')
now = datetime.now().strftime('%B %d, %Y')
txt(8.0, 0.53,
    f'Code Beyond the Earth  ·  codebeyondtheearth.hashnode.dev  '
    f'·  Generated {now}  ·  Data: NASA Artemis II mission',
    fontsize=8, ha='center', color='#475569')

# ════════════════════════════════════════════════════════════
# save
# ════════════════════════════════════════════════════════════
plt.savefig('artemis_summary.png', dpi=150,
            facecolor='#0D1117', bbox_inches='tight')
plt.show()

# ── terminal summary ─────────────────────────────────────────
print("=" * 60)
print("   ARTEMIS II TLI — COMPLETE NOTEBOOK SUMMARY")
print("=" * 60)
print(f"  Cell 1  Constants & setup")
print(f"  Cell 2  Vis-viva → Δv = {delta_v:,.2f} m/s")
print(f"  Cell 3  Artemis I validation → error = −0.35%")
print(f"  Cell 4  Orbital + velocity visualization")
print(f"  Cell 5  TLI burn animation (GIF)")
print(f"  Cell 6  Velocity vector animation (GIF)")
print(f"  Cell 7  Hohmann vs free-return comparison")
print(f"  Cell 8  Rocket equation → {mp_used:,.0f} kg burned")
print(f"  Cell 9  Orbital energy: ε = {eps_TLI/1e6:.2f} MJ/kg")
print(f"  Cell 10 Free-return trajectory animation (GIF)")
print(f"  Cell 11 Interactive Δv calculator (HTML)")
print(f"  Cell 12 This summary dashboard")
print("=" * 60)
print(f"  Saved files:")
print(f"    artemis_tli.png")
print(f"    artemis_tli.gif")
print(f"    artemis_velocity_vector.gif")
print(f"    artemis_hohmann_comparison.png")
print(f"    artemis_rocket_equation.png")
print(f"    artemis_energy.png")
print(f"    artemis_free_return.gif")
print(f"    artemis_free_return.png")
print(f"    tli_calculator.html")
print(f"    artemis_summary.png  ← blog header image")
print("=" * 60)
print(f"  Tonight: update Cell 3 with real Artemis II")
print(f"  TLI data after 8:12 PM EDT burn. Watch NASA+!")
print("=" * 60)

